#!/usr/bin/env bash
# Regenerate shaders.rs from convert.vert and convert.frag. Requires glslc
# and spirv-val (the Vulkan SDK or shaderc).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
scratch="$(mktemp -d)"
trap 'rm -rf "${scratch}"' EXIT
for stage in vert frag; do
    glslc --target-env=vulkan1.1 -O "convert.${stage}" -o "${scratch}/${stage}.spv"
    spirv-val --target-env vulkan1.1 "${scratch}/${stage}.spv"
done
python3 - "${scratch}" "$(glslc --version | head -1)" > shaders.rs <<'PY'
import struct, sys
scratch, version = sys.argv[1], sys.argv[2]
print("// Generated by generate.sh from convert.vert and convert.frag with")
print(f"// {version}. Do not edit by hand.")
for stage, name in (("vert", "VERTEX"), ("frag", "FRAGMENT")):
    data = open(f"{scratch}/{stage}.spv", "rb").read()
    words = struct.unpack(f"<{len(data) // 4}I", data)
    print()
    print(f"pub(super) const {name}: &[u32] = &[")
    for index in range(0, len(words), 8):
        print("    " + ", ".join(f"0x{word:08x}" for word in words[index:index + 8]) + ",")
    print("];")
PY
