//! @generated by the Metal campaign authority; do not edit by hand.
#![allow(unused_imports)]

use crate::mechanical_port::source::renderer::include::rive::renderer::gpu_resource_hpp as _;
use crate::mechanical_port::source::renderer::include::rive::renderer::ore::ore_bind_group_hpp as _;
use crate::mechanical_port::source::renderer::include::rive::renderer::ore::ore_bind_group_layout_hpp as _;
use crate::mechanical_port::source::renderer::include::rive::renderer::ore::ore_binding_map_hpp as _;
use crate::mechanical_port::source::renderer::include::rive::renderer::ore::ore_buffer_hpp as _;
use crate::mechanical_port::source::renderer::include::rive::renderer::ore::ore_context_hpp as _;
use crate::mechanical_port::source::renderer::include::rive::renderer::ore::ore_context_metal_hpp as _;
use crate::mechanical_port::source::renderer::include::rive::renderer::ore::ore_pipeline_hpp as _;
use crate::mechanical_port::source::renderer::include::rive::renderer::ore::ore_render_pass_hpp as _;
use crate::mechanical_port::source::renderer::include::rive::renderer::ore::ore_rstb_entry_container_hpp as _;
use crate::mechanical_port::source::renderer::include::rive::renderer::ore::ore_sampler_hpp as _;
use crate::mechanical_port::source::renderer::include::rive::renderer::ore::ore_shader_module_hpp as _;
use crate::mechanical_port::source::renderer::include::rive::renderer::ore::ore_texture_hpp as _;
use crate::mechanical_port::source::renderer::include::rive::renderer::ore::ore_types_hpp as _;
use crate::mechanical_port::source::renderer::src::gpu_resource_cpp as _;
use crate::mechanical_port::source::renderer::src::ore::metal::ore_bind_group_metal_hpp as _;
use crate::mechanical_port::source::renderer::src::ore::metal::ore_bind_group_metal_mm as _;
use crate::mechanical_port::source::renderer::src::ore::metal::ore_buffer_metal_hpp as _;
use crate::mechanical_port::source::renderer::src::ore::metal::ore_buffer_metal_mm as _;
use crate::mechanical_port::source::renderer::src::ore::metal::ore_context_metal_mm as _;
use crate::mechanical_port::source::renderer::src::ore::metal::ore_pipeline_metal_hpp as _;
use crate::mechanical_port::source::renderer::src::ore::metal::ore_pipeline_metal_mm as _;
use crate::mechanical_port::source::renderer::src::ore::metal::ore_render_pass_metal_hpp as _;
use crate::mechanical_port::source::renderer::src::ore::metal::ore_render_pass_metal_mm as _;
use crate::mechanical_port::source::renderer::src::ore::metal::ore_sampler_metal_hpp as _;
use crate::mechanical_port::source::renderer::src::ore::metal::ore_sampler_metal_mm as _;
use crate::mechanical_port::source::renderer::src::ore::metal::ore_shader_module_metal_hpp as _;
use crate::mechanical_port::source::renderer::src::ore::metal::ore_shader_module_metal_mm as _;
use crate::mechanical_port::source::renderer::src::ore::metal::ore_texture_metal_hpp as _;
use crate::mechanical_port::source::renderer::src::ore::metal::ore_texture_metal_mm as _;
use crate::mechanical_port::source::renderer::src::ore::ore_bind_group_layout_cpp as _;
use crate::mechanical_port::source::renderer::src::ore::ore_binding_map_cpp as _;

pub(crate) const MANIFEST_TARGET_COUNT: usize = 32;
const _: [(); MANIFEST_TARGET_COUNT] = [(); MANIFEST_TARGET_COUNT];
