[package]
name = "nux-apple-product-extension"
version = "0.7.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]

[features]
default = []
apple-runtime = ["nux-capi/apple-metal", "nux-capi/scripting"]

[dependencies]
nux-capi = { path = "../nux-capi", default-features = false }
nuxie-project-data = { path = "../nuxie-project-data" }

[dev-dependencies]
nuxie-schema = { path = "../nuxie-schema" }

[lints]
workspace = true
