# Generated dependency metadata. Rust sources stay in their owning package.
[package]
name = "taffy"
version = "0.12.1"
edition = "2021"
autobins = false
autoexamples = false
autotests = false
autobenches = false
build = false

[lib]
path = "lib.rs"
name = "taffy"

[features]
"alloc" = ["serde?/alloc"]
"block_layout" = []
"calc" = []
"content_size" = []
"debug" = ["std"]
"__bazel_dependency_default" = ["std", "taffy_tree", "flexbox", "grid", "block_layout", "float_layout", "calc", "content_size", "detailed_layout_info"]
"detailed_layout_info" = []
"flexbox" = []
"float_layout" = []
"grid" = ["alloc", "dep:grid"]
"parse" = ["dep:cssparser"]
"parse_faster" = ["parse", "cssparser/fast_match_byte"]
"profile" = ["std"]
"serde" = ["dep:serde"]
"std" = ["grid?/std", "serde?/std", "slotmap?/std"]
"strict_provenance" = []
"taffy_tree" = ["dep:slotmap"]
"default" = []

[dependencies]
"arrayvec" = { "version" = "0.7", "default-features" = false }
"cssparser" = { "version" = "0.37.0", "optional" = true, "default-features" = false }
"document-features" = { "version" = "0.2.7", "optional" = true }
"grid" = { "version" = "1.0.0", "optional" = true, "default-features" = false }
"serde" = { "version" = "1.0", "features" = ["serde_derive"], "optional" = true, "default-features" = false }
"slotmap" = { "version" = "1.0.6", "optional" = true, "default-features" = false }
