"""Emit per-crate rules_rust targets from resolved Cargo graphs."""

import json
from pathlib import Path
from dataclasses import replace


CONDITIONS = {
    'cfg(target_arch = "wasm32")': "wasm",
    'cfg(not(target_arch = "wasm32"))': "native",
    'cfg(all(target_arch = "wasm32", target_os = "unknown"))': "wasm",
    'cfg(not(all(target_arch = "wasm32", target_os = "unknown")))': "native",
    'cfg(target_vendor = "apple")': "apple",
    'cfg(any(target_os = "ios", target_os = "macos"))': "apple",
    'cfg(any(target_os = "macos", target_os = "ios"))': "apple",
    'cfg(any(target_os = "ios", target_os = "macos", target_os = "tvos", target_os = "visionos"))': "apple",
    'cfg(target_os = "android")': "android",
    'cfg(target_os = "macos")': "macos",
    'cfg(target_os = "linux")': "linux",
    'cfg(target_os = "ios")': "ios",
    "cfg(windows)": "windows",
    "cfg(unix)": "unix",
}

# These packages are procedural macros themselves, rather than libraries that
# depend on a derive macro. Cargo-deps helpers expose them separately.
PROC_MACROS = {"luaur-rt-derive", "serde_derive", "thiserror-impl", "bytemuck_derive", "enum_dispatch", "zerocopy-derive"}


def quoted(value):
    return json.dumps(value, sort_keys=True)


def native_select(expressions, conditions_repo=""):
    """Emit one target selection without unifying incompatible platform cuts."""
    if len(set(expressions.values())) == 1:
        return next(iter(expressions.values()))
    entries = [quoted(conditions_repo + "//bazel:" + platform) + ": " + expression
               for platform, expression in sorted(expressions.items())]
    entries.append('"//conditions:default": []')
    return "select({" + ", ".join(entries) + "})"


def feature_expression(graph, package, conditions_repo=""):
    if hasattr(graph, "platforms"):
        return native_select({platform: quoted(sorted(selected.features[package]))
                              for platform, selected in graph.platforms.items()}, conditions_repo)
    return quoted(sorted(graph.features[package]))


def dependency_expression(dependencies, variant, label_for, registry_prefix, package, registry_repo, conditions_repo="", host=False):
    if hasattr(dependencies, "platforms"):
        # Each platform graph already evaluated the original Cargo predicate.
        # Bazel select branches must be concrete lists, so do not nest the
        # original edge select inside the encompassing platform select.
        return native_select({platform: dependency_expression([replace(dep, condition=None) for dep in selected], variant, label_for, registry_prefix,
                                                             package, registry_repo, conditions_repo, host)
                              for platform, selected in dependencies.platforms.items()}, conditions_repo)
    groups = {}
    for dep in dependencies:
        if dep.local == package:
            continue
        if dep.package in PROC_MACROS and dep.local is None:
            continue
        groups.setdefault(dep.condition, []).append(dep)
    pieces = []
    for condition, selected in groups.items():
        local = sorted(set(label_for(dep.local, "host" if host else variant) for dep in selected if dep.local))
        external = sorted(set(dep.alias for dep in selected if dep.local is None))
        parts = []
        if local:
            parts.append(quoted(local))
        if external:
            parts.append(f"crate_deps({quoted(external)}, package_name = {quoted(registry_prefix + '/' + package)})")
        expression = " + ".join(parts) or "[]"
        if condition:
            if condition not in CONDITIONS:
                raise ValueError(f"unmapped Bazel target condition {condition}")
            label = conditions_repo + "//bazel:" + CONDITIONS[condition]
            expression = f"select({{{quoted(label)}: {expression}, \"//conditions:default\": []}})"
        pieces.append(expression)
    return " + ".join(pieces) or "[]"


def render_package(package, graphs, label_for, registry_prefix="bazel/cargo", registry_repo="@runtime_crates", conditions_repo="", fixture_labels=None, unit_tests=True, integration_tests=True, source_owner=None, examples=False):
    """Return one BUILD file for the package and named feature graph variants.

    graphs maps suffixes to FeatureGraph instances; an empty suffix is Cargo's
    default product. label_for(package_name, suffix) supplies repository-aware
    local labels. source_owner can identify an external source-owning package
    (for example @nuxie_runtime//crates/nuxie-runtime), letting a connected graph
    compile those sources against its own registry dependencies.
    """
    fixtures = fixture_labels or []
    lines = [
        "# Generated by tools/bazel/generate.py from Cargo manifests.",
        f'load("{registry_repo}//:defs.bzl", "all_crate_deps", "crate_deps")',
        'load("@rules_rust//cargo:defs.bzl", "cargo_build_script")',
        'load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_lint_config", "rust_shared_library", "rust_static_library", "rust_test")',
        'package(default_visibility = ["//visibility:public"])',
    ]
    source_repo = source_owner.split("//", 1)[0] if source_owner else ""
    if package.name == "nuxie-script-signature":
        lines[2] = 'load(' + quoted(source_repo + '//bazel:script-signature-build.bzl') + ', "cargo_build_script")'
    provenance = package.name in ("nux-capi", "nux-apple-product-extension")
    helpers = ', "provenance_env_file"' if provenance else ''
    lines.insert(-1, 'load(' + quoted(source_repo + '//bazel:source-path.bzl') + ', "source_path"' + helpers + ')')
    lines.append('_source_dir = source_path(' + (quoted(source_owner + ':Cargo.toml') if source_owner else '') + ')')
    if source_owner:
        lines.extend([
            '_sources = ' + quoted([source_owner + ':rust_sources']),
            '_compile_data = ' + quoted([source_owner + ':source_inputs', *fixtures]),
            '_build_sources = ' + quoted([source_owner + ':build_sources']),
            '_build_data = ' + quoted([source_owner + ':source_inputs']),
            '_test_sources = ' + quoted([source_owner + ':test_sources']),
            '_example_sources = ' + quoted([source_owner + ':example_sources']),
        ])
    else:
        lines.extend([
            '_package_inputs = glob(["**"], exclude = ["**/BUILD.bazel", "target/**", "__pycache__/**", "dist/**"], allow_empty = True)',
            'exports_files(_package_inputs)',
            '_sources = glob(["src/**/*.rs"], allow_empty = True)',
            '_compile_data = _package_inputs + ' + quoted(fixtures),
            '_build_sources = glob(["build.rs", "src/**/*.rs"], allow_empty = True)',
            '_build_data = _package_inputs',
            '_test_sources = glob(["tests/**/*.rs"], allow_empty = True)',
            '_example_sources = glob(["examples/**/*.rs"], allow_empty = True)',
            'filegroup(name = "rust_sources", srcs = _sources)',
            'filegroup(name = "build_sources", srcs = _build_sources)',
            'filegroup(name = "source_inputs", srcs = _compile_data + [source for source in _build_data if source not in _compile_data])',
            'filegroup(name = "test_sources", srcs = _test_sources)',
            'filegroup(name = "example_sources", srcs = _example_sources)',
        ])
    lines.append('')
    lints = package.manifest.get("lints", {})
    lint_attributes = []
    for kind in ("rust", "clippy", "rustdoc"):
        levels = {}
        for name, spec in lints.get(kind, {}).items():
            levels[name] = spec if isinstance(spec, str) else spec["level"]
        if levels:
            lint_attributes.append("    " + ("rustc" if kind == "rust" else kind) + " = " + quoted(levels) + ",")
    if lint_attributes:
        lines.extend(['rust_lint_config(', '    name = "cargo_lints",', *lint_attributes, ')', ''])
    def source(path):
        return source_owner + ':' + path if source_owner else path

    lib = package.manifest.get("lib", {})
    crate_root = lib.get("path", "src/lib.rs")
    has_lib = (package.directory / crate_root).is_file()
    build_path = package.manifest["package"].get("build", "build.rs")
    has_build = build_path is not False and (package.directory / build_path).is_file()
    registry_package = registry_prefix + "/" + package.name
    env = {"CARGO_PKG_NAME": package.name}
    compiler_env = 'dict(' + quoted(env) + ', CARGO_MANIFEST_DIR = "$${pwd}/" + _source_dir, BAZEL_CARGO_MANIFEST_DIR = _source_dir)'
    for variant, graph in graphs.items():
        suffix = "__" + variant if variant else ""
        target = package.name + suffix
        features = sorted(graph.features[package.name])
        compiler_features = feature_expression(graph, package.name, conditions_repo)
        normal = graph.dependencies(package.name)
        deps = dependency_expression(normal, variant, label_for, registry_prefix, package.name, registry_repo, conditions_repo)
        if has_build:
            build_deps = graph.dependencies(package.name, ("build-dependencies",))
            build_expr = dependency_expression(build_deps, variant, label_for, registry_prefix, package.name, registry_repo, conditions_repo, host=True)
            lines.extend([
                'cargo_build_script(',
                f'    name = {quoted(target + "__build_script")},',
                f'    pkg_name = {quoted(package.name)},',
                f'    crate_name = {quoted(package.name.replace("-", "_") + "_build_script")},',
                f'    crate_root = {quoted(source(build_path))},',
                '    srcs = _build_sources,',
                '    compile_data = _build_data,',
                '    data = _build_data,',
                f'    edition = {quoted(package.edition)},',
                f'    version = {quoted(package.version)},',
                f'    crate_features = {compiler_features},',
                f'    deps = {build_expr},',
                f'    proc_macro_deps = all_crate_deps(build_proc_macro = True, package_name = {quoted(registry_package)}),',
                *(['    rundir = _source_dir,', '    build_script_env = {"CARGO_MANIFEST_DIR": _source_dir},'] if source_owner else []),
                *(['    build_script_env_files = [provenance_env_file()],'] if provenance else []),
                '    use_default_shell_env = True,' if package.name in ("nux-capi", "nux-apple-product-extension", "nuxie-renderer", "nuxie-renderer-ffi", "nuxie-video-host") else '    use_default_shell_env = False,',
                ')', '',
            ])
            deps += " + " + quoted([":" + target + "__build_script"])
        if has_lib:
            lines.extend([
                'rust_library(', f'    name = {quoted(target)},',
                f'    crate_name = {quoted(lib.get("name", package.name.replace("-", "_")))},',
                f'    crate_root = {quoted(source(crate_root))},',
                '    srcs = _sources,', '    compile_data = _compile_data,',
                f'    edition = {quoted(package.edition)},', f'    version = {quoted(package.version)},',
                f'    crate_features = {compiler_features},', f'    deps = {deps},',
                f'    proc_macro_deps = all_crate_deps(proc_macro = True, package_name = {quoted(registry_package)}),',
                '    rustc_env = ' + compiler_env + ',', ')', '',
            ])
            for output in lib.get("crate-type", []):
                if output not in ("staticlib", "cdylib"):
                    continue
                rule = "rust_static_library" if output == "staticlib" else "rust_shared_library"
                lines.extend([
                    rule + '(', f'    name = {quoted(target + "__" + output)},',
                    f'    crate_name = {quoted(lib.get("name", package.name.replace("-", "_")))},',
                    f'    crate_root = {quoted(source(crate_root))},', '    srcs = _sources,', '    compile_data = _compile_data,',
                    f'    edition = {quoted(package.edition)},', f'    version = {quoted(package.version)},',
                    f'    crate_features = {compiler_features},', f'    deps = {deps},',
                    f'    proc_macro_deps = all_crate_deps(proc_macro = True, package_name = {quoted(registry_package)}),',
                    '    rustc_env = ' + compiler_env + ',', ')', '',
                ])
        binaries = {binary["name"]: binary for binary in package.manifest.get("bin", [])}
        if package.manifest["package"].get("autobins", True):
            if (package.directory / "src/main.rs").is_file():
                binaries.setdefault(package.name, {"name": package.name, "path": "src/main.rs"})
            for path in package.directory.glob("src/bin/*.rs"):
                binaries.setdefault(path.stem, {"name": path.stem, "path": path.relative_to(package.directory).as_posix()})
        binary_products = {}
        for binary_name, binary in sorted(binaries.items()):
            if not set(binary.get("required-features", [])).issubset(features):
                continue
            binary_target = binary_name + suffix
            if has_lib and binary_name == package.name:
                binary_target += "__bin"
            binary_products[binary_name] = ":" + binary_target
            binary_deps = deps
            if has_lib:
                binary_deps += " + " + quoted([":" + target])
            lines.extend([
                'rust_binary(', f'    name = {quoted(binary_target)},',
                f'    crate_name = {quoted(binary_name.replace("-", "_"))},',
                f'    crate_root = {quoted(source(binary.get("path", "src/main.rs")))},',
                '    srcs = _sources,', '    compile_data = _compile_data,',
                f'    edition = {quoted(package.edition)},', f'    version = {quoted(package.version)},',
                f'    crate_features = {compiler_features},', f'    deps = {binary_deps},',
                f'    proc_macro_deps = all_crate_deps(proc_macro = True, package_name = {quoted(registry_package)}),',
                '    rustc_env = ' + compiler_env + ',', ')', '',
            ])
        if examples:
            example_specs = {example["name"]: example for example in package.manifest.get("example", [])}
            if package.manifest["package"].get("autoexamples", True):
                for path in package.directory.glob("examples/*.rs"):
                    example_specs.setdefault(path.stem, {"name": path.stem, "path": path.relative_to(package.directory).as_posix()})
            for example_name, example in sorted(example_specs.items()):
                if not set(example.get("required-features", [])).issubset(features):
                    continue
                example_path = example.get("path", "examples/" + example_name + ".rs")
                example_deps = dependency_expression(graph.dependencies(package.name, ("dependencies", "dev-dependencies")), variant, label_for, registry_prefix, package.name, registry_repo, conditions_repo)
                if has_build:
                    example_deps += " + " + quoted([":" + target + "__build_script"])
                if has_lib:
                    example_deps += " + " + quoted([":" + target])
                rule = "rust_shared_library" if "cdylib" in example.get("crate-type", []) else "rust_binary"
                lines.extend([
                    rule + '(', f'    name = {quoted(example_name + suffix)},',
                    f'    crate_name = {quoted(example_name.replace("-", "_"))},',
                    f'    crate_root = {quoted(source(example_path))},',
                    '    srcs = _example_sources,', '    compile_data = _compile_data,',
                    f'    edition = {quoted(package.edition)},', f'    version = {quoted(package.version)},',
                    f'    crate_features = {compiler_features},', f'    deps = {example_deps},',
                    f'    proc_macro_deps = all_crate_deps(proc_macro = True, proc_macro_dev = True, package_name = {quoted(registry_package)}),',
                    '    rustc_env = ' + compiler_env + ',', ')', '',
                ])
        if variant != "test":
            continue
        test_deps = dependency_expression(graph.dependencies(package.name, ("dev-dependencies",)), variant, label_for, registry_prefix, package.name, registry_repo, conditions_repo)
        if unit_tests and has_lib:
            lines.extend([
                'rust_test(', f'    name = {quoted(package.name + "__unit_test")},', f'    crate = {quoted(":" + target)},',
                f'    crate_features = {compiler_features},',
                f'    deps = {test_deps},', '    data = _compile_data,',
                f'    proc_macro_deps = all_crate_deps(proc_macro_dev = True, package_name = {quoted(registry_package)}),', ')', '',
            ])
        elif unit_tests and package.name in binaries:
            lines.extend([
                'rust_test(', f'    name = {quoted(package.name + "__unit_test")},', f'    crate = {quoted(":" + target)},',
                f'    crate_features = {compiler_features},',
                f'    deps = {test_deps},', '    data = _compile_data,',
                f'    proc_macro_deps = all_crate_deps(proc_macro_dev = True, package_name = {quoted(registry_package)}),', ')', '',
            ])
        if integration_tests:
            integration_deps = dependency_expression(graph.dependencies(package.name, ("dependencies", "dev-dependencies")), variant, label_for, registry_prefix, package.name, registry_repo, conditions_repo)
            if has_build:
                integration_deps += " + " + quoted([":" + target + "__build_script"])
            if has_lib:
                integration_deps = quoted([":" + target]) + " + " + integration_deps
            binary_env = {"CARGO_BIN_EXE_" + name: "$(rootpath " + label + ")"
                          for name, label in binary_products.items()}
            integration_env = "dict(" + compiler_env + ".items() + " + quoted(list(binary_env.items())) + ")"
            explicit = {test["name"]: test for test in package.manifest.get("test", [])}
            files = {file.stem: file for file in package.directory.glob("tests/*.rs")}
            for test_name, test in explicit.items():
                files[test_name] = package.directory / test.get("path", f"tests/{test_name}.rs")
            for test_name, file in sorted(files.items()):
                required = explicit.get(test_name, {}).get("required-features", [])
                if not set(required).issubset(features):
                    continue
                lines.extend([
                    'rust_test(', f'    name = {quoted(package.name + "__test_" + test_name)},',
                    f'    crate_name = {quoted(test_name.replace("-", "_"))},',
                    f'    crate_root = {quoted(source(file.relative_to(package.directory).as_posix()))},',
                    '    srcs = _test_sources,', '    compile_data = _compile_data,',
                    '    data = _compile_data + ' + quoted(list(binary_products.values())) + ',',
                    f'    edition = {quoted(package.edition)},', f'    version = {quoted(package.version)},',
                    f'    crate_features = {compiler_features},',
                    f'    deps = {integration_deps},',
                    f'    proc_macro_deps = all_crate_deps(proc_macro = True, proc_macro_dev = True, package_name = {quoted(registry_package)}),',
                    '    rustc_env = ' + integration_env + ',', ')', '',
                ])
    if lint_attributes:
        # Build scripts have Cargo's separate compilation context. The authored
        # crate and its executable/test roots share its own lint policy.
        rendered = []
        current_rule = None
        for line in lines:
            if line in ('rust_library(', 'rust_binary(', 'rust_shared_library(', 'rust_static_library(', 'rust_test('):
                current_rule = line
            elif line.endswith('('):
                current_rule = None
            if line == ')' and current_rule:
                rendered.append('    lint_config = ":cargo_lints",')
                current_rule = None
            rendered.append(line)
        lines = rendered
    return "\n".join(lines).rstrip("\n") + "\n"
