[package]
name = "nuxie-ore-metal"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[features]
default = []
with-rive-tools = []
tools = ["with-rive-tools"]
track-rive-shader-id = []
rive-objc-exceptions = ["objc2/exception"]

[dev-dependencies]
sha2 = "0.10"

[target.'cfg(target_vendor = "apple")'.dependencies]
block2 = "0.6.2"
objc2 = "0.6.4"
objc2-foundation = { version = "0.3.2", default-features = false, features = ["NSString"] }
objc2-metal = { version = "0.3.2", default-features = false, features = ["block2", "MTLAllocation", "MTLArgument", "MTLBuffer", "MTLCommandBuffer", "MTLCommandEncoder", "MTLCommandQueue", "MTLDepthStencil", "MTLDevice", "MTLLibrary", "MTLPixelFormat", "MTLRenderCommandEncoder", "MTLRenderPass", "MTLRenderPipeline", "MTLResource", "MTLSampler", "MTLTexture", "MTLTypes", "MTLVertexDescriptor"] }
