export const LANGUAGE_VERSION: 'nuxie-html-v1';
export interface Diagnostic { code: string; source: string; message: string }
export type Asset =
  | {kind:'font'; family:string; weight:number; bytes:Uint8Array | number[]}
  | {kind:'image'; bytes:Uint8Array | number[]};
export interface DesignDocument {
  languageVersion: typeof LANGUAGE_VERSION;
  html: string;
  css: string;
  width: number;
  height: number;
  assets?: Record<string,Asset>;
}
export interface SourceBreak { id:string; path:string; text_offset:number }
export interface SourceTextTransform { source:string; rendered:string; scalar_offsets:number[] }
export interface SourceNode {
  id: string;
  path: string;
  /** Artboard-local index for this compilation only. */
  object_id: number;
  text_run_id: number | null;
  text_run_ids: number[];
  text_breaks: SourceBreak[];
  text_transform?: SourceTextTransform;
}
export type CornerRadiusValue = {pixels:number;percent?:never} | {percent:number;pixels?:never};
export type LayoutCornerRadiiRequirement = {object_id:number;radii:[[CornerRadiusValue,CornerRadiusValue],[CornerRadiusValue,CornerRadiusValue],[CornerRadiusValue,CornerRadiusValue],[CornerRadiusValue,CornerRadiusValue]]};
export type LayoutGroupOpacityRequirement = {object_id:number;opacity:number};
export type LinearGradientDirection = {degrees:number;corner?:never} | {corner:{right:boolean;bottom:boolean};degrees?:never};
export type LinearGradientPosition = {pixels:number;percent?:never} | {percent:number;pixels?:never};
export interface LinearGradientStop {color:number;position:LinearGradientPosition | null}
export interface LayoutLinearGradientRequirement {object_id:number;direction:LinearGradientDirection;stops:LinearGradientStop[]}
export type RuntimeCapability = "layout-css-linear-gradient-v1" | "layout-css-group-opacity-v1" | "layout-css-corner-radii-v1" | "layout-css-border-sides-v1" | "layout-css-solid-borders-v1" | "layout-css-overflow-clip-margin-v1" | "layout-css-axis-overflow-v1" | "layout-css-stacking-v1" | "layout-css-absolute-position-v1" | "layout-css-positioned-paint-v1" | "layout-css-percentage-spacing-v1" | "layout-css-aspect-ratio-pair-v1" | "layout-css-aspect-ratio-v1" | "layout-css-content-box-v1" | "layout-css-indefinite-basis-v1" | "layout-css-intrinsic-sizing-v1" | "layout-css-partial-flex-factors-v1" | "layout-css-flex-factors-v1" | "layout-css-distributed-spacing-v1" | "layout-css-align-content-v1" | "layout-css-align-self-v1" | "layout-css-paint-order-v1" | "layout-css-pixel-bounds-v1" | "text-css-single-line-ellipsis-v1" | "text-solid-strikethroughs-v1" | "text-css-shaping-precision-v1" | "text-solid-underlines-v1" | "text-css-wrapped-tabs-v1" | "text-css-pre-wrap-v1" | "text-css-pre-line-v1" | "text-css-normal-wrap-v1" | "text-css-tabs-v1" | "text-css-nowrap-alignment-v1" | "text-cluster-spacing-v1" | "text-css-letter-spacing-v1" | "text-preserved-space-breaks-v1";
export interface TextPolicyRequirement { object_id:number; policy:"css-single-line-ellipsis-v1" | "css-nowrap-alignment-v1" | "css-pre-wrap-v1" | "css-pre-line-v1" | "css-normal-wrap-v1" }
export interface SolidUnderline { color:number; thickness:number; offset:number; skip_ink:"none" | "auto" | "all" }
export interface TextUnderlineRequirement { object_id:number; lines:SolidUnderline[] }
export interface SolidStrikethrough { color:number; thickness:number; offset:number; line_baseline:number }
export interface TextStrikethroughRequirement { object_id:number; lines:SolidStrikethrough[] }
export type AlignSelf = "auto" | "flex-start" | "center" | "flex-end" | "stretch" | "baseline";
export interface LayoutAlignSelfRequirement { object_id:number; alignment:AlignSelf }
export type AlignContent = "flex-start" | "center" | "flex-end" | "stretch" | "space-between" | "space-around" | "space-evenly";
export interface LayoutAlignContentRequirement { object_id:number; alignment:AlignContent }
export type JustifyDistribution = "space-around" | "space-evenly";
export interface LayoutFlexFactorsRequirement { object_id:number; grow:number; shrink:number }
export interface LayoutJustifyContentRequirement { object_id:number; alignment:JustifyDistribution }
export type RuntimeRequirements =
  | { version:1; capabilities:RuntimeCapability[]; layout_flex_factors?:never; layout_justify_content?:never; layout_align_content?:never; layout_align_self?:never; layout_pixel_bounds?:never; text_policies?:never; text_underlines?:never; text_strikethroughs?:never }
  | { version:2; capabilities:RuntimeCapability[]; layout_flex_factors?:never; layout_justify_content?:never; layout_align_content?:never; layout_align_self?:never; layout_pixel_bounds?:never; text_policies:TextPolicyRequirement[]; text_underlines?:never; text_strikethroughs?:never }
  | { version:3; capabilities:RuntimeCapability[]; layout_flex_factors?:never; layout_justify_content?:never; layout_align_content?:never; layout_align_self?:never; layout_pixel_bounds?:never; text_policies?:TextPolicyRequirement[]; text_underlines:TextUnderlineRequirement[]; text_strikethroughs?:never }
  | { version:4; capabilities:RuntimeCapability[]; layout_flex_factors?:never; layout_justify_content?:never; layout_align_content?:never; layout_align_self?:never; layout_pixel_bounds?:never; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs:TextStrikethroughRequirement[] }
  | { version:5; capabilities:RuntimeCapability[]; layout_flex_factors?:never; layout_justify_content?:never; layout_align_content?:never; layout_align_self?:never; layout_pixel_bounds:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:6; capabilities:RuntimeCapability[]; layout_flex_factors?:never; layout_justify_content?:never; layout_align_content?:never; layout_align_self:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:7; capabilities:RuntimeCapability[]; layout_flex_factors?:never; layout_justify_content?:never; layout_align_content:Array<{object_id:number;alignment:Exclude<AlignContent,"space-evenly">}>; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:8; capabilities:RuntimeCapability[]; layout_flex_factors?:never; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:9; capabilities:RuntimeCapability[]; layout_flex_factors:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:10; capabilities:RuntimeCapability[]; layout_flex_factors:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:11; layout_intrinsic_sizing:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:12; layout_intrinsic_sizing?:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:13; layout_content_box:number[]; layout_intrinsic_sizing?:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:14; layout_aspect_ratios:{object_id:number;content_box:boolean}[]; layout_content_box?:number[]; layout_intrinsic_sizing?:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:15; layout_aspect_ratios:{object_id:number;content_box:boolean;pair:[number,number]}[]; layout_content_box?:number[]; layout_intrinsic_sizing?:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:16; layout_percentage_spacing:number[]; layout_aspect_ratios?:{object_id:number;content_box:boolean;pair?:[number,number]}[]; layout_content_box?:number[]; layout_intrinsic_sizing?:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:17; layout_positioned:number[]; layout_percentage_spacing?:number[]; layout_aspect_ratios?:{object_id:number;content_box:boolean;pair?:[number,number]}[]; layout_content_box?:number[]; layout_intrinsic_sizing?:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:18; layout_absolute:number[]; layout_positioned:number[]; layout_percentage_spacing?:number[]; layout_aspect_ratios?:{object_id:number;content_box:boolean;pair?:[number,number]}[]; layout_content_box?:number[]; layout_intrinsic_sizing?:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:19; layout_stacking:{object_id:number;level:number}[]; layout_absolute?:number[]; layout_positioned?:number[]; layout_percentage_spacing?:number[]; layout_aspect_ratios?:{object_id:number;content_box:boolean;pair?:[number,number]}[]; layout_content_box?:number[]; layout_intrinsic_sizing?:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:20; layout_axis_overflow:{object_id:number;axis:"x"|"y"}[]; layout_stacking?:{object_id:number;level:number}[]; layout_absolute?:number[]; layout_positioned?:number[]; layout_percentage_spacing?:number[]; layout_aspect_ratios?:{object_id:number;content_box:boolean;pair?:[number,number]}[]; layout_content_box?:number[]; layout_intrinsic_sizing?:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:21; layout_overflow_clip_margins:{object_id:number;origin:"content-box"|"padding-box"|"border-box";pixels:number}[]; layout_axis_overflow?:{object_id:number;axis:"x"|"y"}[]; layout_stacking?:{object_id:number;level:number}[]; layout_absolute?:number[]; layout_positioned?:number[]; layout_percentage_spacing?:number[]; layout_aspect_ratios?:{object_id:number;content_box:boolean;pair?:[number,number]}[]; layout_content_box?:number[]; layout_intrinsic_sizing?:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:22; layout_borders:{object_id:number;color:number}[]; layout_overflow_clip_margins?:{object_id:number;origin:"content-box"|"padding-box"|"border-box";pixels:number}[]; layout_axis_overflow?:{object_id:number;axis:"x"|"y"}[]; layout_stacking?:{object_id:number;level:number}[]; layout_absolute?:number[]; layout_positioned?:number[]; layout_percentage_spacing?:number[]; layout_aspect_ratios?:{object_id:number;content_box:boolean;pair?:[number,number]}[]; layout_content_box?:number[]; layout_intrinsic_sizing?:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:23; layout_border_sides:{object_id:number;colors:[number,number,number,number]}[]; layout_borders?:{object_id:number;color:number}[]; layout_overflow_clip_margins?:{object_id:number;origin:"content-box"|"padding-box"|"border-box";pixels:number}[]; layout_axis_overflow?:{object_id:number;axis:"x"|"y"}[]; layout_stacking?:{object_id:number;level:number}[]; layout_absolute?:number[]; layout_positioned?:number[]; layout_percentage_spacing?:number[]; layout_aspect_ratios?:{object_id:number;content_box:boolean;pair?:[number,number]}[]; layout_content_box?:number[]; layout_intrinsic_sizing?:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:24; layout_corner_radii:LayoutCornerRadiiRequirement[]; layout_border_sides?:{object_id:number;colors:[number,number,number,number]}[]; layout_borders?:{object_id:number;color:number}[]; layout_overflow_clip_margins?:{object_id:number;origin:"content-box"|"padding-box"|"border-box";pixels:number}[]; layout_axis_overflow?:{object_id:number;axis:"x"|"y"}[]; layout_stacking?:{object_id:number;level:number}[]; layout_absolute?:number[]; layout_positioned?:number[]; layout_percentage_spacing?:number[]; layout_aspect_ratios?:{object_id:number;content_box:boolean;pair?:[number,number]}[]; layout_content_box?:number[]; layout_intrinsic_sizing?:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:25; layout_group_opacity:LayoutGroupOpacityRequirement[]; layout_corner_radii?:LayoutCornerRadiiRequirement[]; layout_border_sides?:{object_id:number;colors:[number,number,number,number]}[]; layout_borders?:{object_id:number;color:number}[]; layout_overflow_clip_margins?:{object_id:number;origin:"content-box"|"padding-box"|"border-box";pixels:number}[]; layout_axis_overflow?:{object_id:number;axis:"x"|"y"}[]; layout_stacking?:{object_id:number;level:number}[]; layout_absolute?:number[]; layout_positioned?:number[]; layout_percentage_spacing?:number[]; layout_aspect_ratios?:{object_id:number;content_box:boolean;pair?:[number,number]}[]; layout_content_box?:number[]; layout_intrinsic_sizing?:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] }
  | { version:26; layout_linear_gradients:LayoutLinearGradientRequirement[]; layout_group_opacity?:LayoutGroupOpacityRequirement[]; layout_corner_radii?:LayoutCornerRadiiRequirement[]; layout_border_sides?:{object_id:number;colors:[number,number,number,number]}[]; layout_borders?:{object_id:number;color:number}[]; layout_overflow_clip_margins?:{object_id:number;origin:"content-box"|"padding-box"|"border-box";pixels:number}[]; layout_axis_overflow?:{object_id:number;axis:"x"|"y"}[]; layout_stacking?:{object_id:number;level:number}[]; layout_absolute?:number[]; layout_positioned?:number[]; layout_percentage_spacing?:number[]; layout_aspect_ratios?:{object_id:number;content_box:boolean;pair?:[number,number]}[]; layout_content_box?:number[]; layout_intrinsic_sizing?:number[]; capabilities:RuntimeCapability[]; layout_flex_factors?:LayoutFlexFactorsRequirement[]; layout_justify_content?:LayoutJustifyContentRequirement[]; layout_align_content?:LayoutAlignContentRequirement[]; layout_align_self?:LayoutAlignSelfRequirement[]; layout_pixel_bounds?:number[]; text_policies?:TextPolicyRequirement[]; text_underlines?:TextUnderlineRequirement[]; text_strikethroughs?:TextStrikethroughRequirement[] };
export type CompileResult =
  | {ok:true; languageVersion:typeof LANGUAGE_VERSION; riv:Uint8Array; sourceMap:SourceNode[]; runtimeRequirements:RuntimeRequirements}
  | {ok:false; diagnostics:Diagnostic[]};
export interface Compiler {
  readonly languageVersion: typeof LANGUAGE_VERSION;
  compile(document:DesignDocument):CompileResult;
}
export function createCompiler(bytesOrModule:BufferSource | WebAssembly.Module):Promise<Compiler>;
