#!/usr/bin/env python3
"""Generate rawtext draw 1's exact compound path from its recorded stream."""

import argparse
import pathlib
import re


STREAM_LINE_INDEX = 8
EXPECTED_VERB_COUNT = 506
EXPECTED_POINT_COUNT = 1096
EXPECTED_CONTOUR_COUNT = 36
PATH_PREFIX = "drawPath path={id=1,fillRule=2,path={verbs=["
POINTS_MARKER = "],points=["
PAINT_MARKER = (
    "]}} paint={id=1,style=fill,color=0xff000000,thickness=1,join=0,"
    "cap=0,feather=0,blendMode=3,shader=0}"
)
POINT_RE = re.compile(r"\(([-+0-9.eE]+),([-+0-9.eE]+)\)")


def parse_stream_path(stream: pathlib.Path) -> list[tuple[str, tuple[str, ...]]]:
    lines = stream.read_text().splitlines()
    if len(lines) <= STREAM_LINE_INDEX:
        raise ValueError("rawtext stream does not contain line 9")
    line = lines[STREAM_LINE_INDEX]
    if not line.startswith(PATH_PREFIX) or not line.endswith(PAINT_MARKER):
        raise ValueError("stream line 9 is not rawtext draw 1")

    verbs_end = line.index(POINTS_MARKER, len(PATH_PREFIX))
    verbs = line[len(PATH_PREFIX):verbs_end].split(",")
    points_start = verbs_end + len(POINTS_MARKER)
    points_end = line.index("]}} paint=", points_start)
    points_text = line[points_start:points_end]
    points = POINT_RE.findall(points_text)
    if ",".join(f"({x},{y})" for x, y in points) != points_text:
        raise ValueError("rawtext draw 1 contains a noncanonical point literal")
    if len(verbs) != EXPECTED_VERB_COUNT or len(points) != EXPECTED_POINT_COUNT:
        raise ValueError("rawtext draw 1 verb or point count drifted")
    if verbs.count("move") != EXPECTED_CONTOUR_COUNT:
        raise ValueError("rawtext draw 1 contour count drifted")
    if points[0] != ("5.9765625", "66.796875"):
        raise ValueError("rawtext draw 1 first point drifted")
    if points[-1] != ("106.167747", "224.504501"):
        raise ValueError("rawtext draw 1 last point drifted")

    arity = {"move": 1, "line": 1, "cubic": 3, "close": 0}
    records = []
    point_index = 0
    for verb in verbs:
        if verb not in arity:
            raise ValueError(f"rawtext draw 1 has unsupported verb {verb!r}")
        count = arity[verb]
        end = point_index + count
        if end > len(points):
            raise ValueError("rawtext draw 1 verb stream overruns its points")
        records.append((verb, tuple(value for point in points[point_index:end] for value in point)))
        point_index = end
    if point_index != len(points):
        raise ValueError("rawtext draw 1 has unconsumed points")
    return records


def float_literal(value: str) -> str:
    return f"{value}f" if any(char in value for char in ".eE") else f"{value}.f"


def generate_include(records: list[tuple[str, tuple[str, ...]]]) -> str:
    lines = [
        "// Generated by generate_rawtext_stream_path.py; do not edit.",
        "// Source: fixtures/renderer/streams/gm/rawtext.rive-stream line 9.",
        "void addRawTextDrawOne(rive::RenderPath* path)",
        "{",
    ]
    methods = {"move": "moveTo", "line": "lineTo", "cubic": "cubicTo"}
    for verb, values in records:
        if verb == "close":
            lines.append("    path->close();")
        else:
            arguments = ", ".join(float_literal(value) for value in values)
            lines.append(f"    path->{methods[verb]}({arguments});")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stream", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if bool(args.output) == args.check:
        parser.error("specify exactly one of --output or --check")
    records = parse_stream_path(args.stream)
    if args.output:
        args.output.write_text(generate_include(records))


if __name__ == "__main__":
    main()
