#!/usr/bin/env python3
"""Generate the exact feather_polyshapes shark path from stream line 28."""

import argparse
import pathlib
import re


STREAM_LINE_INDEX = 27
TRANSFORM_LINE_INDEX = 13
EXPECTED_POINT_COUNT = 315
PATH_PREFIX = "drawPath path={id=4,fillRule=2,path={verbs=["
POINTS_MARKER = "],points=["
PAINT_MARKER = "]}} paint={id=1,style=fill,color=0xffffffff,thickness=1,join=0,cap=0,feather=1,blendMode=3,shader=0}"
POINT_RE = re.compile(r"\(([-+0-9.eE]+),([-+0-9.eE]+)\)")
TRANSFORM_RE = re.compile(
    r"transform matrix=\[([-+0-9.eE]+),0,0,([-+0-9.eE]+),0,0\]"
)


def parse_stream_scale(lines: list[str]) -> str:
    if len(lines) <= TRANSFORM_LINE_INDEX:
        raise ValueError("feather_polyshapes stream does not contain line 14")
    match = TRANSFORM_RE.fullmatch(lines[TRANSFORM_LINE_INDEX])
    if match is None or match.group(1) != match.group(2):
        raise ValueError("stream line 14 is not a uniform origin-preserving transform")
    return match.group(1)


def parse_stream_path(stream: pathlib.Path) -> tuple[str, list[tuple[str, str, str]]]:
    lines = stream.read_text().splitlines()
    scale = parse_stream_scale(lines)
    if len(lines) <= STREAM_LINE_INDEX:
        raise ValueError("feather_polyshapes stream does not contain line 28")
    line = lines[STREAM_LINE_INDEX]
    if not line.startswith(PATH_PREFIX) or not line.endswith(PAINT_MARKER):
        raise ValueError("stream line 28 is not the row-0 feather=1 shark draw")

    verbs_end = line.index(POINTS_MARKER, len(PATH_PREFIX))
    verbs = line[len(PATH_PREFIX):verbs_end].split(",")
    points_start = verbs_end + len(POINTS_MARKER)
    points_end = line.index("]}} paint=", points_start)
    points_text = line[points_start:points_end]
    points = POINT_RE.findall(points_text)
    if ",".join(f"({x},{y})" for x, y in points) != points_text:
        raise ValueError("stream line 28 contains a noncanonical point literal")
    if len(verbs) != EXPECTED_POINT_COUNT or len(points) != EXPECTED_POINT_COUNT:
        raise ValueError("stream line 28 shark point count drifted")
    if verbs[0] != "move" or any(verb != "line" for verb in verbs[1:]):
        raise ValueError("stream line 28 shark must contain one move followed by lines")
    if points[0] != ("1.35999978", "118.419998") or points[-1] != points[0]:
        raise ValueError("stream line 28 shark endpoints drifted")
    return scale, list(zip(verbs, *(zip(*points))))


def float_literal(value: str) -> str:
    return f"{value}f" if any(char in value for char in ".eE") else f"{value}.f"


def generate_include(scale: str, records: list[tuple[str, str, str]]) -> str:
    lines = [
        "// Generated by generate_polyshark_stream_path.py; do not edit.",
        "// Source: fixtures/renderer/streams/gm/feather_polyshapes.rive-stream lines 14 and 28.",
        f"constexpr float kPolySharkStreamScale = {float_literal(scale)};",
        "void addFeatherPolyShapesShark(rive::RenderPath* path)",
        "{",
    ]
    for verb, x, y in records:
        method = "moveTo" if verb == "move" else "lineTo"
        lines.append(f"    path->{method}({float_literal(x)}, {float_literal(y)});")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stream", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if bool(args.output) == args.check:
        parser.error("specify exactly one of --output or --check")
    scale, records = parse_stream_path(args.stream)
    if args.output:
        args.output.write_text(generate_include(scale, records))


if __name__ == "__main__":
    main()
