#ifndef NUX_RUNTIME_GENERATED_H
#define NUX_RUNTIME_GENERATED_H

/* Generated by cbindgen. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define NUX_RUNTIME_ABI_MAJOR 1

#define NUX_RUNTIME_ABI_MINOR 1

/**
 * Opaque C handle. It retains the logical render session across detach.
 */
typedef struct NuxAppleSurface NuxAppleSurface;

/**
 * Opaque C handle. It retains its runtime context.
 */
typedef struct NuxFlowRenderSession NuxFlowRenderSession;

/**
 * Opaque C handle. Its storage is private and retained by child handles.
 */
typedef struct NuxFlowRuntimeContext NuxFlowRuntimeContext;

typedef struct NuxOperationResult NuxOperationResult;

/**
 * Stable-width C status code. Named constants are exported separately so
 * Swift imports one unambiguous `UInt32`-backed type instead of a C enum tag
 * that competes with its typedef.
 */
typedef uint32_t NuxStatus;

typedef struct NuxAppleSurfaceDescriptor {
  uint32_t struct_size;
  uint32_t pixel_width;
  uint32_t pixel_height;
} NuxAppleSurfaceDescriptor;

typedef struct NuxFrameOperation {
  uint32_t struct_size;
  float elapsed_seconds;
  bool render;
  /**
   * A live `id<CAMetalDrawable>` acquired by Swift on the main actor.
   * The runtime borrows it only for the synchronous advance call.
   */
  void *apple_drawable;
  /**
   * Caller-owned context consumed by `completion_callback`. Both completion
   * fields must be null or non-null together.
   */
  void *completion_context;
  /**
   * Optional one-shot GPU completion callback. The callback may run on an
   * arbitrary Metal or runtime thread and must not call UIKit.
   */
  void (*completion_callback)(void *context);
} NuxFrameOperation;

typedef struct NuxByteView {
  const uint8_t *data;
  uint64_t len;
} NuxByteView;

typedef struct NuxFlowSessionDescriptor {
  uint32_t struct_size;
  /**
   * UTF-8 authored artboard name. A null view selects the default artboard.
   */
  struct NuxByteView artboard_name;
  /**
   * UTF-8 authored state-machine name. A null view selects the authored
   * default, falling back to state-machine zero. Slice 1 advances the base
   * artboard update when no state machine exists; linear-animation fallback
   * is added with the product-complete player selection operation.
   */
  struct NuxByteView state_machine_name;
} NuxFlowSessionDescriptor;

typedef struct NuxFlowAuthorizationKey {
  uint32_t struct_size;
  struct NuxByteView key_id;
  /**
   * Exactly 32 raw Ed25519 public-key bytes.
   */
  struct NuxByteView ed25519_public_key;
} NuxFlowAuthorizationKey;

/**
 * Stable-width external artifact asset kind.
 */
typedef uint32_t NuxFlowExternalAssetKind;

/**
 * One element of `NuxFlowImportRequest.external_assets`. Because the array has
 * no independent stride, every element must use this exact published size.
 */
typedef struct NuxFlowExternalAsset {
  uint32_t struct_size;
  NuxFlowExternalAssetKind kind;
  /**
   * Serialized `FileAsset.assetId`, not an asset-list ordinal.
   */
  uint32_t asset_id;
  bool required;
  /**
   * Distinguishes explicitly omitted optional content from supplied empty bytes.
   */
  bool provided;
  struct NuxByteView unique_name;
  struct NuxByteView source_key;
  struct NuxByteView expected_sha256;
  struct NuxByteView bytes;
} NuxFlowExternalAsset;

typedef struct NuxFlowImportRequest {
  uint32_t struct_size;
  /**
   * Exact verified visual-runtime bytes. The field is container-neutral so
   * the current RIV adapter can later be replaced without changing sessions.
   */
  struct NuxByteView artifact_bytes;
  /**
   * UTF-8 acquisition identity used to prevent cross-flow replay.
   */
  struct NuxByteView expected_flow_id;
  /**
   * UTF-8 acquisition identity used to prevent cross-build replay.
   */
  struct NuxByteView expected_build_id;
  /**
   * Exact signed artifact manifest bytes.
   */
  struct NuxByteView manifest_bytes;
  /**
   * Optional exact detached signature-envelope bytes. Only `{NULL, 0}` is
   * absent; a non-null empty view is present malformed evidence.
   */
  struct NuxByteView signature_envelope_bytes;
  /**
   * Optional Nuxie-selected validation material. This is evidence, never a
   * caller-supplied authorization decision.
   */
  const struct NuxFlowAuthorizationKey *selected_key;
  /**
   * Ordered manifest asset inputs, already resolved to bytes or an explicit omission.
   */
  const struct NuxFlowExternalAsset *external_assets;
  uint64_t external_asset_count;
} NuxFlowImportRequest;

/**
 * Stable-width structured diagnostic severity.
 */
typedef uint32_t NuxDiagnosticSeverity;

/**
 * Frozen ABI-major-1 diagnostic output layout. Callers initialize
 * `struct_size` to the exact published size before invoking an accessor.
 */
typedef struct NuxDiagnosticView {
  uint32_t struct_size;
  NuxDiagnosticSeverity severity;
  struct NuxByteView code;
  struct NuxByteView message;
} NuxDiagnosticView;

/**
 * Stable-width script authorization result set during artifact import.
 */
typedef uint32_t NuxScriptAuthorization;

/**
 * Stable-width C presentation outcome.
 */
typedef uint32_t NuxSurfaceDisposition;

#define NUX_DIAGNOSTIC_SEVERITY_DEBUG 0

#define NUX_DIAGNOSTIC_SEVERITY_FATAL 2

#define NUX_DIAGNOSTIC_SEVERITY_WARNING 1

#define NUX_FLOW_EXTERNAL_ASSET_KIND_FONT 2

#define NUX_FLOW_EXTERNAL_ASSET_KIND_IMAGE 1

#define NUX_SCRIPT_AUTHORIZATION_AUTHENTICATED 2

#define NUX_SCRIPT_AUTHORIZATION_NOT_APPLICABLE 0

#define NUX_SCRIPT_AUTHORIZATION_VISUAL_ONLY 1

#define NUX_STATUS_ABI_MISMATCH (NuxStatus)6

#define NUX_STATUS_IMPORT_ERROR (NuxStatus)2

#define NUX_STATUS_INVALID_ARGUMENT (NuxStatus)5

#define NUX_STATUS_NOT_FOUND (NuxStatus)3

#define NUX_STATUS_NULL_ARGUMENT (NuxStatus)1

#define NUX_STATUS_OK (NuxStatus)0

#define NUX_STATUS_RUNTIME_ERROR (NuxStatus)4

#define NUX_STATUS_SURFACE_ERROR (NuxStatus)7

#define NUX_SURFACE_DISPOSITION_DEVICE_LOST (NuxSurfaceDisposition)7

#define NUX_SURFACE_DISPOSITION_FATAL (NuxSurfaceDisposition)9

#define NUX_SURFACE_DISPOSITION_NONE (NuxSurfaceDisposition)0

#define NUX_SURFACE_DISPOSITION_OUT_OF_MEMORY (NuxSurfaceDisposition)8

#define NUX_SURFACE_DISPOSITION_PRESENTED (NuxSurfaceDisposition)1

#define NUX_SURFACE_DISPOSITION_RECONFIGURED (NuxSurfaceDisposition)5

#define NUX_SURFACE_DISPOSITION_RECREATED (NuxSurfaceDisposition)6

#define NUX_SURFACE_DISPOSITION_SKIPPED_OCCLUDED (NuxSurfaceDisposition)4

#define NUX_SURFACE_DISPOSITION_SKIPPED_TIMEOUT (NuxSurfaceDisposition)3

#define NUX_SURFACE_DISPOSITION_SKIPPED_ZERO_SIZE (NuxSurfaceDisposition)2

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Copies the renderer's Metal device for main-actor `CAMetalLayer` setup.
 *
 * On success `out_metal_device` receives an Objective-C object pointer with
 * +1 ownership. The caller must transfer that ownership to ARC or release it.
 *
 * # Safety
 *
 * `surface` must be live and output pointers must be null or writable. Calls
 * may originate on arbitrary threads; this library serializes runtime state.
 */
NuxStatus nux_apple_surface_copy_metal_device(const struct NuxAppleSurface *surface,
                                              void **out_metal_device,
                                              struct NuxOperationResult **out_result);

/**
 * Detaches presentation state while preserving logical session state.
 *
 * # Safety
 *
 * `surface` must be live and `out_result` must be null or writable. Calls may
 * originate on arbitrary threads; this library serializes runtime state.
 */
NuxStatus nux_apple_surface_detach(const struct NuxAppleSurface *surface,
                                   struct NuxOperationResult **out_result);

/**
 * Releases one Apple-surface handle. Null is a no-op.
 *
 * # Safety
 *
 * A non-null pointer must be an owned handle returned by this library and not
 * previously released. Release must not race a call using the same handle.
 */
void nux_apple_surface_free(struct NuxAppleSurface *surface);

/**
 * Reattaches logical presentation state after a detach.
 *
 * # Safety
 *
 * Handles, descriptor, and output storage must be valid. Calls may originate
 * on arbitrary threads; this library serializes runtime state.
 */
NuxStatus nux_apple_surface_reattach(const struct NuxAppleSurface *surface,
                                     const struct NuxAppleSurfaceDescriptor *descriptor,
                                     struct NuxOperationResult **out_result);

/**
 * Resizes or zero-size-suspends one attached Apple surface.
 *
 * # Safety
 *
 * `surface` must be live and `out_result` must be null or writable. Calls may
 * originate on arbitrary threads; this library serializes runtime state.
 */
NuxStatus nux_apple_surface_resize(const struct NuxAppleSurface *surface,
                                   uint32_t pixel_width,
                                   uint32_t pixel_height,
                                   struct NuxOperationResult **out_result);

/**
 * Advances a logical session and optionally renders its attached surface.
 *
 * # Safety
 *
 * `session` and `operation` must be live, valid pointers; `out_result` must
 * be null or writable. When rendering, `operation.apple_drawable` may be null
 * to report a bounded no-drawable outcome; otherwise it must be a live
 * `id<CAMetalDrawable>` retained until this synchronous call returns. A
 * drawable must not be supplied when rendering is disabled. Calls may
 * originate on arbitrary threads; this library serializes runtime state.
 */
NuxStatus nux_flow_render_session_advance(const struct NuxFlowRenderSession *session,
                                          const struct NuxFrameOperation *operation,
                                          struct NuxOperationResult **out_result);

/**
 * Creates logical Apple presentation state for a render session.
 *
 * # Safety
 *
 * Handles and output pointers must be valid. Calls may originate on arbitrary
 * threads; this library serializes runtime state. Swift remains responsible
 * for configuring its `CAMetalLayer` and acquiring each drawable.
 */
NuxStatus nux_flow_render_session_attach_apple_surface(const struct NuxFlowRenderSession *session,
                                                       const struct NuxAppleSurfaceDescriptor *descriptor,
                                                       struct NuxAppleSurface **out_surface,
                                                       struct NuxOperationResult **out_result);

/**
 * Creates an independent logical screen session from a context.
 *
 * # Safety
 *
 * `context` must be live. The descriptor and output pointers must be valid,
 * aligned, and readable or writable as their direction requires. Calls may
 * originate on arbitrary threads; this library serializes runtime state.
 */
NuxStatus nux_flow_render_session_create(const struct NuxFlowRuntimeContext *context,
                                         const struct NuxFlowSessionDescriptor *descriptor,
                                         struct NuxFlowRenderSession **out_session,
                                         struct NuxOperationResult **out_result);

/**
 * Releases one render-session handle. Null is a no-op.
 *
 * # Safety
 *
 * A non-null pointer must be an owned handle returned by this library and not
 * previously released. Release must not race a call using the same handle.
 * Child surfaces may remain alive.
 */
void nux_flow_render_session_free(struct NuxFlowRenderSession *session);

/**
 * Imports one visual artifact into a retained runtime context.
 *
 * # Safety
 *
 * Non-null pointers must be properly aligned and valid for this call.
 * `request.artifact_bytes` must be readable for its declared length. Output
 * pointers must address writable handle storage.
 */
NuxStatus nux_flow_runtime_context_create(const struct NuxFlowImportRequest *request,
                                          struct NuxFlowRuntimeContext **out_context,
                                          struct NuxOperationResult **out_result);

/**
 * Releases one runtime-context handle. Null is a no-op.
 *
 * # Safety
 *
 * A non-null pointer must be an owned handle returned by this library and
 * must not have been released before. Release must not race a call using the
 * same handle. Child handles may remain alive.
 */
void nux_flow_runtime_context_free(struct NuxFlowRuntimeContext *context);

/**
 * Borrows the authenticated key ID stored by an import result.
 *
 * # Safety
 *
 * `result` must be live and `out_key_id` writable. The returned view expires
 * when `result` is released.
 */
NuxStatus nux_operation_result_authenticated_key_id(const struct NuxOperationResult *result,
                                                    struct NuxByteView *out_key_id);

/**
 * Returns whether an operation changed logical runtime state.
 *
 * # Safety
 *
 * A non-null pointer must identify a live result owned by this library.
 */
bool nux_operation_result_changed(const struct NuxOperationResult *result);

/**
 * Borrows the diagnostic bytes stored by an operation result.
 *
 * # Safety
 *
 * `result` must be null or live, and `out_diagnostic` must point to writable
 * storage. A returned byte view expires when `result` is released.
 */
NuxStatus nux_operation_result_diagnostic(const struct NuxOperationResult *result,
                                          struct NuxByteView *out_diagnostic);

/**
 * Borrows one structured diagnostic by stable result order.
 *
 * # Safety
 *
 * `result` must be live and `out_diagnostic` writable with `struct_size`
 * initialized to the exact ABI-major-1 layout size. Returned views expire when
 * `result` is released.
 */
NuxStatus nux_operation_result_diagnostic_at(const struct NuxOperationResult *result,
                                             uint64_t index,
                                             struct NuxDiagnosticView *out_diagnostic);

/**
 * Returns the number of phase-ordered structured diagnostics in a result.
 *
 * # Safety
 *
 * A non-null pointer must identify a live result owned by this library.
 */
uint64_t nux_operation_result_diagnostic_count(const struct NuxOperationResult *result);

/**
 * Releases one operation result. Null is a no-op.
 *
 * # Safety
 *
 * A non-null pointer must be an owned result returned by this library and
 * must not have been released before.
 */
void nux_operation_result_free(struct NuxOperationResult *result);

/**
 * Returns the artifact import's script authorization, or `NOT_APPLICABLE`.
 *
 * # Safety
 *
 * A non-null pointer must identify a live result owned by this library.
 */
NuxScriptAuthorization nux_operation_result_script_authorization(const struct NuxOperationResult *result);

/**
 * Returns an operation result's status, or `NULL_ARGUMENT` for null.
 *
 * # Safety
 *
 * A non-null pointer must identify a live result owned by this library.
 */
NuxStatus nux_operation_result_status(const struct NuxOperationResult *result);

/**
 * Returns an operation result's surface disposition.
 *
 * # Safety
 *
 * A non-null pointer must identify a live result owned by this library.
 */
NuxSurfaceDisposition nux_operation_result_surface_disposition(const struct NuxOperationResult *result);

uint16_t nux_runtime_abi_major(void);

uint16_t nux_runtime_abi_minor(void);

/**
 * Writes a process-static UTF-8 JSON view to `out_provenance`.
 *
 * # Safety
 *
 * `out_provenance` must point to writable, properly aligned storage for one
 * [`NuxByteView`].
 */
NuxStatus nux_runtime_build_provenance(struct NuxByteView *out_provenance);

NuxStatus nux_runtime_require_abi(uint16_t required_major, uint16_t minimum_minor);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NUX_RUNTIME_GENERATED_H */
