#pragma once

#define GLSL_ATLAS_FEATHERED_FILL "NC"
#define GLSL_ATLAS_FEATHERED_FILL_raw NC
#define GLSL_ATLAS_FEATHERED_STROKE "TC"
#define GLSL_ATLAS_FEATHERED_STROKE_raw TC
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE "WD"
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE_raw WD
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH "UD"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH_raw UD
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE "EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE_raw EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT "VD"
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT_raw VD
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM "UE"
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM_raw UE
#define GLSL_BASE_INSTANCE_UNIFORM_NAME "AE"
#define GLSL_BASE_INSTANCE_UNIFORM_NAME_raw AE
#define GLSL_BORROWED_COVERAGE_PASS "EC"
#define GLSL_BORROWED_COVERAGE_PASS_raw EC
#define GLSL_CLEAR_CLIP "RF"
#define GLSL_CLEAR_CLIP_raw RF
#define GLSL_CLEAR_COLOR "RE"
#define GLSL_CLEAR_COLOR_raw RE
#define GLSL_CLEAR_COVERAGE "CE"
#define GLSL_CLEAR_COVERAGE_raw CE
#define GLSL_CLOCKWISE_FILL "DE"
#define GLSL_CLOCKWISE_FILL_raw DE
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER "ZC"
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER_raw ZC
#define GLSL_COLOR_PLANE_IDX_OVERRIDE "LE"
#define GLSL_COLOR_PLANE_IDX_OVERRIDE_raw LE
#define GLSL_DISABLE_ADVANCED_BLEND "VF"
#define GLSL_DISABLE_ADVANCED_BLEND_raw VF
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS "NE"
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS_raw NE
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS "KF"
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS_raw KF
#define GLSL_DRAW_IMAGE "JE"
#define GLSL_DRAW_IMAGE_raw JE
#define GLSL_DRAW_IMAGE_MESH "OB"
#define GLSL_DRAW_IMAGE_MESH_raw OB
#define GLSL_DRAW_IMAGE_RECT "KD"
#define GLSL_DRAW_IMAGE_RECT_raw KD
#define GLSL_DRAW_INTERIOR_TRIANGLES "EB"
#define GLSL_DRAW_INTERIOR_TRIANGLES_raw EB
#define GLSL_DRAW_PATH "JD"
#define GLSL_DRAW_PATH_raw JD
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS "BF"
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS_raw BF
#define GLSL_EMULATE_DYNAMIC_COLOR_WRITE_DISABLE "GD"
#define GLSL_EMULATE_DYNAMIC_COLOR_WRITE_DISABLE_raw GD
#define GLSL_ENABLE_ADVANCED_BLEND "AB"
#define GLSL_ENABLE_ADVANCED_BLEND_raw AB
#define GLSL_ENABLE_CLIPPING "I"
#define GLSL_ENABLE_CLIPPING_raw I
#define GLSL_ENABLE_CLIP_RECT "BB"
#define GLSL_ENABLE_CLIP_RECT_raw BB
#define GLSL_ENABLE_DITHER "LB"
#define GLSL_ENABLE_DITHER_raw LB
#define GLSL_ENABLE_EVEN_ODD "WC"
#define GLSL_ENABLE_EVEN_ODD_raw WC
#define GLSL_ENABLE_FEATHER "HB"
#define GLSL_ENABLE_FEATHER_raw HB
#define GLSL_ENABLE_HSL_BLEND_MODES "FC"
#define GLSL_ENABLE_HSL_BLEND_MODES_raw FC
#define GLSL_ENABLE_INSTANCE_INDEX "OE"
#define GLSL_ENABLE_INSTANCE_INDEX_raw OE
#define GLSL_ENABLE_KHR_BLEND "IE"
#define GLSL_ENABLE_KHR_BLEND_raw IE
#define GLSL_ENABLE_MIN_16_PRECISION "PE"
#define GLSL_ENABLE_MIN_16_PRECISION_raw PE
#define GLSL_ENABLE_NESTED_CLIPPING "YC"
#define GLSL_ENABLE_NESTED_CLIPPING_raw YC
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS "QE"
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS_raw QE
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE "SC"
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE_raw SC
#define GLSL_FEATHER_ATLAS_BLIT "FB"
#define GLSL_FEATHER_ATLAS_BLIT_raw FB
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT "Q"
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT_raw Q
#define GLSL_FRAGMENT "GB"
#define GLSL_FRAGMENT_raw GB
#define GLSL_FRAMEBUFFER_BOTTOM_UP "AG"
#define GLSL_FRAMEBUFFER_BOTTOM_UP_raw AG
#define GLSL_FlushUniforms "CC"
#define GLSL_FlushUniforms_raw CC
#define GLSL_GLSL_VERSION "MC"
#define GLSL_GLSL_VERSION_raw MC
#define GLSL_GL_RENDERER_MALI "IF"
#define GLSL_GL_RENDERER_MALI_raw IF
#define GLSL_INITIALIZE_PLS "KE"
#define GLSL_INITIALIZE_PLS_raw KE
#define GLSL_INPUT_ATTACHMENT_BINDING "AF"
#define GLSL_INPUT_ATTACHMENT_BINDING_raw AF
#define GLSL_LOAD_COLOR "TE"
#define GLSL_LOAD_COLOR_raw TE
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE "ND"
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE_raw ND
#define GLSL_NEEDS_CLIP_DISTANCE "YE"
#define GLSL_NEEDS_CLIP_DISTANCE_raw YE
#define GLSL_NEEDS_GAMMA_CORRECTION "BC"
#define GLSL_NEEDS_GAMMA_CORRECTION_raw BC
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND "CF"
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND_raw CF
#define GLSL_NESTED_CLIP_UPDATE_ONLY "FD"
#define GLSL_NESTED_CLIP_UPDATE_ONLY_raw FD
#define GLSL_NEVER_GENERATE_PREMULTIPLIED_PAINT_COLORS "ZF"
#define GLSL_NEVER_GENERATE_PREMULTIPLIED_PAINT_COLORS_raw ZF
#define GLSL_NO_VARYING "ZE"
#define GLSL_NO_VARYING_raw ZE
#define GLSL_OPTIONALLY_FLAT "MB"
#define GLSL_OPTIONALLY_FLAT_raw MB
#define GLSL_PLS_BLEND_SRC_OVER "VC"
#define GLSL_PLS_BLEND_SRC_OVER_raw VC
#define GLSL_PLS_IMPL_ANGLE "EXPORTED_PLS_IMPL_ANGLE"
#define GLSL_PLS_IMPL_ANGLE_raw EXPORTED_PLS_IMPL_ANGLE
#define GLSL_PLS_IMPL_DEVICE_BUFFER "PF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_raw PF
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED "QF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED_raw QF
#define GLSL_PLS_IMPL_EXT_NATIVE "MF"
#define GLSL_PLS_IMPL_EXT_NATIVE_raw MF
#define GLSL_PLS_IMPL_NONE "OF"
#define GLSL_PLS_IMPL_NONE_raw OF
#define GLSL_PLS_IMPL_STORAGE_BUFFER "XD"
#define GLSL_PLS_IMPL_STORAGE_BUFFER_raw XD
#define GLSL_PLS_IMPL_STORAGE_TEXTURE "ZD"
#define GLSL_PLS_IMPL_STORAGE_TEXTURE_raw ZD
#define GLSL_PLS_IMPL_SUBPASS_LOAD "NF"
#define GLSL_PLS_IMPL_SUBPASS_LOAD_raw NF
#define GLSL_POST_INVERT_Y "RC"
#define GLSL_POST_INVERT_Y_raw RC
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC "SB"
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC_raw SB
#define GLSL_RENDER_MODE_MSAA "CB"
#define GLSL_RENDER_MODE_MSAA_raw CB
#define GLSL_RESOLVE_PLS "QC"
#define GLSL_RESOLVE_PLS_raw QC
#define GLSL_SOURCE_TEXTURE_MSAA "OD"
#define GLSL_SOURCE_TEXTURE_MSAA_raw OD
#define GLSL_STORE_COLOR "BE"
#define GLSL_STORE_COLOR_raw BE
#define GLSL_STORE_COLOR_CLEAR "MD"
#define GLSL_STORE_COLOR_CLEAR_raw MD
#define GLSL_SUPPORTS_SUBPASS_LOAD "UF"
#define GLSL_SUPPORTS_SUBPASS_LOAD_raw UF
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA "DF"
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA_raw DF
#define GLSL_TARGET_SPIRV "DC"
#define GLSL_TARGET_SPIRV_raw DC
#define GLSL_TARGET_WGSL "YD"
#define GLSL_TARGET_WGSL_raw YD
#define GLSL_TESS_TEXTURE_FLOATING_POINT "HF"
#define GLSL_TESS_TEXTURE_FLOATING_POINT_raw HF
#define GLSL_USE_FILTERING "CD"
#define GLSL_USE_FILTERING_raw CD
#define GLSL_USE_WEBGPU_SAMPLERS "JF"
#define GLSL_USE_WEBGPU_SAMPLERS_raw JF
#define GLSL_USING_PLS_STORAGE_TEXTURES "LF"
#define GLSL_USING_PLS_STORAGE_TEXTURES_raw LF
#define GLSL_VERTEX "DB"
#define GLSL_VERTEX_raw DB
#define GLSL_VULKAN_VENDOR_ARM "DD"
#define GLSL_VULKAN_VENDOR_ARM_raw DD
#define GLSL_a_args "TB"
#define GLSL_a_args_raw TB
#define GLSL_a_color0 "RD"
#define GLSL_a_color0_raw RD
#define GLSL_a_color1 "SD"
#define GLSL_a_color1_raw SD
#define GLSL_a_contourIDWithFlags "HE"
#define GLSL_a_contourIDWithFlags_raw HE
#define GLSL_a_imageDrawBlendMode "ZB"
#define GLSL_a_imageDrawBlendMode_raw ZB
#define GLSL_a_imageDrawClipID "YB"
#define GLSL_a_imageDrawClipID_raw YB
#define GLSL_a_imageDrawClipRectInverseMatrix "QB"
#define GLSL_a_imageDrawClipRectInverseMatrix_raw QB
#define GLSL_a_imageDrawOpacity "XB"
#define GLSL_a_imageDrawOpacity_raw XB
#define GLSL_a_imageDrawPacked "IB"
#define GLSL_a_imageDrawPacked_raw IB
#define GLSL_a_imageDrawTranslates "NB"
#define GLSL_a_imageDrawTranslates_raw NB
#define GLSL_a_imageDrawViewMatrix "WB"
#define GLSL_a_imageDrawViewMatrix_raw WB
#define GLSL_a_imageDrawZIndex "AC"
#define GLSL_a_imageDrawZIndex_raw AC
#define GLSL_a_imageRectVertex "HC"
#define GLSL_a_imageRectVertex_raw HC
#define GLSL_a_joinTan_and_ys "UC"
#define GLSL_a_joinTan_and_ys_raw UC
#define GLSL_a_mirroredVertexData "VB"
#define GLSL_a_mirroredVertexData_raw VB
#define GLSL_a_p0p1_ "HD"
#define GLSL_a_p0p1__raw HD
#define GLSL_a_p2p3_ "ID"
#define GLSL_a_p2p3__raw ID
#define GLSL_a_patchVertexData "UB"
#define GLSL_a_patchVertexData_raw UB
#define GLSL_a_position "OC"
#define GLSL_a_position_raw OC
#define GLSL_a_reflectionX0X1 "FE"
#define GLSL_a_reflectionX0X1_raw FE
#define GLSL_a_segmentCounts "GE"
#define GLSL_a_segmentCounts_raw GE
#define GLSL_a_span "KC"
#define GLSL_a_span_raw KC
#define GLSL_a_spanX "PD"
#define GLSL_a_spanX_raw PD
#define GLSL_a_texCoord "PC"
#define GLSL_a_texCoord_raw PC
#define GLSL_a_triangleVertex "KB"
#define GLSL_a_triangleVertex_raw KB
#define GLSL_a_x0x1 "EE"
#define GLSL_a_x0x1_raw EE
#define GLSL_a_yWithFlags "QD"
#define GLSL_a_yWithFlags_raw QD
#define GLSL_atlasFillFragmentMain "VE"
#define GLSL_atlasFillFragmentMain_raw VE
#define GLSL_atlasRenderTexture "XE"
#define GLSL_atlasRenderTexture_raw XE
#define GLSL_atlasResolveVertexMain "TF"
#define GLSL_atlasResolveVertexMain_raw TF
#define GLSL_atlasStrokeFragmentMain "WE"
#define GLSL_atlasStrokeFragmentMain_raw WE
#define GLSL_atlasVertexMain "SF"
#define GLSL_atlasVertexMain_raw SF
#define GLSL_blitFragmentMain "ME"
#define GLSL_blitFragmentMain_raw ME
#define GLSL_blitVertexMain "EF"
#define GLSL_blitVertexMain_raw EF
#define GLSL_clearColor "SE"
#define GLSL_clearColor_raw SE
#define GLSL_colorRampFragmentMain "GF"
#define GLSL_colorRampFragmentMain_raw GF
#define GLSL_colorRampVertexMain "FF"
#define GLSL_colorRampVertexMain_raw FF
#define GLSL_contourBuffer "ED"
#define GLSL_contourBuffer_raw ED
#define GLSL_drawFragmentMain "JB"
#define GLSL_drawFragmentMain_raw JB
#define GLSL_drawVertexMain "GC"
#define GLSL_drawVertexMain_raw GC
#define GLSL_dstColorTexture "TD"
#define GLSL_dstColorTexture_raw TD
#define GLSL_featherAtlasTexture "BD"
#define GLSL_featherAtlasTexture_raw BD
#define GLSL_gaussianIntegralTexture "XC"
#define GLSL_gaussianIntegralTexture_raw XC
#define GLSL_gradTexture "LD"
#define GLSL_gradTexture_raw LD
#define GLSL_imageTexture "IC"
#define GLSL_imageTexture_raw IC
#define GLSL_paintAuxBuffer "RB"
#define GLSL_paintAuxBuffer_raw RB
#define GLSL_paintBuffer "AD"
#define GLSL_paintBuffer_raw AD
#define GLSL_pathBuffer "PB"
#define GLSL_pathBuffer_raw PB
#define GLSL_sourceTexture "JC"
#define GLSL_sourceTexture_raw JC
#define GLSL_stencilVertexMain "WF"
#define GLSL_stencilVertexMain_raw WF
#define GLSL_tessVertexTexture "LC"
#define GLSL_tessVertexTexture_raw LC
#define GLSL_tessellateFragmentMain "YF"
#define GLSL_tessellateFragmentMain_raw YF
#define GLSL_tessellateVertexMain "XF"
#define GLSL_tessellateVertexMain_raw XF
