#pragma once

#define GLSL_ATLAS_FEATHERED_FILL "OC"
#define GLSL_ATLAS_FEATHERED_FILL_raw OC
#define GLSL_ATLAS_FEATHERED_STROKE "UC"
#define GLSL_ATLAS_FEATHERED_STROKE_raw UC
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE "XD"
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE_raw XD
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH "VD"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH_raw VD
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE "EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE_raw EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT "WD"
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT_raw WD
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM "VE"
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM_raw VE
#define GLSL_BASE_INSTANCE_UNIFORM_NAME "BE"
#define GLSL_BASE_INSTANCE_UNIFORM_NAME_raw BE
#define GLSL_BORROWED_COVERAGE_PASS "FC"
#define GLSL_BORROWED_COVERAGE_PASS_raw FC
#define GLSL_CLEAR_CLIP "SF"
#define GLSL_CLEAR_CLIP_raw SF
#define GLSL_CLEAR_COLOR "SE"
#define GLSL_CLEAR_COLOR_raw SE
#define GLSL_CLEAR_COVERAGE "DE"
#define GLSL_CLEAR_COVERAGE_raw DE
#define GLSL_CLOCKWISE_FILL "EE"
#define GLSL_CLOCKWISE_FILL_raw EE
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER "AD"
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER_raw AD
#define GLSL_COLOR_PLANE_IDX_OVERRIDE "ME"
#define GLSL_COLOR_PLANE_IDX_OVERRIDE_raw ME
#define GLSL_DISABLE_ADVANCED_BLEND "WF"
#define GLSL_DISABLE_ADVANCED_BLEND_raw WF
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS "OE"
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS_raw OE
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS "LF"
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS_raw LF
#define GLSL_DRAW_IMAGE "KE"
#define GLSL_DRAW_IMAGE_raw KE
#define GLSL_DRAW_IMAGE_MESH "PB"
#define GLSL_DRAW_IMAGE_MESH_raw PB
#define GLSL_DRAW_IMAGE_RECT "LD"
#define GLSL_DRAW_IMAGE_RECT_raw LD
#define GLSL_DRAW_INTERIOR_TRIANGLES "EB"
#define GLSL_DRAW_INTERIOR_TRIANGLES_raw EB
#define GLSL_DRAW_PATH "KD"
#define GLSL_DRAW_PATH_raw KD
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS "CF"
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS_raw CF
#define GLSL_EMULATE_DYNAMIC_COLOR_WRITE_DISABLE "HD"
#define GLSL_EMULATE_DYNAMIC_COLOR_WRITE_DISABLE_raw HD
#define GLSL_ENABLE_ADVANCED_BLEND "AB"
#define GLSL_ENABLE_ADVANCED_BLEND_raw AB
#define GLSL_ENABLE_CLIPPING "I"
#define GLSL_ENABLE_CLIPPING_raw I
#define GLSL_ENABLE_CLIP_RECT "BB"
#define GLSL_ENABLE_CLIP_RECT_raw BB
#define GLSL_ENABLE_DITHER "MB"
#define GLSL_ENABLE_DITHER_raw MB
#define GLSL_ENABLE_EVEN_ODD "XC"
#define GLSL_ENABLE_EVEN_ODD_raw XC
#define GLSL_ENABLE_FEATHER "HB"
#define GLSL_ENABLE_FEATHER_raw HB
#define GLSL_ENABLE_HSL_BLEND_MODES "GC"
#define GLSL_ENABLE_HSL_BLEND_MODES_raw GC
#define GLSL_ENABLE_INSTANCE_INDEX "PE"
#define GLSL_ENABLE_INSTANCE_INDEX_raw PE
#define GLSL_ENABLE_KHR_BLEND "JE"
#define GLSL_ENABLE_KHR_BLEND_raw JE
#define GLSL_ENABLE_MIN_16_PRECISION "QE"
#define GLSL_ENABLE_MIN_16_PRECISION_raw QE
#define GLSL_ENABLE_MODULATED_IMAGE "KB"
#define GLSL_ENABLE_MODULATED_IMAGE_raw KB
#define GLSL_ENABLE_NESTED_CLIPPING "ZC"
#define GLSL_ENABLE_NESTED_CLIPPING_raw ZC
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS "RE"
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS_raw RE
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE "TC"
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE_raw TC
#define GLSL_FEATHER_ATLAS_BLIT "FB"
#define GLSL_FEATHER_ATLAS_BLIT_raw FB
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT "Q"
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT_raw Q
#define GLSL_FRAGMENT "GB"
#define GLSL_FRAGMENT_raw GB
#define GLSL_FRAMEBUFFER_BOTTOM_UP "BG"
#define GLSL_FRAMEBUFFER_BOTTOM_UP_raw BG
#define GLSL_FlushUniforms "DC"
#define GLSL_FlushUniforms_raw DC
#define GLSL_GLSL_VERSION "NC"
#define GLSL_GLSL_VERSION_raw NC
#define GLSL_GL_RENDERER_MALI "JF"
#define GLSL_GL_RENDERER_MALI_raw JF
#define GLSL_INITIALIZE_PLS "LE"
#define GLSL_INITIALIZE_PLS_raw LE
#define GLSL_INPUT_ATTACHMENT_BINDING "BF"
#define GLSL_INPUT_ATTACHMENT_BINDING_raw BF
#define GLSL_LOAD_COLOR "UE"
#define GLSL_LOAD_COLOR_raw UE
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE "OD"
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE_raw OD
#define GLSL_NEEDS_CLIP_DISTANCE "ZE"
#define GLSL_NEEDS_CLIP_DISTANCE_raw ZE
#define GLSL_NEEDS_GAMMA_CORRECTION "CC"
#define GLSL_NEEDS_GAMMA_CORRECTION_raw CC
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND "DF"
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND_raw DF
#define GLSL_NESTED_CLIP_UPDATE_ONLY "GD"
#define GLSL_NESTED_CLIP_UPDATE_ONLY_raw GD
#define GLSL_NEVER_GENERATE_PREMULTIPLIED_PAINT_COLORS "AG"
#define GLSL_NEVER_GENERATE_PREMULTIPLIED_PAINT_COLORS_raw AG
#define GLSL_NO_VARYING "AF"
#define GLSL_NO_VARYING_raw AF
#define GLSL_OPTIONALLY_FLAT "NB"
#define GLSL_OPTIONALLY_FLAT_raw NB
#define GLSL_PLS_BLEND_SRC_OVER "WC"
#define GLSL_PLS_BLEND_SRC_OVER_raw WC
#define GLSL_PLS_IMPL_ANGLE "EXPORTED_PLS_IMPL_ANGLE"
#define GLSL_PLS_IMPL_ANGLE_raw EXPORTED_PLS_IMPL_ANGLE
#define GLSL_PLS_IMPL_DEVICE_BUFFER "QF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_raw QF
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED "RF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED_raw RF
#define GLSL_PLS_IMPL_EXT_NATIVE "NF"
#define GLSL_PLS_IMPL_EXT_NATIVE_raw NF
#define GLSL_PLS_IMPL_NONE "PF"
#define GLSL_PLS_IMPL_NONE_raw PF
#define GLSL_PLS_IMPL_STORAGE_BUFFER "YD"
#define GLSL_PLS_IMPL_STORAGE_BUFFER_raw YD
#define GLSL_PLS_IMPL_STORAGE_TEXTURE "AE"
#define GLSL_PLS_IMPL_STORAGE_TEXTURE_raw AE
#define GLSL_PLS_IMPL_SUBPASS_LOAD "OF"
#define GLSL_PLS_IMPL_SUBPASS_LOAD_raw OF
#define GLSL_POST_INVERT_Y "SC"
#define GLSL_POST_INVERT_Y_raw SC
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC "TB"
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC_raw TB
#define GLSL_RENDER_MODE_MSAA "CB"
#define GLSL_RENDER_MODE_MSAA_raw CB
#define GLSL_RESOLVE_PLS "RC"
#define GLSL_RESOLVE_PLS_raw RC
#define GLSL_SOURCE_TEXTURE_MSAA "PD"
#define GLSL_SOURCE_TEXTURE_MSAA_raw PD
#define GLSL_STORE_COLOR "CE"
#define GLSL_STORE_COLOR_raw CE
#define GLSL_STORE_COLOR_CLEAR "ND"
#define GLSL_STORE_COLOR_CLEAR_raw ND
#define GLSL_SUPPORTS_SUBPASS_LOAD "VF"
#define GLSL_SUPPORTS_SUBPASS_LOAD_raw VF
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA "EF"
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA_raw EF
#define GLSL_TARGET_SPIRV "EC"
#define GLSL_TARGET_SPIRV_raw EC
#define GLSL_TARGET_WGSL "ZD"
#define GLSL_TARGET_WGSL_raw ZD
#define GLSL_TESS_TEXTURE_FLOATING_POINT "IF"
#define GLSL_TESS_TEXTURE_FLOATING_POINT_raw IF
#define GLSL_USE_FILTERING "DD"
#define GLSL_USE_FILTERING_raw DD
#define GLSL_USE_WEBGPU_SAMPLERS "KF"
#define GLSL_USE_WEBGPU_SAMPLERS_raw KF
#define GLSL_USING_PLS_STORAGE_TEXTURES "MF"
#define GLSL_USING_PLS_STORAGE_TEXTURES_raw MF
#define GLSL_VERTEX "DB"
#define GLSL_VERTEX_raw DB
#define GLSL_VULKAN_VENDOR_ARM "ED"
#define GLSL_VULKAN_VENDOR_ARM_raw ED
#define GLSL_a_args "UB"
#define GLSL_a_args_raw UB
#define GLSL_a_color0 "SD"
#define GLSL_a_color0_raw SD
#define GLSL_a_color1 "TD"
#define GLSL_a_color1_raw TD
#define GLSL_a_contourIDWithFlags "IE"
#define GLSL_a_contourIDWithFlags_raw IE
#define GLSL_a_imageDrawBlendMode "AC"
#define GLSL_a_imageDrawBlendMode_raw AC
#define GLSL_a_imageDrawClipID "ZB"
#define GLSL_a_imageDrawClipID_raw ZB
#define GLSL_a_imageDrawClipRectInverseMatrix "SB"
#define GLSL_a_imageDrawClipRectInverseMatrix_raw SB
#define GLSL_a_imageDrawOpacity "YB"
#define GLSL_a_imageDrawOpacity_raw YB
#define GLSL_a_imageDrawPacked "IB"
#define GLSL_a_imageDrawPacked_raw IB
#define GLSL_a_imageDrawTranslates "OB"
#define GLSL_a_imageDrawTranslates_raw OB
#define GLSL_a_imageDrawViewMatrix "XB"
#define GLSL_a_imageDrawViewMatrix_raw XB
#define GLSL_a_imageDrawZIndex "BC"
#define GLSL_a_imageDrawZIndex_raw BC
#define GLSL_a_imageRectVertex "IC"
#define GLSL_a_imageRectVertex_raw IC
#define GLSL_a_joinTan_and_ys "VC"
#define GLSL_a_joinTan_and_ys_raw VC
#define GLSL_a_mirroredVertexData "WB"
#define GLSL_a_mirroredVertexData_raw WB
#define GLSL_a_p0p1_ "ID"
#define GLSL_a_p0p1__raw ID
#define GLSL_a_p2p3_ "JD"
#define GLSL_a_p2p3__raw JD
#define GLSL_a_patchVertexData "VB"
#define GLSL_a_patchVertexData_raw VB
#define GLSL_a_position "PC"
#define GLSL_a_position_raw PC
#define GLSL_a_reflectionX0X1 "GE"
#define GLSL_a_reflectionX0X1_raw GE
#define GLSL_a_segmentCounts "HE"
#define GLSL_a_segmentCounts_raw HE
#define GLSL_a_span "LC"
#define GLSL_a_span_raw LC
#define GLSL_a_spanX "QD"
#define GLSL_a_spanX_raw QD
#define GLSL_a_texCoord "QC"
#define GLSL_a_texCoord_raw QC
#define GLSL_a_triangleVertex "LB"
#define GLSL_a_triangleVertex_raw LB
#define GLSL_a_x0x1 "FE"
#define GLSL_a_x0x1_raw FE
#define GLSL_a_yWithFlags "RD"
#define GLSL_a_yWithFlags_raw RD
#define GLSL_atlasFillFragmentMain "WE"
#define GLSL_atlasFillFragmentMain_raw WE
#define GLSL_atlasRenderTexture "YE"
#define GLSL_atlasRenderTexture_raw YE
#define GLSL_atlasResolveVertexMain "UF"
#define GLSL_atlasResolveVertexMain_raw UF
#define GLSL_atlasStrokeFragmentMain "XE"
#define GLSL_atlasStrokeFragmentMain_raw XE
#define GLSL_atlasVertexMain "TF"
#define GLSL_atlasVertexMain_raw TF
#define GLSL_blitFragmentMain "NE"
#define GLSL_blitFragmentMain_raw NE
#define GLSL_blitVertexMain "FF"
#define GLSL_blitVertexMain_raw FF
#define GLSL_clearColor "TE"
#define GLSL_clearColor_raw TE
#define GLSL_colorRampFragmentMain "HF"
#define GLSL_colorRampFragmentMain_raw HF
#define GLSL_colorRampVertexMain "GF"
#define GLSL_colorRampVertexMain_raw GF
#define GLSL_contourBuffer "FD"
#define GLSL_contourBuffer_raw FD
#define GLSL_drawFragmentMain "JB"
#define GLSL_drawFragmentMain_raw JB
#define GLSL_drawVertexMain "HC"
#define GLSL_drawVertexMain_raw HC
#define GLSL_dstColorTexture "UD"
#define GLSL_dstColorTexture_raw UD
#define GLSL_featherAtlasTexture "CD"
#define GLSL_featherAtlasTexture_raw CD
#define GLSL_gaussianIntegralTexture "YC"
#define GLSL_gaussianIntegralTexture_raw YC
#define GLSL_gradTexture "MD"
#define GLSL_gradTexture_raw MD
#define GLSL_imageTexture "JC"
#define GLSL_imageTexture_raw JC
#define GLSL_paintAuxBuffer "RB"
#define GLSL_paintAuxBuffer_raw RB
#define GLSL_paintBuffer "BD"
#define GLSL_paintBuffer_raw BD
#define GLSL_pathBuffer "QB"
#define GLSL_pathBuffer_raw QB
#define GLSL_sourceTexture "KC"
#define GLSL_sourceTexture_raw KC
#define GLSL_stencilVertexMain "XF"
#define GLSL_stencilVertexMain_raw XF
#define GLSL_tessVertexTexture "MC"
#define GLSL_tessVertexTexture_raw MC
#define GLSL_tessellateFragmentMain "ZF"
#define GLSL_tessellateFragmentMain_raw ZF
#define GLSL_tessellateVertexMain "YF"
#define GLSL_tessellateVertexMain_raw YF
