#pragma once

#define GLSL_ATLAS_FEATHERED_FILL "NC"
#define GLSL_ATLAS_FEATHERED_FILL_raw NC
#define GLSL_ATLAS_FEATHERED_STROKE "TC"
#define GLSL_ATLAS_FEATHERED_STROKE_raw TC
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE "XD"
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE_raw XD
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH "VD"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH_raw VD
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE "EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE_raw EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT "WD"
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT_raw WD
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM "UE"
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM_raw UE
#define GLSL_BASE_INSTANCE_UNIFORM_NAME "AE"
#define GLSL_BASE_INSTANCE_UNIFORM_NAME_raw AE
#define GLSL_BORROWED_COVERAGE_PASS "DC"
#define GLSL_BORROWED_COVERAGE_PASS_raw DC
#define GLSL_CLEAR_CLIP "SF"
#define GLSL_CLEAR_CLIP_raw SF
#define GLSL_CLEAR_COLOR "RE"
#define GLSL_CLEAR_COLOR_raw RE
#define GLSL_CLEAR_COVERAGE "CE"
#define GLSL_CLEAR_COVERAGE_raw CE
#define GLSL_CLOCKWISE_FILL "DE"
#define GLSL_CLOCKWISE_FILL_raw DE
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER "ZC"
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER_raw ZC
#define GLSL_COLOR_PLANE_IDX_OVERRIDE "LE"
#define GLSL_COLOR_PLANE_IDX_OVERRIDE_raw LE
#define GLSL_DISABLE_ADVANCED_BLEND "YF"
#define GLSL_DISABLE_ADVANCED_BLEND_raw YF
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS "NE"
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS_raw NE
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS "LF"
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS_raw LF
#define GLSL_DRAW_IMAGE "JE"
#define GLSL_DRAW_IMAGE_raw JE
#define GLSL_DRAW_IMAGE_MESH "OB"
#define GLSL_DRAW_IMAGE_MESH_raw OB
#define GLSL_DRAW_IMAGE_RECT "LD"
#define GLSL_DRAW_IMAGE_RECT_raw LD
#define GLSL_DRAW_INTERIOR_TRIANGLES "EB"
#define GLSL_DRAW_INTERIOR_TRIANGLES_raw EB
#define GLSL_DRAW_PATH "KD"
#define GLSL_DRAW_PATH_raw KD
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS "CF"
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS_raw CF
#define GLSL_EMULATE_DYNAMIC_COLOR_WRITE_DISABLE "HD"
#define GLSL_EMULATE_DYNAMIC_COLOR_WRITE_DISABLE_raw HD
#define GLSL_ENABLE_ADVANCED_BLEND "AB"
#define GLSL_ENABLE_ADVANCED_BLEND_raw AB
#define GLSL_ENABLE_CLIPPING "I"
#define GLSL_ENABLE_CLIPPING_raw I
#define GLSL_ENABLE_CLIP_RECT "BB"
#define GLSL_ENABLE_CLIP_RECT_raw BB
#define GLSL_ENABLE_DITHER "LB"
#define GLSL_ENABLE_DITHER_raw LB
#define GLSL_ENABLE_EVEN_ODD "WC"
#define GLSL_ENABLE_EVEN_ODD_raw WC
#define GLSL_ENABLE_FEATHER "HB"
#define GLSL_ENABLE_FEATHER_raw HB
#define GLSL_ENABLE_HSL_BLEND_MODES "EC"
#define GLSL_ENABLE_HSL_BLEND_MODES_raw EC
#define GLSL_ENABLE_INSTANCE_INDEX "OE"
#define GLSL_ENABLE_INSTANCE_INDEX_raw OE
#define GLSL_ENABLE_KHR_BLEND "IE"
#define GLSL_ENABLE_KHR_BLEND_raw IE
#define GLSL_ENABLE_MIN_16_PRECISION "PE"
#define GLSL_ENABLE_MIN_16_PRECISION_raw PE
#define GLSL_ENABLE_MODULATED_IMAGE "JB"
#define GLSL_ENABLE_MODULATED_IMAGE_raw JB
#define GLSL_ENABLE_NESTED_CLIPPING "YC"
#define GLSL_ENABLE_NESTED_CLIPPING_raw YC
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS "QE"
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS_raw QE
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE "SC"
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE_raw SC
#define GLSL_FEATHER_ATLAS_BLIT "FB"
#define GLSL_FEATHER_ATLAS_BLIT_raw FB
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT "N"
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT_raw N
#define GLSL_FRAGMENT "GB"
#define GLSL_FRAGMENT_raw GB
#define GLSL_FRAMEBUFFER_BOTTOM_UP "DG"
#define GLSL_FRAMEBUFFER_BOTTOM_UP_raw DG
#define GLSL_FlushUniforms "BC"
#define GLSL_FlushUniforms_raw BC
#define GLSL_GLSL_VERSION "LC"
#define GLSL_GLSL_VERSION_raw LC
#define GLSL_GL_RENDERER_MALI "JF"
#define GLSL_GL_RENDERER_MALI_raw JF
#define GLSL_INITIALIZE_PLS "KE"
#define GLSL_INITIALIZE_PLS_raw KE
#define GLSL_INPUT_ATTACHMENT_BINDING "BF"
#define GLSL_INPUT_ATTACHMENT_BINDING_raw BF
#define GLSL_LOAD_COLOR "TE"
#define GLSL_LOAD_COLOR_raw TE
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE "OD"
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE_raw OD
#define GLSL_NEEDS_CLIP_DISTANCE "ZE"
#define GLSL_NEEDS_CLIP_DISTANCE_raw ZE
#define GLSL_NEEDS_GAMMA_CORRECTION "AC"
#define GLSL_NEEDS_GAMMA_CORRECTION_raw AC
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND "DF"
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND_raw DF
#define GLSL_NEEDS_USHORT_DEFINE "YE"
#define GLSL_NEEDS_USHORT_DEFINE_raw YE
#define GLSL_NESTED_CLIP_UPDATE_ONLY "GD"
#define GLSL_NESTED_CLIP_UPDATE_ONLY_raw GD
#define GLSL_NEVER_GENERATE_PREMULTIPLIED_PAINT_COLORS "CG"
#define GLSL_NEVER_GENERATE_PREMULTIPLIED_PAINT_COLORS_raw CG
#define GLSL_NO_VARYING "AF"
#define GLSL_NO_VARYING_raw AF
#define GLSL_OPTIONALLY_FLAT "MB"
#define GLSL_OPTIONALLY_FLAT_raw MB
#define GLSL_PLS_BLEND_SRC_OVER "VC"
#define GLSL_PLS_BLEND_SRC_OVER_raw VC
#define GLSL_PLS_IMPL_ANGLE "EXPORTED_PLS_IMPL_ANGLE"
#define GLSL_PLS_IMPL_ANGLE_raw EXPORTED_PLS_IMPL_ANGLE
#define GLSL_PLS_IMPL_DEVICE_BUFFER "QF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_raw QF
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED "RF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED_raw RF
#define GLSL_PLS_IMPL_EXT_NATIVE "NF"
#define GLSL_PLS_IMPL_EXT_NATIVE_raw NF
#define GLSL_PLS_IMPL_NONE "PF"
#define GLSL_PLS_IMPL_NONE_raw PF
#define GLSL_PLS_IMPL_STORAGE_BUFFER "FD"
#define GLSL_PLS_IMPL_STORAGE_BUFFER_raw FD
#define GLSL_PLS_IMPL_STORAGE_TEXTURE "ZD"
#define GLSL_PLS_IMPL_STORAGE_TEXTURE_raw ZD
#define GLSL_PLS_IMPL_SUBPASS_LOAD "OF"
#define GLSL_PLS_IMPL_SUBPASS_LOAD_raw OF
#define GLSL_POST_INVERT_Y "RC"
#define GLSL_POST_INVERT_Y_raw RC
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC "RB"
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC_raw RB
#define GLSL_RENDER_MODE_DEPTH_STENCIL "CB"
#define GLSL_RENDER_MODE_DEPTH_STENCIL_raw CB
#define GLSL_RESOLVE_PLS "QC"
#define GLSL_RESOLVE_PLS_raw QC
#define GLSL_SOURCE_TEXTURE_MSAA "PD"
#define GLSL_SOURCE_TEXTURE_MSAA_raw PD
#define GLSL_STORE_COLOR "BE"
#define GLSL_STORE_COLOR_raw BE
#define GLSL_STORE_COLOR_CLEAR "ND"
#define GLSL_STORE_COLOR_CLEAR_raw ND
#define GLSL_SUPPORTS_MSAA_DST_TEXEL_FETCH "WF"
#define GLSL_SUPPORTS_MSAA_DST_TEXEL_FETCH_raw WF
#define GLSL_SUPPORTS_SUBPASS_LOAD "VF"
#define GLSL_SUPPORTS_SUBPASS_LOAD_raw VF
#define GLSL_SV_INSTANCE_ID_INCLUDES_BASE "XF"
#define GLSL_SV_INSTANCE_ID_INCLUDES_BASE_raw XF
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA "EF"
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA_raw EF
#define GLSL_TARGET_SPIRV "CC"
#define GLSL_TARGET_SPIRV_raw CC
#define GLSL_TARGET_WGSL "YD"
#define GLSL_TARGET_WGSL_raw YD
#define GLSL_TESS_TEXTURE_FLOATING_POINT "IF"
#define GLSL_TESS_TEXTURE_FLOATING_POINT_raw IF
#define GLSL_USE_FILTERING "CD"
#define GLSL_USE_FILTERING_raw CD
#define GLSL_USE_WEBGPU_SAMPLERS "KF"
#define GLSL_USE_WEBGPU_SAMPLERS_raw KF
#define GLSL_USING_PLS_STORAGE_TEXTURES "MF"
#define GLSL_USING_PLS_STORAGE_TEXTURES_raw MF
#define GLSL_VERTEX "DB"
#define GLSL_VERTEX_raw DB
#define GLSL_VULKAN_VENDOR_ARM "DD"
#define GLSL_VULKAN_VENDOR_ARM_raw DD
#define GLSL_a_args "TB"
#define GLSL_a_args_raw TB
#define GLSL_a_color0 "SD"
#define GLSL_a_color0_raw SD
#define GLSL_a_color1 "TD"
#define GLSL_a_color1_raw TD
#define GLSL_a_contourIDWithFlags "HE"
#define GLSL_a_contourIDWithFlags_raw HE
#define GLSL_a_imageDrawBlendMode "ZB"
#define GLSL_a_imageDrawBlendMode_raw ZB
#define GLSL_a_imageDrawClipID "YB"
#define GLSL_a_imageDrawClipID_raw YB
#define GLSL_a_imageDrawClipRectInverseMatrix "SB"
#define GLSL_a_imageDrawClipRectInverseMatrix_raw SB
#define GLSL_a_imageDrawOpacity "XB"
#define GLSL_a_imageDrawOpacity_raw XB
#define GLSL_a_imageDrawTranslates "NB"
#define GLSL_a_imageDrawTranslates_raw NB
#define GLSL_a_imageDrawViewMatrix "WB"
#define GLSL_a_imageDrawViewMatrix_raw WB
#define GLSL_a_imageDrawZIndex "MC"
#define GLSL_a_imageDrawZIndex_raw MC
#define GLSL_a_imageRectVertex "GC"
#define GLSL_a_imageRectVertex_raw GC
#define GLSL_a_joinTan_and_ys "UC"
#define GLSL_a_joinTan_and_ys_raw UC
#define GLSL_a_mirroredVertexData "VB"
#define GLSL_a_mirroredVertexData_raw VB
#define GLSL_a_p0p1_ "ID"
#define GLSL_a_p0p1__raw ID
#define GLSL_a_p2p3_ "JD"
#define GLSL_a_p2p3__raw JD
#define GLSL_a_patchVertexData "UB"
#define GLSL_a_patchVertexData_raw UB
#define GLSL_a_position "OC"
#define GLSL_a_position_raw OC
#define GLSL_a_reflectionX0X1 "FE"
#define GLSL_a_reflectionX0X1_raw FE
#define GLSL_a_segmentCounts "GE"
#define GLSL_a_segmentCounts_raw GE
#define GLSL_a_span "JC"
#define GLSL_a_span_raw JC
#define GLSL_a_spanX "QD"
#define GLSL_a_spanX_raw QD
#define GLSL_a_texCoord "PC"
#define GLSL_a_texCoord_raw PC
#define GLSL_a_triangleVertex "KB"
#define GLSL_a_triangleVertex_raw KB
#define GLSL_a_x0x1 "EE"
#define GLSL_a_x0x1_raw EE
#define GLSL_a_yWithFlags "RD"
#define GLSL_a_yWithFlags_raw RD
#define GLSL_atlasFillFragmentMain "VE"
#define GLSL_atlasFillFragmentMain_raw VE
#define GLSL_atlasRenderTexture "XE"
#define GLSL_atlasRenderTexture_raw XE
#define GLSL_atlasResolveVertexMain "UF"
#define GLSL_atlasResolveVertexMain_raw UF
#define GLSL_atlasStrokeFragmentMain "WE"
#define GLSL_atlasStrokeFragmentMain_raw WE
#define GLSL_atlasVertexMain "TF"
#define GLSL_atlasVertexMain_raw TF
#define GLSL_blitFragmentMain "ME"
#define GLSL_blitFragmentMain_raw ME
#define GLSL_blitVertexMain "FF"
#define GLSL_blitVertexMain_raw FF
#define GLSL_clearColor "SE"
#define GLSL_clearColor_raw SE
#define GLSL_colorRampFragmentMain "HF"
#define GLSL_colorRampFragmentMain_raw HF
#define GLSL_colorRampVertexMain "GF"
#define GLSL_colorRampVertexMain_raw GF
#define GLSL_contourBuffer "ED"
#define GLSL_contourBuffer_raw ED
#define GLSL_drawFragmentMain "IB"
#define GLSL_drawFragmentMain_raw IB
#define GLSL_drawVertexMain "FC"
#define GLSL_drawVertexMain_raw FC
#define GLSL_dstColorTexture "UD"
#define GLSL_dstColorTexture_raw UD
#define GLSL_featherAtlasTexture "BD"
#define GLSL_featherAtlasTexture_raw BD
#define GLSL_gaussianIntegralTexture "XC"
#define GLSL_gaussianIntegralTexture_raw XC
#define GLSL_gradTexture "MD"
#define GLSL_gradTexture_raw MD
#define GLSL_imageTexture "HC"
#define GLSL_imageTexture_raw HC
#define GLSL_paintAuxBuffer "QB"
#define GLSL_paintAuxBuffer_raw QB
#define GLSL_paintBuffer "AD"
#define GLSL_paintBuffer_raw AD
#define GLSL_pathBuffer "PB"
#define GLSL_pathBuffer_raw PB
#define GLSL_sourceTexture "IC"
#define GLSL_sourceTexture_raw IC
#define GLSL_stencilVertexMain "ZF"
#define GLSL_stencilVertexMain_raw ZF
#define GLSL_tessVertexTexture "KC"
#define GLSL_tessVertexTexture_raw KC
#define GLSL_tessellateFragmentMain "BG"
#define GLSL_tessellateFragmentMain_raw BG
#define GLSL_tessellateVertexMain "AG"
#define GLSL_tessellateVertexMain_raw AG
