#pragma once

#define GLSL_ATLAS_FEATHERED_FILL "NC"
#define GLSL_ATLAS_FEATHERED_FILL_raw NC
#define GLSL_ATLAS_FEATHERED_STROKE "UC"
#define GLSL_ATLAS_FEATHERED_STROKE_raw UC
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE "BE"
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE_raw BE
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH "ZD"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH_raw ZD
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE "EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE_raw EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT "AE"
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT_raw AE
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM "AF"
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM_raw AF
#define GLSL_BASE_INSTANCE_UNIFORM_NAME "EE"
#define GLSL_BASE_INSTANCE_UNIFORM_NAME_raw EE
#define GLSL_BORROWED_COVERAGE_PASS "DC"
#define GLSL_BORROWED_COVERAGE_PASS_raw DC
#define GLSL_CLEAR_CLIP "YF"
#define GLSL_CLEAR_CLIP_raw YF
#define GLSL_CLEAR_COLOR "XE"
#define GLSL_CLEAR_COLOR_raw XE
#define GLSL_CLEAR_COVERAGE "GE"
#define GLSL_CLEAR_COVERAGE_raw GE
#define GLSL_CLOCKWISE_FILL "HE"
#define GLSL_CLOCKWISE_FILL_raw HE
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER "CD"
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER_raw CD
#define GLSL_COLOR_PLANE_IDX_OVERRIDE "QE"
#define GLSL_COLOR_PLANE_IDX_OVERRIDE_raw QE
#define GLSL_DISABLE_ADVANCED_BLEND "EG"
#define GLSL_DISABLE_ADVANCED_BLEND_raw EG
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS "SE"
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS_raw SE
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS "RF"
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS_raw RF
#define GLSL_DRAW_IMAGE "OE"
#define GLSL_DRAW_IMAGE_raw OE
#define GLSL_DRAW_IMAGE_MESH "OB"
#define GLSL_DRAW_IMAGE_MESH_raw OB
#define GLSL_DRAW_IMAGE_RECT "AD"
#define GLSL_DRAW_IMAGE_RECT_raw AD
#define GLSL_DRAW_INTERIOR_TRIANGLES "EB"
#define GLSL_DRAW_INTERIOR_TRIANGLES_raw EB
#define GLSL_DRAW_PATH "OD"
#define GLSL_DRAW_PATH_raw OD
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS "IF"
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS_raw IF
#define GLSL_EMULATE_DYNAMIC_COLOR_WRITE_DISABLE "LD"
#define GLSL_EMULATE_DYNAMIC_COLOR_WRITE_DISABLE_raw LD
#define GLSL_ENABLE_ADVANCED_BLEND "AB"
#define GLSL_ENABLE_ADVANCED_BLEND_raw AB
#define GLSL_ENABLE_CLIPPING "I"
#define GLSL_ENABLE_CLIPPING_raw I
#define GLSL_ENABLE_CLIP_RECT "BB"
#define GLSL_ENABLE_CLIP_RECT_raw BB
#define GLSL_ENABLE_DITHER "LB"
#define GLSL_ENABLE_DITHER_raw LB
#define GLSL_ENABLE_EVEN_ODD "XC"
#define GLSL_ENABLE_EVEN_ODD_raw XC
#define GLSL_ENABLE_FEATHER "HB"
#define GLSL_ENABLE_FEATHER_raw HB
#define GLSL_ENABLE_HSL_BLEND_MODES "EC"
#define GLSL_ENABLE_HSL_BLEND_MODES_raw EC
#define GLSL_ENABLE_INSTANCE_INDEX "UE"
#define GLSL_ENABLE_INSTANCE_INDEX_raw UE
#define GLSL_ENABLE_KHR_BLEND "ME"
#define GLSL_ENABLE_KHR_BLEND_raw ME
#define GLSL_ENABLE_MIN_16_PRECISION "VE"
#define GLSL_ENABLE_MIN_16_PRECISION_raw VE
#define GLSL_ENABLE_MODULATED_IMAGE "JB"
#define GLSL_ENABLE_MODULATED_IMAGE_raw JB
#define GLSL_ENABLE_NESTED_CLIPPING "ZC"
#define GLSL_ENABLE_NESTED_CLIPPING_raw ZC
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS "WE"
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS_raw WE
#define GLSL_ENABLE_RENDER_TARGET_BOTTOM_UP "NE"
#define GLSL_ENABLE_RENDER_TARGET_BOTTOM_UP_raw NE
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE "TC"
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE_raw TC
#define GLSL_FEATHER_ATLAS_BLIT "GB"
#define GLSL_FEATHER_ATLAS_BLIT_raw GB
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT "O"
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT_raw O
#define GLSL_FRAGMENT "FB"
#define GLSL_FRAGMENT_raw FB
#define GLSL_FlushUniforms "BC"
#define GLSL_FlushUniforms_raw BC
#define GLSL_GLSL_VERSION "LC"
#define GLSL_GLSL_VERSION_raw LC
#define GLSL_GL_RENDERER_MALI "PF"
#define GLSL_GL_RENDERER_MALI_raw PF
#define GLSL_INITIALIZE_PLS "PE"
#define GLSL_INITIALIZE_PLS_raw PE
#define GLSL_INPUT_ATTACHMENT_BINDING "HF"
#define GLSL_INPUT_ATTACHMENT_BINDING_raw HF
#define GLSL_LOAD_COLOR "ZE"
#define GLSL_LOAD_COLOR_raw ZE
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE "SD"
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE_raw SD
#define GLSL_MSAA_DST_COLOR "TE"
#define GLSL_MSAA_DST_COLOR_raw TE
#define GLSL_NEEDS_CLIP_DISTANCE "FF"
#define GLSL_NEEDS_CLIP_DISTANCE_raw FF
#define GLSL_NEEDS_GAMMA_CORRECTION "AC"
#define GLSL_NEEDS_GAMMA_CORRECTION_raw AC
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND "JF"
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND_raw JF
#define GLSL_NEEDS_USHORT_DEFINE "EF"
#define GLSL_NEEDS_USHORT_DEFINE_raw EF
#define GLSL_NESTED_CLIP_UPDATE_ONLY "KD"
#define GLSL_NESTED_CLIP_UPDATE_ONLY_raw KD
#define GLSL_NO_VARYING "GF"
#define GLSL_NO_VARYING_raw GF
#define GLSL_OPTIONALLY_FLAT "MB"
#define GLSL_OPTIONALLY_FLAT_raw MB
#define GLSL_PLS_BLEND_SRC_OVER "WC"
#define GLSL_PLS_BLEND_SRC_OVER_raw WC
#define GLSL_PLS_IMPL_ANGLE "EXPORTED_PLS_IMPL_ANGLE"
#define GLSL_PLS_IMPL_ANGLE_raw EXPORTED_PLS_IMPL_ANGLE
#define GLSL_PLS_IMPL_DEVICE_BUFFER "WF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_raw WF
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED "XF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED_raw XF
#define GLSL_PLS_IMPL_EXT_NATIVE "TF"
#define GLSL_PLS_IMPL_EXT_NATIVE_raw TF
#define GLSL_PLS_IMPL_NONE "VF"
#define GLSL_PLS_IMPL_NONE_raw VF
#define GLSL_PLS_IMPL_STORAGE_BUFFER "JD"
#define GLSL_PLS_IMPL_STORAGE_BUFFER_raw JD
#define GLSL_PLS_IMPL_STORAGE_TEXTURE "DE"
#define GLSL_PLS_IMPL_STORAGE_TEXTURE_raw DE
#define GLSL_PLS_IMPL_SUBPASS_LOAD "UF"
#define GLSL_PLS_IMPL_SUBPASS_LOAD_raw UF
#define GLSL_POST_INVERT_Y "SC"
#define GLSL_POST_INVERT_Y_raw SC
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC "RB"
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC_raw RB
#define GLSL_RENDER_MODE_DEPTH_STENCIL "CB"
#define GLSL_RENDER_MODE_DEPTH_STENCIL_raw CB
#define GLSL_RESOLVE_PLS "RC"
#define GLSL_RESOLVE_PLS_raw RC
#define GLSL_SOURCE_TEXTURE_MSAA "TD"
#define GLSL_SOURCE_TEXTURE_MSAA_raw TD
#define GLSL_STORE_COLOR "FE"
#define GLSL_STORE_COLOR_raw FE
#define GLSL_STORE_COLOR_CLEAR "RD"
#define GLSL_STORE_COLOR_CLEAR_raw RD
#define GLSL_SUPPORTS_MSAA_DST_TEXEL_FETCH "CG"
#define GLSL_SUPPORTS_MSAA_DST_TEXEL_FETCH_raw CG
#define GLSL_SUPPORTS_SUBPASS_LOAD "BG"
#define GLSL_SUPPORTS_SUBPASS_LOAD_raw BG
#define GLSL_SV_INSTANCE_ID_INCLUDES_BASE "DG"
#define GLSL_SV_INSTANCE_ID_INCLUDES_BASE_raw DG
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA "KF"
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA_raw KF
#define GLSL_TARGET_SPIRV "CC"
#define GLSL_TARGET_SPIRV_raw CC
#define GLSL_TARGET_WGSL "CE"
#define GLSL_TARGET_WGSL_raw CE
#define GLSL_TESS_TEXTURE_FLOATING_POINT "OF"
#define GLSL_TESS_TEXTURE_FLOATING_POINT_raw OF
#define GLSL_USE_FILTERING "GD"
#define GLSL_USE_FILTERING_raw GD
#define GLSL_USE_WEBGPU_SAMPLERS "QF"
#define GLSL_USE_WEBGPU_SAMPLERS_raw QF
#define GLSL_USING_PLS_STORAGE_TEXTURES "SF"
#define GLSL_USING_PLS_STORAGE_TEXTURES_raw SF
#define GLSL_VERTEX "DB"
#define GLSL_VERTEX_raw DB
#define GLSL_VULKAN_VENDOR_ARM "HD"
#define GLSL_VULKAN_VENDOR_ARM_raw HD
#define GLSL_a_args "TB"
#define GLSL_a_args_raw TB
#define GLSL_a_color0 "WD"
#define GLSL_a_color0_raw WD
#define GLSL_a_color1 "XD"
#define GLSL_a_color1_raw XD
#define GLSL_a_contourIDWithFlags "LE"
#define GLSL_a_contourIDWithFlags_raw LE
#define GLSL_a_imageDrawBlendMode "ZB"
#define GLSL_a_imageDrawBlendMode_raw ZB
#define GLSL_a_imageDrawClipID "YB"
#define GLSL_a_imageDrawClipID_raw YB
#define GLSL_a_imageDrawClipRectInverseMatrix "SB"
#define GLSL_a_imageDrawClipRectInverseMatrix_raw SB
#define GLSL_a_imageDrawModulatedColor "XB"
#define GLSL_a_imageDrawModulatedColor_raw XB
#define GLSL_a_imageDrawTranslates "NB"
#define GLSL_a_imageDrawTranslates_raw NB
#define GLSL_a_imageDrawViewMatrix "WB"
#define GLSL_a_imageDrawViewMatrix_raw WB
#define GLSL_a_imageDrawZIndex "MC"
#define GLSL_a_imageDrawZIndex_raw MC
#define GLSL_a_imageRectGradientMatrix "QD"
#define GLSL_a_imageRectGradientMatrix_raw QD
#define GLSL_a_imageRectImageAndGradientTranslates "BD"
#define GLSL_a_imageRectImageAndGradientTranslates_raw BD
#define GLSL_a_imageRectImageMatrix "PD"
#define GLSL_a_imageRectImageMatrix_raw PD
#define GLSL_a_imageRectPackedGradientData "OC"
#define GLSL_a_imageRectPackedGradientData_raw OC
#define GLSL_a_imageRectVertex "GC"
#define GLSL_a_imageRectVertex_raw GC
#define GLSL_a_joinTan_and_ys "VC"
#define GLSL_a_joinTan_and_ys_raw VC
#define GLSL_a_mirroredVertexData "VB"
#define GLSL_a_mirroredVertexData_raw VB
#define GLSL_a_p0p1_ "MD"
#define GLSL_a_p0p1__raw MD
#define GLSL_a_p2p3_ "ND"
#define GLSL_a_p2p3__raw ND
#define GLSL_a_patchVertexData "UB"
#define GLSL_a_patchVertexData_raw UB
#define GLSL_a_position "PC"
#define GLSL_a_position_raw PC
#define GLSL_a_reflectionX0X1 "JE"
#define GLSL_a_reflectionX0X1_raw JE
#define GLSL_a_segmentCounts "KE"
#define GLSL_a_segmentCounts_raw KE
#define GLSL_a_span "JC"
#define GLSL_a_span_raw JC
#define GLSL_a_spanX "UD"
#define GLSL_a_spanX_raw UD
#define GLSL_a_texCoord "QC"
#define GLSL_a_texCoord_raw QC
#define GLSL_a_triangleVertex "KB"
#define GLSL_a_triangleVertex_raw KB
#define GLSL_a_x0x1 "IE"
#define GLSL_a_x0x1_raw IE
#define GLSL_a_yWithFlags "VD"
#define GLSL_a_yWithFlags_raw VD
#define GLSL_atlasFillFragmentMain "BF"
#define GLSL_atlasFillFragmentMain_raw BF
#define GLSL_atlasRenderTexture "DF"
#define GLSL_atlasRenderTexture_raw DF
#define GLSL_atlasResolveVertexMain "AG"
#define GLSL_atlasResolveVertexMain_raw AG
#define GLSL_atlasStrokeFragmentMain "CF"
#define GLSL_atlasStrokeFragmentMain_raw CF
#define GLSL_atlasVertexMain "ZF"
#define GLSL_atlasVertexMain_raw ZF
#define GLSL_blitFragmentMain "RE"
#define GLSL_blitFragmentMain_raw RE
#define GLSL_blitVertexMain "LF"
#define GLSL_blitVertexMain_raw LF
#define GLSL_clearColor "YE"
#define GLSL_clearColor_raw YE
#define GLSL_colorRampFragmentMain "NF"
#define GLSL_colorRampFragmentMain_raw NF
#define GLSL_colorRampVertexMain "MF"
#define GLSL_colorRampVertexMain_raw MF
#define GLSL_contourBuffer "ID"
#define GLSL_contourBuffer_raw ID
#define GLSL_drawFragmentMain "IB"
#define GLSL_drawFragmentMain_raw IB
#define GLSL_drawVertexMain "FC"
#define GLSL_drawVertexMain_raw FC
#define GLSL_dstColorTexture "YD"
#define GLSL_dstColorTexture_raw YD
#define GLSL_featherAtlasTexture "FD"
#define GLSL_featherAtlasTexture_raw FD
#define GLSL_gaussianIntegralTexture "YC"
#define GLSL_gaussianIntegralTexture_raw YC
#define GLSL_gradTexture "ED"
#define GLSL_gradTexture_raw ED
#define GLSL_imageTexture "HC"
#define GLSL_imageTexture_raw HC
#define GLSL_paintAuxBuffer "QB"
#define GLSL_paintAuxBuffer_raw QB
#define GLSL_paintBuffer "DD"
#define GLSL_paintBuffer_raw DD
#define GLSL_pathBuffer "PB"
#define GLSL_pathBuffer_raw PB
#define GLSL_sourceTexture "IC"
#define GLSL_sourceTexture_raw IC
#define GLSL_stencilVertexMain "FG"
#define GLSL_stencilVertexMain_raw FG
#define GLSL_tessVertexTexture "KC"
#define GLSL_tessVertexTexture_raw KC
#define GLSL_tessellateFragmentMain "HG"
#define GLSL_tessellateFragmentMain_raw HG
#define GLSL_tessellateVertexMain "GG"
#define GLSL_tessellateVertexMain_raw GG
