#pragma once

#define GLSL_ATLAS_FEATHERED_FILL "NC"
#define GLSL_ATLAS_FEATHERED_FILL_raw NC
#define GLSL_ATLAS_FEATHERED_STROKE "SC"
#define GLSL_ATLAS_FEATHERED_STROKE_raw SC
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE "CE"
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE_raw CE
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH "AE"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH_raw AE
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE "EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE_raw EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT "BE"
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT_raw BE
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM "CF"
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM_raw CF
#define GLSL_BASE_INSTANCE_UNIFORM_NAME "FE"
#define GLSL_BASE_INSTANCE_UNIFORM_NAME_raw FE
#define GLSL_BASE_VERTEX_UNIFORM_NAME "WE"
#define GLSL_BASE_VERTEX_UNIFORM_NAME_raw WE
#define GLSL_BORROWED_COVERAGE_PASS "EC"
#define GLSL_BORROWED_COVERAGE_PASS_raw EC
#define GLSL_CLEAR_CLIP "ZF"
#define GLSL_CLEAR_CLIP_raw ZF
#define GLSL_CLEAR_COLOR "ZE"
#define GLSL_CLEAR_COLOR_raw ZE
#define GLSL_CLEAR_COVERAGE "HE"
#define GLSL_CLEAR_COVERAGE_raw HE
#define GLSL_CLOCKWISE_FILL "IE"
#define GLSL_CLOCKWISE_FILL_raw IE
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER "GD"
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER_raw GD
#define GLSL_COLOR_PLANE_IDX_OVERRIDE "QE"
#define GLSL_COLOR_PLANE_IDX_OVERRIDE_raw QE
#define GLSL_DISABLE_ADVANCED_BLEND "GG"
#define GLSL_DISABLE_ADVANCED_BLEND_raw GG
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS "SE"
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS_raw SE
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS "SF"
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS_raw SF
#define GLSL_DRAW_IMAGE "OE"
#define GLSL_DRAW_IMAGE_raw OE
#define GLSL_DRAW_IMAGE_MESH "NB"
#define GLSL_DRAW_IMAGE_MESH_raw NB
#define GLSL_DRAW_IMAGE_RECT "ED"
#define GLSL_DRAW_IMAGE_RECT_raw ED
#define GLSL_DRAW_INTERIOR_TRIANGLES "DB"
#define GLSL_DRAW_INTERIOR_TRIANGLES_raw DB
#define GLSL_DRAW_PATH "PD"
#define GLSL_DRAW_PATH_raw PD
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS "KF"
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS_raw KF
#define GLSL_DS_HAIRLINE_STROKE "BD"
#define GLSL_DS_HAIRLINE_STROKE_raw BD
#define GLSL_DS_POLAR_STROKE "AD"
#define GLSL_DS_POLAR_STROKE_raw AD
#define GLSL_ENABLE_ADVANCED_BLEND "H"
#define GLSL_ENABLE_ADVANCED_BLEND_raw H
#define GLSL_ENABLE_BASE_VERTEX "VE"
#define GLSL_ENABLE_BASE_VERTEX_raw VE
#define GLSL_ENABLE_CLIPPING "N"
#define GLSL_ENABLE_CLIPPING_raw N
#define GLSL_ENABLE_CLIP_RECT "AB"
#define GLSL_ENABLE_CLIP_RECT_raw AB
#define GLSL_ENABLE_DITHER "OB"
#define GLSL_ENABLE_DITHER_raw OB
#define GLSL_ENABLE_EVEN_ODD "XC"
#define GLSL_ENABLE_EVEN_ODD_raw XC
#define GLSL_ENABLE_FEATHER "HB"
#define GLSL_ENABLE_FEATHER_raw HB
#define GLSL_ENABLE_HSL_BLEND_MODES "FC"
#define GLSL_ENABLE_HSL_BLEND_MODES_raw FC
#define GLSL_ENABLE_INSTANCE_INDEX "EE"
#define GLSL_ENABLE_INSTANCE_INDEX_raw EE
#define GLSL_ENABLE_KHR_BLEND "NE"
#define GLSL_ENABLE_KHR_BLEND_raw NE
#define GLSL_ENABLE_MIN_16_PRECISION "XE"
#define GLSL_ENABLE_MIN_16_PRECISION_raw XE
#define GLSL_ENABLE_MODULATED_IMAGE "GB"
#define GLSL_ENABLE_MODULATED_IMAGE_raw GB
#define GLSL_ENABLE_NESTED_CLIPPING "DD"
#define GLSL_ENABLE_NESTED_CLIPPING_raw DD
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS "YE"
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS_raw YE
#define GLSL_ENABLE_RENDER_TARGET_BOTTOM_UP "SD"
#define GLSL_ENABLE_RENDER_TARGET_BOTTOM_UP_raw SD
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE "RC"
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE_raw RC
#define GLSL_FEATHER_ATLAS_BLIT "FB"
#define GLSL_FEATHER_ATLAS_BLIT_raw FB
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT "U"
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT_raw U
#define GLSL_FRAGMENT "EB"
#define GLSL_FRAGMENT_raw EB
#define GLSL_FlushUniforms "VB"
#define GLSL_FlushUniforms_raw VB
#define GLSL_GLSL_VERSION "KC"
#define GLSL_GLSL_VERSION_raw KC
#define GLSL_GL_RENDERER_MALI "QF"
#define GLSL_GL_RENDERER_MALI_raw QF
#define GLSL_INITIALIZE_PLS "PE"
#define GLSL_INITIALIZE_PLS_raw PE
#define GLSL_INPUT_ATTACHMENT_BINDING "JF"
#define GLSL_INPUT_ATTACHMENT_BINDING_raw JF
#define GLSL_LOAD_COLOR "BF"
#define GLSL_LOAD_COLOR_raw BF
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE "UD"
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE_raw UD
#define GLSL_MSAA_DST_COLOR "TE"
#define GLSL_MSAA_DST_COLOR_raw TE
#define GLSL_NEEDS_CLIP_DISTANCE "HF"
#define GLSL_NEEDS_CLIP_DISTANCE_raw HF
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND "LF"
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND_raw LF
#define GLSL_NEEDS_USHORT_DEFINE "GF"
#define GLSL_NEEDS_USHORT_DEFINE_raw GF
#define GLSL_NESTED_CLIP_UPDATE_ONLY "MD"
#define GLSL_NESTED_CLIP_UPDATE_ONLY_raw MD
#define GLSL_NO_VARYING "IF"
#define GLSL_NO_VARYING_raw IF
#define GLSL_OPTIONALLY_FLAT "MB"
#define GLSL_OPTIONALLY_FLAT_raw MB
#define GLSL_PLS_BLEND_SRC_OVER "UC"
#define GLSL_PLS_BLEND_SRC_OVER_raw UC
#define GLSL_PLS_IMPL_ANGLE "EXPORTED_PLS_IMPL_ANGLE"
#define GLSL_PLS_IMPL_ANGLE_raw EXPORTED_PLS_IMPL_ANGLE
#define GLSL_PLS_IMPL_DEVICE_BUFFER "XF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_raw XF
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED "YF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED_raw YF
#define GLSL_PLS_IMPL_EXT_NATIVE "UF"
#define GLSL_PLS_IMPL_EXT_NATIVE_raw UF
#define GLSL_PLS_IMPL_NONE "WF"
#define GLSL_PLS_IMPL_NONE_raw WF
#define GLSL_PLS_IMPL_STORAGE_BUFFER "LD"
#define GLSL_PLS_IMPL_STORAGE_BUFFER_raw LD
#define GLSL_PLS_IMPL_STORAGE_TEXTURE "DE"
#define GLSL_PLS_IMPL_STORAGE_TEXTURE_raw DE
#define GLSL_PLS_IMPL_SUBPASS_LOAD "VF"
#define GLSL_PLS_IMPL_SUBPASS_LOAD_raw VF
#define GLSL_POST_INVERT_Y "MC"
#define GLSL_POST_INVERT_Y_raw MC
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC "QB"
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC_raw QB
#define GLSL_RENDER_MODE_DEPTH_STENCIL "CB"
#define GLSL_RENDER_MODE_DEPTH_STENCIL_raw CB
#define GLSL_RESOLVE_PLS "VC"
#define GLSL_RESOLVE_PLS_raw VC
#define GLSL_SOURCE_TEXTURE_MSAA "VD"
#define GLSL_SOURCE_TEXTURE_MSAA_raw VD
#define GLSL_STORE_COLOR "GE"
#define GLSL_STORE_COLOR_raw GE
#define GLSL_STORE_COLOR_CLEAR "TD"
#define GLSL_STORE_COLOR_CLEAR_raw TD
#define GLSL_SUPPORTS_MSAA_DST_TEXEL_FETCH "DG"
#define GLSL_SUPPORTS_MSAA_DST_TEXEL_FETCH_raw DG
#define GLSL_SUPPORTS_SUBPASS_LOAD "CG"
#define GLSL_SUPPORTS_SUBPASS_LOAD_raw CG
#define GLSL_SV_INSTANCE_ID_INCLUDES_BASE "EG"
#define GLSL_SV_INSTANCE_ID_INCLUDES_BASE_raw EG
#define GLSL_SV_VERTEX_ID_INCLUDES_BASE "FG"
#define GLSL_SV_VERTEX_ID_INCLUDES_BASE_raw FG
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA "MF"
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA_raw MF
#define GLSL_TARGET_SPIRV "DC"
#define GLSL_TARGET_SPIRV_raw DC
#define GLSL_TARGET_WGSL "UE"
#define GLSL_TARGET_WGSL_raw UE
#define GLSL_USE_FILTERING "ID"
#define GLSL_USE_FILTERING_raw ID
#define GLSL_USE_WEBGPU_SAMPLERS "RF"
#define GLSL_USE_WEBGPU_SAMPLERS_raw RF
#define GLSL_USING_PLS_STORAGE_TEXTURES "TF"
#define GLSL_USING_PLS_STORAGE_TEXTURES_raw TF
#define GLSL_VERTEX "BB"
#define GLSL_VERTEX_raw BB
#define GLSL_VULKAN_VENDOR_ARM "JD"
#define GLSL_VULKAN_VENDOR_ARM_raw JD
#define GLSL_a_args "WB"
#define GLSL_a_args_raw WB
#define GLSL_a_color0 "YD"
#define GLSL_a_color0_raw YD
#define GLSL_a_color1 "ZD"
#define GLSL_a_color1_raw ZD
#define GLSL_a_contourIDWithFlags "ME"
#define GLSL_a_contourIDWithFlags_raw ME
#define GLSL_a_imageDrawBlendMode "CC"
#define GLSL_a_imageDrawBlendMode_raw CC
#define GLSL_a_imageDrawClipID "BC"
#define GLSL_a_imageDrawClipID_raw BC
#define GLSL_a_imageDrawClipRectInverseMatrix "SB"
#define GLSL_a_imageDrawClipRectInverseMatrix_raw SB
#define GLSL_a_imageDrawModulatedColor "AC"
#define GLSL_a_imageDrawModulatedColor_raw AC
#define GLSL_a_imageDrawTranslates "PB"
#define GLSL_a_imageDrawTranslates_raw PB
#define GLSL_a_imageDrawViewMatrix "ZB"
#define GLSL_a_imageDrawViewMatrix_raw ZB
#define GLSL_a_imageDrawZIndex "LC"
#define GLSL_a_imageDrawZIndex_raw LC
#define GLSL_a_imageMeshUVTransform "HC"
#define GLSL_a_imageMeshUVTransform_raw HC
#define GLSL_a_imageRectGradientMatrix "RD"
#define GLSL_a_imageRectGradientMatrix_raw RD
#define GLSL_a_imageRectImageAndGradientTranslates "FD"
#define GLSL_a_imageRectImageAndGradientTranslates_raw FD
#define GLSL_a_imageRectImageMatrix "QD"
#define GLSL_a_imageRectImageMatrix_raw QD
#define GLSL_a_imageRectPackedGradientData "OC"
#define GLSL_a_imageRectPackedGradientData_raw OC
#define GLSL_a_imageRectVertex "GC"
#define GLSL_a_imageRectVertex_raw GC
#define GLSL_a_joinTan_and_ys "TC"
#define GLSL_a_joinTan_and_ys_raw TC
#define GLSL_a_mirroredVertexData "YB"
#define GLSL_a_mirroredVertexData_raw YB
#define GLSL_a_p0p1_ "ND"
#define GLSL_a_p0p1__raw ND
#define GLSL_a_p2p3_ "OD"
#define GLSL_a_p2p3__raw OD
#define GLSL_a_patchVertexData "XB"
#define GLSL_a_patchVertexData_raw XB
#define GLSL_a_position "PC"
#define GLSL_a_position_raw PC
#define GLSL_a_reflectionX0X1 "KE"
#define GLSL_a_reflectionX0X1_raw KE
#define GLSL_a_segmentCounts "LE"
#define GLSL_a_segmentCounts_raw LE
#define GLSL_a_span "JC"
#define GLSL_a_span_raw JC
#define GLSL_a_spanX "WD"
#define GLSL_a_spanX_raw WD
#define GLSL_a_texCoord "QC"
#define GLSL_a_texCoord_raw QC
#define GLSL_a_triangleVertex "LB"
#define GLSL_a_triangleVertex_raw LB
#define GLSL_a_x0x1 "JE"
#define GLSL_a_x0x1_raw JE
#define GLSL_a_yWithFlags "XD"
#define GLSL_a_yWithFlags_raw XD
#define GLSL_atlasFillFragmentMain "DF"
#define GLSL_atlasFillFragmentMain_raw DF
#define GLSL_atlasRenderTexture "FF"
#define GLSL_atlasRenderTexture_raw FF
#define GLSL_atlasResolveVertexMain "BG"
#define GLSL_atlasResolveVertexMain_raw BG
#define GLSL_atlasStrokeFragmentMain "EF"
#define GLSL_atlasStrokeFragmentMain_raw EF
#define GLSL_atlasVertexMain "AG"
#define GLSL_atlasVertexMain_raw AG
#define GLSL_blitFragmentMain "RE"
#define GLSL_blitFragmentMain_raw RE
#define GLSL_blitVertexMain "NF"
#define GLSL_blitVertexMain_raw NF
#define GLSL_clearColor "AF"
#define GLSL_clearColor_raw AF
#define GLSL_colorRampFragmentMain "PF"
#define GLSL_colorRampFragmentMain_raw PF
#define GLSL_colorRampVertexMain "OF"
#define GLSL_colorRampVertexMain_raw OF
#define GLSL_contourBuffer "CD"
#define GLSL_contourBuffer_raw CD
#define GLSL_drawFragmentMain "IB"
#define GLSL_drawFragmentMain_raw IB
#define GLSL_drawVertexMain "RB"
#define GLSL_drawVertexMain_raw RB
#define GLSL_dstColorTexture "KD"
#define GLSL_dstColorTexture_raw KD
#define GLSL_featherAtlasTexture "HD"
#define GLSL_featherAtlasTexture_raw HD
#define GLSL_gaussianIntegralTexture "ZC"
#define GLSL_gaussianIntegralTexture_raw ZC
#define GLSL_gradTexture "YC"
#define GLSL_gradTexture_raw YC
#define GLSL_imageTexture "TB"
#define GLSL_imageTexture_raw TB
#define GLSL_paintAuxBuffer "JB"
#define GLSL_paintAuxBuffer_raw JB
#define GLSL_paintBuffer "WC"
#define GLSL_paintBuffer_raw WC
#define GLSL_pathBuffer "KB"
#define GLSL_pathBuffer_raw KB
#define GLSL_sourceTexture "IC"
#define GLSL_sourceTexture_raw IC
#define GLSL_stencilVertexMain "HG"
#define GLSL_stencilVertexMain_raw HG
#define GLSL_tessVertexTexture "UB"
#define GLSL_tessVertexTexture_raw UB
#define GLSL_tessellateFragmentMain "JG"
#define GLSL_tessellateFragmentMain_raw JG
#define GLSL_tessellateVertexMain "IG"
#define GLSL_tessellateVertexMain_raw IG
