#pragma once

#define GLSL_ATLAS_FEATHERED_FILL "NC"
#define GLSL_ATLAS_FEATHERED_FILL_raw NC
#define GLSL_ATLAS_FEATHERED_STROKE "TC"
#define GLSL_ATLAS_FEATHERED_STROKE_raw TC
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE "VD"
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE_raw VD
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH "TD"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH_raw TD
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE "EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE_raw EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT "UD"
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT_raw UD
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM "TE"
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM_raw TE
#define GLSL_BASE_INSTANCE_UNIFORM_NAME "YD"
#define GLSL_BASE_INSTANCE_UNIFORM_NAME_raw YD
#define GLSL_BORROWED_COVERAGE_PASS "EC"
#define GLSL_BORROWED_COVERAGE_PASS_raw EC
#define GLSL_CLEAR_CLIP "QF"
#define GLSL_CLEAR_CLIP_raw QF
#define GLSL_CLEAR_COLOR "QE"
#define GLSL_CLEAR_COLOR_raw QE
#define GLSL_CLEAR_COVERAGE "AE"
#define GLSL_CLEAR_COVERAGE_raw AE
#define GLSL_CLOCKWISE_FILL "BE"
#define GLSL_CLOCKWISE_FILL_raw BE
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER "ZC"
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER_raw ZC
#define GLSL_COLOR_PLANE_IDX_OVERRIDE "JE"
#define GLSL_COLOR_PLANE_IDX_OVERRIDE_raw JE
#define GLSL_DISABLE_ADVANCED_BLEND "UF"
#define GLSL_DISABLE_ADVANCED_BLEND_raw UF
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS "LE"
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS_raw LE
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS "JF"
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS_raw JF
#define GLSL_DRAW_IMAGE "HE"
#define GLSL_DRAW_IMAGE_raw HE
#define GLSL_DRAW_IMAGE_MESH "OB"
#define GLSL_DRAW_IMAGE_MESH_raw OB
#define GLSL_DRAW_IMAGE_RECT "JD"
#define GLSL_DRAW_IMAGE_RECT_raw JD
#define GLSL_DRAW_INTERIOR_TRIANGLES "EB"
#define GLSL_DRAW_INTERIOR_TRIANGLES_raw EB
#define GLSL_DRAW_PATH "ID"
#define GLSL_DRAW_PATH_raw ID
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS "AF"
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS_raw AF
#define GLSL_ENABLE_ADVANCED_BLEND "AB"
#define GLSL_ENABLE_ADVANCED_BLEND_raw AB
#define GLSL_ENABLE_CLIPPING "I"
#define GLSL_ENABLE_CLIPPING_raw I
#define GLSL_ENABLE_CLIP_RECT "BB"
#define GLSL_ENABLE_CLIP_RECT_raw BB
#define GLSL_ENABLE_DITHER "LB"
#define GLSL_ENABLE_DITHER_raw LB
#define GLSL_ENABLE_EVEN_ODD "WC"
#define GLSL_ENABLE_EVEN_ODD_raw WC
#define GLSL_ENABLE_FEATHER "HB"
#define GLSL_ENABLE_FEATHER_raw HB
#define GLSL_ENABLE_HSL_BLEND_MODES "FC"
#define GLSL_ENABLE_HSL_BLEND_MODES_raw FC
#define GLSL_ENABLE_INSTANCE_INDEX "NE"
#define GLSL_ENABLE_INSTANCE_INDEX_raw NE
#define GLSL_ENABLE_KHR_BLEND "GE"
#define GLSL_ENABLE_KHR_BLEND_raw GE
#define GLSL_ENABLE_MIN_16_PRECISION "OE"
#define GLSL_ENABLE_MIN_16_PRECISION_raw OE
#define GLSL_ENABLE_NESTED_CLIPPING "YC"
#define GLSL_ENABLE_NESTED_CLIPPING_raw YC
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS "PE"
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS_raw PE
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE "SC"
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE_raw SC
#define GLSL_FEATHER_ATLAS_BLIT "FB"
#define GLSL_FEATHER_ATLAS_BLIT_raw FB
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT "Q"
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT_raw Q
#define GLSL_FRAGMENT "GB"
#define GLSL_FRAGMENT_raw GB
#define GLSL_FRAMEBUFFER_BOTTOM_UP "ZF"
#define GLSL_FRAMEBUFFER_BOTTOM_UP_raw ZF
#define GLSL_FlushUniforms "CC"
#define GLSL_FlushUniforms_raw CC
#define GLSL_GLSL_VERSION "MC"
#define GLSL_GLSL_VERSION_raw MC
#define GLSL_GL_RENDERER_MALI "HF"
#define GLSL_GL_RENDERER_MALI_raw HF
#define GLSL_INITIALIZE_PLS "IE"
#define GLSL_INITIALIZE_PLS_raw IE
#define GLSL_INPUT_ATTACHMENT_BINDING "ZE"
#define GLSL_INPUT_ATTACHMENT_BINDING_raw ZE
#define GLSL_LOAD_COLOR "SE"
#define GLSL_LOAD_COLOR_raw SE
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE "MD"
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE_raw MD
#define GLSL_NEEDS_CLIP_DISTANCE "XE"
#define GLSL_NEEDS_CLIP_DISTANCE_raw XE
#define GLSL_NEEDS_GAMMA_CORRECTION "BC"
#define GLSL_NEEDS_GAMMA_CORRECTION_raw BC
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND "BF"
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND_raw BF
#define GLSL_NESTED_CLIP_UPDATE_ONLY "FD"
#define GLSL_NESTED_CLIP_UPDATE_ONLY_raw FD
#define GLSL_NEVER_GENERATE_PREMULTIPLIED_PAINT_COLORS "YF"
#define GLSL_NEVER_GENERATE_PREMULTIPLIED_PAINT_COLORS_raw YF
#define GLSL_NO_VARYING "YE"
#define GLSL_NO_VARYING_raw YE
#define GLSL_OPTIONALLY_FLAT "MB"
#define GLSL_OPTIONALLY_FLAT_raw MB
#define GLSL_PLS_BLEND_SRC_OVER "VC"
#define GLSL_PLS_BLEND_SRC_OVER_raw VC
#define GLSL_PLS_IMPL_ANGLE "EXPORTED_PLS_IMPL_ANGLE"
#define GLSL_PLS_IMPL_ANGLE_raw EXPORTED_PLS_IMPL_ANGLE
#define GLSL_PLS_IMPL_DEVICE_BUFFER "OF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_raw OF
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED "PF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED_raw PF
#define GLSL_PLS_IMPL_EXT_NATIVE "LF"
#define GLSL_PLS_IMPL_EXT_NATIVE_raw LF
#define GLSL_PLS_IMPL_NONE "NF"
#define GLSL_PLS_IMPL_NONE_raw NF
#define GLSL_PLS_IMPL_STORAGE_BUFFER "WD"
#define GLSL_PLS_IMPL_STORAGE_BUFFER_raw WD
#define GLSL_PLS_IMPL_STORAGE_TEXTURE "XD"
#define GLSL_PLS_IMPL_STORAGE_TEXTURE_raw XD
#define GLSL_PLS_IMPL_SUBPASS_LOAD "MF"
#define GLSL_PLS_IMPL_SUBPASS_LOAD_raw MF
#define GLSL_POST_INVERT_Y "RC"
#define GLSL_POST_INVERT_Y_raw RC
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC "SB"
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC_raw SB
#define GLSL_RENDER_MODE_MSAA "CB"
#define GLSL_RENDER_MODE_MSAA_raw CB
#define GLSL_RESOLVE_PLS "QC"
#define GLSL_RESOLVE_PLS_raw QC
#define GLSL_SOURCE_TEXTURE_MSAA "ND"
#define GLSL_SOURCE_TEXTURE_MSAA_raw ND
#define GLSL_STORE_COLOR "ZD"
#define GLSL_STORE_COLOR_raw ZD
#define GLSL_STORE_COLOR_CLEAR "LD"
#define GLSL_STORE_COLOR_CLEAR_raw LD
#define GLSL_SUPPORTS_SUBPASS_LOAD "TF"
#define GLSL_SUPPORTS_SUBPASS_LOAD_raw TF
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA "CF"
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA_raw CF
#define GLSL_TARGET_SPIRV "DC"
#define GLSL_TARGET_SPIRV_raw DC
#define GLSL_TARGET_WGSL "ME"
#define GLSL_TARGET_WGSL_raw ME
#define GLSL_TESS_TEXTURE_FLOATING_POINT "GF"
#define GLSL_TESS_TEXTURE_FLOATING_POINT_raw GF
#define GLSL_USE_FILTERING "CD"
#define GLSL_USE_FILTERING_raw CD
#define GLSL_USE_WEBGPU_SAMPLERS "IF"
#define GLSL_USE_WEBGPU_SAMPLERS_raw IF
#define GLSL_USING_PLS_STORAGE_TEXTURES "KF"
#define GLSL_USING_PLS_STORAGE_TEXTURES_raw KF
#define GLSL_VERTEX "DB"
#define GLSL_VERTEX_raw DB
#define GLSL_VULKAN_VENDOR_ARM "DD"
#define GLSL_VULKAN_VENDOR_ARM_raw DD
#define GLSL_a_args "TB"
#define GLSL_a_args_raw TB
#define GLSL_a_color0 "QD"
#define GLSL_a_color0_raw QD
#define GLSL_a_color1 "RD"
#define GLSL_a_color1_raw RD
#define GLSL_a_contourIDWithFlags "FE"
#define GLSL_a_contourIDWithFlags_raw FE
#define GLSL_a_imageDrawBlendMode "ZB"
#define GLSL_a_imageDrawBlendMode_raw ZB
#define GLSL_a_imageDrawClipID "YB"
#define GLSL_a_imageDrawClipID_raw YB
#define GLSL_a_imageDrawClipRectInverseMatrix "QB"
#define GLSL_a_imageDrawClipRectInverseMatrix_raw QB
#define GLSL_a_imageDrawOpacity "XB"
#define GLSL_a_imageDrawOpacity_raw XB
#define GLSL_a_imageDrawPacked "IB"
#define GLSL_a_imageDrawPacked_raw IB
#define GLSL_a_imageDrawTranslates "NB"
#define GLSL_a_imageDrawTranslates_raw NB
#define GLSL_a_imageDrawViewMatrix "WB"
#define GLSL_a_imageDrawViewMatrix_raw WB
#define GLSL_a_imageDrawZIndex "AC"
#define GLSL_a_imageDrawZIndex_raw AC
#define GLSL_a_imageRectVertex "HC"
#define GLSL_a_imageRectVertex_raw HC
#define GLSL_a_joinTan_and_ys "UC"
#define GLSL_a_joinTan_and_ys_raw UC
#define GLSL_a_mirroredVertexData "VB"
#define GLSL_a_mirroredVertexData_raw VB
#define GLSL_a_p0p1_ "GD"
#define GLSL_a_p0p1__raw GD
#define GLSL_a_p2p3_ "HD"
#define GLSL_a_p2p3__raw HD
#define GLSL_a_patchVertexData "UB"
#define GLSL_a_patchVertexData_raw UB
#define GLSL_a_position "OC"
#define GLSL_a_position_raw OC
#define GLSL_a_reflectionX0X1 "DE"
#define GLSL_a_reflectionX0X1_raw DE
#define GLSL_a_segmentCounts "EE"
#define GLSL_a_segmentCounts_raw EE
#define GLSL_a_span "KC"
#define GLSL_a_span_raw KC
#define GLSL_a_spanX "OD"
#define GLSL_a_spanX_raw OD
#define GLSL_a_texCoord "PC"
#define GLSL_a_texCoord_raw PC
#define GLSL_a_triangleVertex "KB"
#define GLSL_a_triangleVertex_raw KB
#define GLSL_a_x0x1 "CE"
#define GLSL_a_x0x1_raw CE
#define GLSL_a_yWithFlags "PD"
#define GLSL_a_yWithFlags_raw PD
#define GLSL_atlasFillFragmentMain "UE"
#define GLSL_atlasFillFragmentMain_raw UE
#define GLSL_atlasRenderTexture "WE"
#define GLSL_atlasRenderTexture_raw WE
#define GLSL_atlasResolveVertexMain "SF"
#define GLSL_atlasResolveVertexMain_raw SF
#define GLSL_atlasStrokeFragmentMain "VE"
#define GLSL_atlasStrokeFragmentMain_raw VE
#define GLSL_atlasVertexMain "RF"
#define GLSL_atlasVertexMain_raw RF
#define GLSL_blitFragmentMain "KE"
#define GLSL_blitFragmentMain_raw KE
#define GLSL_blitVertexMain "DF"
#define GLSL_blitVertexMain_raw DF
#define GLSL_clearColor "RE"
#define GLSL_clearColor_raw RE
#define GLSL_colorRampFragmentMain "FF"
#define GLSL_colorRampFragmentMain_raw FF
#define GLSL_colorRampVertexMain "EF"
#define GLSL_colorRampVertexMain_raw EF
#define GLSL_contourBuffer "ED"
#define GLSL_contourBuffer_raw ED
#define GLSL_drawFragmentMain "JB"
#define GLSL_drawFragmentMain_raw JB
#define GLSL_drawVertexMain "GC"
#define GLSL_drawVertexMain_raw GC
#define GLSL_dstColorTexture "SD"
#define GLSL_dstColorTexture_raw SD
#define GLSL_featherAtlasTexture "BD"
#define GLSL_featherAtlasTexture_raw BD
#define GLSL_gaussianIntegralTexture "XC"
#define GLSL_gaussianIntegralTexture_raw XC
#define GLSL_gradTexture "KD"
#define GLSL_gradTexture_raw KD
#define GLSL_imageTexture "IC"
#define GLSL_imageTexture_raw IC
#define GLSL_paintAuxBuffer "RB"
#define GLSL_paintAuxBuffer_raw RB
#define GLSL_paintBuffer "AD"
#define GLSL_paintBuffer_raw AD
#define GLSL_pathBuffer "PB"
#define GLSL_pathBuffer_raw PB
#define GLSL_sourceTexture "JC"
#define GLSL_sourceTexture_raw JC
#define GLSL_stencilVertexMain "VF"
#define GLSL_stencilVertexMain_raw VF
#define GLSL_tessVertexTexture "LC"
#define GLSL_tessVertexTexture_raw LC
#define GLSL_tessellateFragmentMain "XF"
#define GLSL_tessellateFragmentMain_raw XF
#define GLSL_tessellateVertexMain "WF"
#define GLSL_tessellateVertexMain_raw WF
