#pragma once

#define GLSL_ATLAS_FEATHERED_FILL "OC"
#define GLSL_ATLAS_FEATHERED_FILL_raw OC
#define GLSL_ATLAS_FEATHERED_STROKE "UC"
#define GLSL_ATLAS_FEATHERED_STROKE_raw UC
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE "BE"
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE_raw BE
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH "ZD"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH_raw ZD
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE "EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE_raw EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT "AE"
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT_raw AE
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM "BF"
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM_raw BF
#define GLSL_BASE_INSTANCE_UNIFORM_NAME "EE"
#define GLSL_BASE_INSTANCE_UNIFORM_NAME_raw EE
#define GLSL_BASE_VERTEX_UNIFORM_NAME "VE"
#define GLSL_BASE_VERTEX_UNIFORM_NAME_raw VE
#define GLSL_BORROWED_COVERAGE_PASS "FC"
#define GLSL_BORROWED_COVERAGE_PASS_raw FC
#define GLSL_CLEAR_CLIP "YF"
#define GLSL_CLEAR_CLIP_raw YF
#define GLSL_CLEAR_COLOR "YE"
#define GLSL_CLEAR_COLOR_raw YE
#define GLSL_CLEAR_COVERAGE "GE"
#define GLSL_CLEAR_COVERAGE_raw GE
#define GLSL_CLOCKWISE_FILL "HE"
#define GLSL_CLOCKWISE_FILL_raw HE
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER "ED"
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER_raw ED
#define GLSL_COLOR_PLANE_IDX_OVERRIDE "PE"
#define GLSL_COLOR_PLANE_IDX_OVERRIDE_raw PE
#define GLSL_DISABLE_ADVANCED_BLEND "FG"
#define GLSL_DISABLE_ADVANCED_BLEND_raw FG
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS "RE"
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS_raw RE
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS "RF"
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS_raw RF
#define GLSL_DRAW_IMAGE "NE"
#define GLSL_DRAW_IMAGE_raw NE
#define GLSL_DRAW_IMAGE_MESH "NB"
#define GLSL_DRAW_IMAGE_MESH_raw NB
#define GLSL_DRAW_IMAGE_RECT "CD"
#define GLSL_DRAW_IMAGE_RECT_raw CD
#define GLSL_DRAW_INTERIOR_TRIANGLES "DB"
#define GLSL_DRAW_INTERIOR_TRIANGLES_raw DB
#define GLSL_DRAW_PATH "ND"
#define GLSL_DRAW_PATH_raw ND
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS "JF"
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS_raw JF
#define GLSL_ENABLE_ADVANCED_BLEND "O"
#define GLSL_ENABLE_ADVANCED_BLEND_raw O
#define GLSL_ENABLE_BASE_VERTEX "UE"
#define GLSL_ENABLE_BASE_VERTEX_raw UE
#define GLSL_ENABLE_CLIPPING "A"
#define GLSL_ENABLE_CLIPPING_raw A
#define GLSL_ENABLE_CLIP_RECT "AB"
#define GLSL_ENABLE_CLIP_RECT_raw AB
#define GLSL_ENABLE_DITHER "OB"
#define GLSL_ENABLE_DITHER_raw OB
#define GLSL_ENABLE_EVEN_ODD "YC"
#define GLSL_ENABLE_EVEN_ODD_raw YC
#define GLSL_ENABLE_FEATHER "HB"
#define GLSL_ENABLE_FEATHER_raw HB
#define GLSL_ENABLE_HSL_BLEND_MODES "GC"
#define GLSL_ENABLE_HSL_BLEND_MODES_raw GC
#define GLSL_ENABLE_INSTANCE_INDEX "DE"
#define GLSL_ENABLE_INSTANCE_INDEX_raw DE
#define GLSL_ENABLE_KHR_BLEND "ME"
#define GLSL_ENABLE_KHR_BLEND_raw ME
#define GLSL_ENABLE_MIN_16_PRECISION "WE"
#define GLSL_ENABLE_MIN_16_PRECISION_raw WE
#define GLSL_ENABLE_MODULATED_IMAGE "GB"
#define GLSL_ENABLE_MODULATED_IMAGE_raw GB
#define GLSL_ENABLE_NESTED_CLIPPING "BD"
#define GLSL_ENABLE_NESTED_CLIPPING_raw BD
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS "XE"
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS_raw XE
#define GLSL_ENABLE_RENDER_TARGET_BOTTOM_UP "QD"
#define GLSL_ENABLE_RENDER_TARGET_BOTTOM_UP_raw QD
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE "TC"
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE_raw TC
#define GLSL_FEATHER_ATLAS_BLIT "FB"
#define GLSL_FEATHER_ATLAS_BLIT_raw FB
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT "V"
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT_raw V
#define GLSL_FRAGMENT "EB"
#define GLSL_FRAGMENT_raw EB
#define GLSL_FlushUniforms "UB"
#define GLSL_FlushUniforms_raw UB
#define GLSL_GLSL_VERSION "LC"
#define GLSL_GLSL_VERSION_raw LC
#define GLSL_GL_RENDERER_MALI "PF"
#define GLSL_GL_RENDERER_MALI_raw PF
#define GLSL_INITIALIZE_PLS "OE"
#define GLSL_INITIALIZE_PLS_raw OE
#define GLSL_INPUT_ATTACHMENT_BINDING "IF"
#define GLSL_INPUT_ATTACHMENT_BINDING_raw IF
#define GLSL_LOAD_COLOR "AF"
#define GLSL_LOAD_COLOR_raw AF
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE "SD"
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE_raw SD
#define GLSL_MSAA_DST_COLOR "SE"
#define GLSL_MSAA_DST_COLOR_raw SE
#define GLSL_NEEDS_CLIP_DISTANCE "GF"
#define GLSL_NEEDS_CLIP_DISTANCE_raw GF
#define GLSL_NEEDS_GAMMA_CORRECTION "CC"
#define GLSL_NEEDS_GAMMA_CORRECTION_raw CC
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND "KF"
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND_raw KF
#define GLSL_NEEDS_USHORT_DEFINE "FF"
#define GLSL_NEEDS_USHORT_DEFINE_raw FF
#define GLSL_NESTED_CLIP_UPDATE_ONLY "KD"
#define GLSL_NESTED_CLIP_UPDATE_ONLY_raw KD
#define GLSL_NO_VARYING "HF"
#define GLSL_NO_VARYING_raw HF
#define GLSL_OPTIONALLY_FLAT "KB"
#define GLSL_OPTIONALLY_FLAT_raw KB
#define GLSL_PLS_BLEND_SRC_OVER "WC"
#define GLSL_PLS_BLEND_SRC_OVER_raw WC
#define GLSL_PLS_IMPL_ANGLE "EXPORTED_PLS_IMPL_ANGLE"
#define GLSL_PLS_IMPL_ANGLE_raw EXPORTED_PLS_IMPL_ANGLE
#define GLSL_PLS_IMPL_DEVICE_BUFFER "WF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_raw WF
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED "XF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED_raw XF
#define GLSL_PLS_IMPL_EXT_NATIVE "TF"
#define GLSL_PLS_IMPL_EXT_NATIVE_raw TF
#define GLSL_PLS_IMPL_NONE "VF"
#define GLSL_PLS_IMPL_NONE_raw VF
#define GLSL_PLS_IMPL_STORAGE_BUFFER "JD"
#define GLSL_PLS_IMPL_STORAGE_BUFFER_raw JD
#define GLSL_PLS_IMPL_STORAGE_TEXTURE "CE"
#define GLSL_PLS_IMPL_STORAGE_TEXTURE_raw CE
#define GLSL_PLS_IMPL_SUBPASS_LOAD "UF"
#define GLSL_PLS_IMPL_SUBPASS_LOAD_raw UF
#define GLSL_POST_INVERT_Y "NC"
#define GLSL_POST_INVERT_Y_raw NC
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC "QB"
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC_raw QB
#define GLSL_RENDER_MODE_DEPTH_STENCIL "CB"
#define GLSL_RENDER_MODE_DEPTH_STENCIL_raw CB
#define GLSL_RESOLVE_PLS "SC"
#define GLSL_RESOLVE_PLS_raw SC
#define GLSL_SOURCE_TEXTURE_MSAA "TD"
#define GLSL_SOURCE_TEXTURE_MSAA_raw TD
#define GLSL_STORE_COLOR "FE"
#define GLSL_STORE_COLOR_raw FE
#define GLSL_STORE_COLOR_CLEAR "RD"
#define GLSL_STORE_COLOR_CLEAR_raw RD
#define GLSL_SUPPORTS_MSAA_DST_TEXEL_FETCH "CG"
#define GLSL_SUPPORTS_MSAA_DST_TEXEL_FETCH_raw CG
#define GLSL_SUPPORTS_SUBPASS_LOAD "BG"
#define GLSL_SUPPORTS_SUBPASS_LOAD_raw BG
#define GLSL_SV_INSTANCE_ID_INCLUDES_BASE "DG"
#define GLSL_SV_INSTANCE_ID_INCLUDES_BASE_raw DG
#define GLSL_SV_VERTEX_ID_INCLUDES_BASE "EG"
#define GLSL_SV_VERTEX_ID_INCLUDES_BASE_raw EG
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA "LF"
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA_raw LF
#define GLSL_TARGET_SPIRV "EC"
#define GLSL_TARGET_SPIRV_raw EC
#define GLSL_TARGET_WGSL "TE"
#define GLSL_TARGET_WGSL_raw TE
#define GLSL_USE_FILTERING "HD"
#define GLSL_USE_FILTERING_raw HD
#define GLSL_USE_WEBGPU_SAMPLERS "QF"
#define GLSL_USE_WEBGPU_SAMPLERS_raw QF
#define GLSL_USING_PLS_STORAGE_TEXTURES "SF"
#define GLSL_USING_PLS_STORAGE_TEXTURES_raw SF
#define GLSL_VERTEX "BB"
#define GLSL_VERTEX_raw BB
#define GLSL_VULKAN_VENDOR_ARM "ID"
#define GLSL_VULKAN_VENDOR_ARM_raw ID
#define GLSL_a_args "VB"
#define GLSL_a_args_raw VB
#define GLSL_a_color0 "WD"
#define GLSL_a_color0_raw WD
#define GLSL_a_color1 "XD"
#define GLSL_a_color1_raw XD
#define GLSL_a_contourIDWithFlags "LE"
#define GLSL_a_contourIDWithFlags_raw LE
#define GLSL_a_imageDrawBlendMode "BC"
#define GLSL_a_imageDrawBlendMode_raw BC
#define GLSL_a_imageDrawClipID "AC"
#define GLSL_a_imageDrawClipID_raw AC
#define GLSL_a_imageDrawClipRectInverseMatrix "SB"
#define GLSL_a_imageDrawClipRectInverseMatrix_raw SB
#define GLSL_a_imageDrawModulatedColor "ZB"
#define GLSL_a_imageDrawModulatedColor_raw ZB
#define GLSL_a_imageDrawTranslates "PB"
#define GLSL_a_imageDrawTranslates_raw PB
#define GLSL_a_imageDrawViewMatrix "YB"
#define GLSL_a_imageDrawViewMatrix_raw YB
#define GLSL_a_imageDrawZIndex "MC"
#define GLSL_a_imageDrawZIndex_raw MC
#define GLSL_a_imageMeshUVTransform "IC"
#define GLSL_a_imageMeshUVTransform_raw IC
#define GLSL_a_imageRectGradientMatrix "PD"
#define GLSL_a_imageRectGradientMatrix_raw PD
#define GLSL_a_imageRectImageAndGradientTranslates "DD"
#define GLSL_a_imageRectImageAndGradientTranslates_raw DD
#define GLSL_a_imageRectImageMatrix "OD"
#define GLSL_a_imageRectImageMatrix_raw OD
#define GLSL_a_imageRectPackedGradientData "PC"
#define GLSL_a_imageRectPackedGradientData_raw PC
#define GLSL_a_imageRectVertex "HC"
#define GLSL_a_imageRectVertex_raw HC
#define GLSL_a_joinTan_and_ys "VC"
#define GLSL_a_joinTan_and_ys_raw VC
#define GLSL_a_mirroredVertexData "XB"
#define GLSL_a_mirroredVertexData_raw XB
#define GLSL_a_p0p1_ "LD"
#define GLSL_a_p0p1__raw LD
#define GLSL_a_p2p3_ "MD"
#define GLSL_a_p2p3__raw MD
#define GLSL_a_patchVertexData "WB"
#define GLSL_a_patchVertexData_raw WB
#define GLSL_a_position "QC"
#define GLSL_a_position_raw QC
#define GLSL_a_reflectionX0X1 "JE"
#define GLSL_a_reflectionX0X1_raw JE
#define GLSL_a_segmentCounts "KE"
#define GLSL_a_segmentCounts_raw KE
#define GLSL_a_span "KC"
#define GLSL_a_span_raw KC
#define GLSL_a_spanX "UD"
#define GLSL_a_spanX_raw UD
#define GLSL_a_texCoord "RC"
#define GLSL_a_texCoord_raw RC
#define GLSL_a_triangleVertex "MB"
#define GLSL_a_triangleVertex_raw MB
#define GLSL_a_x0x1 "IE"
#define GLSL_a_x0x1_raw IE
#define GLSL_a_yWithFlags "VD"
#define GLSL_a_yWithFlags_raw VD
#define GLSL_atlasFillFragmentMain "CF"
#define GLSL_atlasFillFragmentMain_raw CF
#define GLSL_atlasRenderTexture "EF"
#define GLSL_atlasRenderTexture_raw EF
#define GLSL_atlasResolveVertexMain "AG"
#define GLSL_atlasResolveVertexMain_raw AG
#define GLSL_atlasStrokeFragmentMain "DF"
#define GLSL_atlasStrokeFragmentMain_raw DF
#define GLSL_atlasVertexMain "ZF"
#define GLSL_atlasVertexMain_raw ZF
#define GLSL_blitFragmentMain "QE"
#define GLSL_blitFragmentMain_raw QE
#define GLSL_blitVertexMain "MF"
#define GLSL_blitVertexMain_raw MF
#define GLSL_clearColor "ZE"
#define GLSL_clearColor_raw ZE
#define GLSL_colorRampFragmentMain "OF"
#define GLSL_colorRampFragmentMain_raw OF
#define GLSL_colorRampVertexMain "NF"
#define GLSL_colorRampVertexMain_raw NF
#define GLSL_contourBuffer "AD"
#define GLSL_contourBuffer_raw AD
#define GLSL_drawFragmentMain "IB"
#define GLSL_drawFragmentMain_raw IB
#define GLSL_drawVertexMain "RB"
#define GLSL_drawVertexMain_raw RB
#define GLSL_dstColorTexture "YD"
#define GLSL_dstColorTexture_raw YD
#define GLSL_featherAtlasTexture "GD"
#define GLSL_featherAtlasTexture_raw GD
#define GLSL_gaussianIntegralTexture "ZC"
#define GLSL_gaussianIntegralTexture_raw ZC
#define GLSL_gradTexture "FD"
#define GLSL_gradTexture_raw FD
#define GLSL_imageTexture "DC"
#define GLSL_imageTexture_raw DC
#define GLSL_paintAuxBuffer "JB"
#define GLSL_paintAuxBuffer_raw JB
#define GLSL_paintBuffer "XC"
#define GLSL_paintBuffer_raw XC
#define GLSL_pathBuffer "LB"
#define GLSL_pathBuffer_raw LB
#define GLSL_sourceTexture "JC"
#define GLSL_sourceTexture_raw JC
#define GLSL_stencilVertexMain "GG"
#define GLSL_stencilVertexMain_raw GG
#define GLSL_tessVertexTexture "TB"
#define GLSL_tessVertexTexture_raw TB
#define GLSL_tessellateFragmentMain "IG"
#define GLSL_tessellateFragmentMain_raw IG
#define GLSL_tessellateVertexMain "HG"
#define GLSL_tessellateVertexMain_raw HG
