#pragma once

#define GLSL_ATLAS_FEATHERED_FILL "MC"
#define GLSL_ATLAS_FEATHERED_FILL_raw MC
#define GLSL_ATLAS_FEATHERED_STROKE "TC"
#define GLSL_ATLAS_FEATHERED_STROKE_raw TC
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE "AE"
#define GLSL_ATLAS_RENDER_TARGET_R32I_ATOMIC_TEXTURE_raw AE
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH "YD"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_FRAMEBUFFER_FETCH_raw YD
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE "EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE"
#define GLSL_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE_raw EXPORTED_ATLAS_RENDER_TARGET_R32UI_PLS_ANGLE
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT "ZD"
#define GLSL_ATLAS_RENDER_TARGET_R8_PLS_EXT_raw ZD
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM "ZE"
#define GLSL_ATLAS_RENDER_TARGET_RGBA8_UNORM_raw ZE
#define GLSL_BASE_INSTANCE_UNIFORM_NAME "DE"
#define GLSL_BASE_INSTANCE_UNIFORM_NAME_raw DE
#define GLSL_BORROWED_COVERAGE_PASS "CC"
#define GLSL_BORROWED_COVERAGE_PASS_raw CC
#define GLSL_CLEAR_CLIP "WF"
#define GLSL_CLEAR_CLIP_raw WF
#define GLSL_CLEAR_COLOR "WE"
#define GLSL_CLEAR_COLOR_raw WE
#define GLSL_CLEAR_COVERAGE "FE"
#define GLSL_CLEAR_COVERAGE_raw FE
#define GLSL_CLOCKWISE_FILL "GE"
#define GLSL_CLOCKWISE_FILL_raw GE
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER "BD"
#define GLSL_COALESCED_PLS_RESOLVE_AND_TRANSFER_raw BD
#define GLSL_COLOR_PLANE_IDX_OVERRIDE "PE"
#define GLSL_COLOR_PLANE_IDX_OVERRIDE_raw PE
#define GLSL_DISABLE_ADVANCED_BLEND "CG"
#define GLSL_DISABLE_ADVANCED_BLEND_raw CG
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS "RE"
#define GLSL_DISABLE_CLIP_DISTANCE_FOR_UBERSHADERS_raw RE
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS "PF"
#define GLSL_DISABLE_SHADER_STORAGE_BUFFERS_raw PF
#define GLSL_DRAW_IMAGE "NE"
#define GLSL_DRAW_IMAGE_raw NE
#define GLSL_DRAW_IMAGE_MESH "KB"
#define GLSL_DRAW_IMAGE_MESH_raw KB
#define GLSL_DRAW_IMAGE_RECT "ZC"
#define GLSL_DRAW_IMAGE_RECT_raw ZC
#define GLSL_DRAW_INTERIOR_TRIANGLES "DB"
#define GLSL_DRAW_INTERIOR_TRIANGLES_raw DB
#define GLSL_DRAW_PATH "ND"
#define GLSL_DRAW_PATH_raw ND
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS "HF"
#define GLSL_DRAW_RENDER_TARGET_UPDATE_BOUNDS_raw HF
#define GLSL_EMULATE_DYNAMIC_COLOR_WRITE_DISABLE "KD"
#define GLSL_EMULATE_DYNAMIC_COLOR_WRITE_DISABLE_raw KD
#define GLSL_ENABLE_ADVANCED_BLEND "T"
#define GLSL_ENABLE_ADVANCED_BLEND_raw T
#define GLSL_ENABLE_CLIPPING "I"
#define GLSL_ENABLE_CLIPPING_raw I
#define GLSL_ENABLE_CLIP_RECT "AB"
#define GLSL_ENABLE_CLIP_RECT_raw AB
#define GLSL_ENABLE_DITHER "LB"
#define GLSL_ENABLE_DITHER_raw LB
#define GLSL_ENABLE_EVEN_ODD "WC"
#define GLSL_ENABLE_EVEN_ODD_raw WC
#define GLSL_ENABLE_FEATHER "GB"
#define GLSL_ENABLE_FEATHER_raw GB
#define GLSL_ENABLE_HSL_BLEND_MODES "DC"
#define GLSL_ENABLE_HSL_BLEND_MODES_raw DC
#define GLSL_ENABLE_INSTANCE_INDEX "TE"
#define GLSL_ENABLE_INSTANCE_INDEX_raw TE
#define GLSL_ENABLE_KHR_BLEND "LE"
#define GLSL_ENABLE_KHR_BLEND_raw LE
#define GLSL_ENABLE_MIN_16_PRECISION "UE"
#define GLSL_ENABLE_MIN_16_PRECISION_raw UE
#define GLSL_ENABLE_MODULATED_IMAGE "IB"
#define GLSL_ENABLE_MODULATED_IMAGE_raw IB
#define GLSL_ENABLE_NESTED_CLIPPING "YC"
#define GLSL_ENABLE_NESTED_CLIPPING_raw YC
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS "VE"
#define GLSL_ENABLE_RASTERIZER_ORDERED_VIEWS_raw VE
#define GLSL_ENABLE_RENDER_TARGET_BOTTOM_UP "ME"
#define GLSL_ENABLE_RENDER_TARGET_BOTTOM_UP_raw ME
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE "SC"
#define GLSL_ENABLE_TYPED_UAV_LOAD_STORE_raw SC
#define GLSL_FEATHER_ATLAS_BLIT "FB"
#define GLSL_FEATHER_ATLAS_BLIT_raw FB
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT "Q"
#define GLSL_FIXED_FUNCTION_COLOR_OUTPUT_raw Q
#define GLSL_FRAGMENT "EB"
#define GLSL_FRAGMENT_raw EB
#define GLSL_FlushUniforms "TB"
#define GLSL_FlushUniforms_raw TB
#define GLSL_GLSL_VERSION "KC"
#define GLSL_GLSL_VERSION_raw KC
#define GLSL_GL_RENDERER_MALI "NF"
#define GLSL_GL_RENDERER_MALI_raw NF
#define GLSL_INITIALIZE_PLS "OE"
#define GLSL_INITIALIZE_PLS_raw OE
#define GLSL_INPUT_ATTACHMENT_BINDING "GF"
#define GLSL_INPUT_ATTACHMENT_BINDING_raw GF
#define GLSL_LOAD_COLOR "YE"
#define GLSL_LOAD_COLOR_raw YE
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE "RD"
#define GLSL_LOAD_COLOR_FROM_DST_TEXTURE_raw RD
#define GLSL_MSAA_DST_COLOR "SE"
#define GLSL_MSAA_DST_COLOR_raw SE
#define GLSL_NEEDS_CLIP_DISTANCE "EF"
#define GLSL_NEEDS_CLIP_DISTANCE_raw EF
#define GLSL_NEEDS_GAMMA_CORRECTION "BC"
#define GLSL_NEEDS_GAMMA_CORRECTION_raw BC
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND "IF"
#define GLSL_NEEDS_PATH_ID_CLAMP_WORKAROUND_raw IF
#define GLSL_NEEDS_USHORT_DEFINE "DF"
#define GLSL_NEEDS_USHORT_DEFINE_raw DF
#define GLSL_NESTED_CLIP_UPDATE_ONLY "JD"
#define GLSL_NESTED_CLIP_UPDATE_ONLY_raw JD
#define GLSL_NO_VARYING "FF"
#define GLSL_NO_VARYING_raw FF
#define GLSL_OPTIONALLY_FLAT "MB"
#define GLSL_OPTIONALLY_FLAT_raw MB
#define GLSL_PLS_BLEND_SRC_OVER "VC"
#define GLSL_PLS_BLEND_SRC_OVER_raw VC
#define GLSL_PLS_IMPL_ANGLE "EXPORTED_PLS_IMPL_ANGLE"
#define GLSL_PLS_IMPL_ANGLE_raw EXPORTED_PLS_IMPL_ANGLE
#define GLSL_PLS_IMPL_DEVICE_BUFFER "UF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_raw UF
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED "VF"
#define GLSL_PLS_IMPL_DEVICE_BUFFER_RASTER_ORDERED_raw VF
#define GLSL_PLS_IMPL_EXT_NATIVE "RF"
#define GLSL_PLS_IMPL_EXT_NATIVE_raw RF
#define GLSL_PLS_IMPL_NONE "TF"
#define GLSL_PLS_IMPL_NONE_raw TF
#define GLSL_PLS_IMPL_STORAGE_BUFFER "ID"
#define GLSL_PLS_IMPL_STORAGE_BUFFER_raw ID
#define GLSL_PLS_IMPL_STORAGE_TEXTURE "CE"
#define GLSL_PLS_IMPL_STORAGE_TEXTURE_raw CE
#define GLSL_PLS_IMPL_SUBPASS_LOAD "SF"
#define GLSL_PLS_IMPL_SUBPASS_LOAD_raw SF
#define GLSL_POST_INVERT_Y "RC"
#define GLSL_POST_INVERT_Y_raw RC
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC "QB"
#define GLSL_RENDER_MODE_CLOCKWISE_ATOMIC_raw QB
#define GLSL_RENDER_MODE_DEPTH_STENCIL "BB"
#define GLSL_RENDER_MODE_DEPTH_STENCIL_raw BB
#define GLSL_RESOLVE_PLS "QC"
#define GLSL_RESOLVE_PLS_raw QC
#define GLSL_SOURCE_TEXTURE_MSAA "SD"
#define GLSL_SOURCE_TEXTURE_MSAA_raw SD
#define GLSL_STORE_COLOR "EE"
#define GLSL_STORE_COLOR_raw EE
#define GLSL_STORE_COLOR_CLEAR "QD"
#define GLSL_STORE_COLOR_CLEAR_raw QD
#define GLSL_SUPPORTS_MSAA_DST_TEXEL_FETCH "AG"
#define GLSL_SUPPORTS_MSAA_DST_TEXEL_FETCH_raw AG
#define GLSL_SUPPORTS_SUBPASS_LOAD "ZF"
#define GLSL_SUPPORTS_SUBPASS_LOAD_raw ZF
#define GLSL_SV_INSTANCE_ID_INCLUDES_BASE "BG"
#define GLSL_SV_INSTANCE_ID_INCLUDES_BASE_raw BG
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA "JF"
#define GLSL_SWIZZLE_COLOR_BGRA_TO_RGBA_raw JF
#define GLSL_TARGET_SPIRV "SB"
#define GLSL_TARGET_SPIRV_raw SB
#define GLSL_TARGET_WGSL "BE"
#define GLSL_TARGET_WGSL_raw BE
#define GLSL_USE_FILTERING "FD"
#define GLSL_USE_FILTERING_raw FD
#define GLSL_USE_WEBGPU_SAMPLERS "OF"
#define GLSL_USE_WEBGPU_SAMPLERS_raw OF
#define GLSL_USING_PLS_STORAGE_TEXTURES "QF"
#define GLSL_USING_PLS_STORAGE_TEXTURES_raw QF
#define GLSL_VERTEX "CB"
#define GLSL_VERTEX_raw CB
#define GLSL_VULKAN_VENDOR_ARM "GD"
#define GLSL_VULKAN_VENDOR_ARM_raw GD
#define GLSL_a_args "UB"
#define GLSL_a_args_raw UB
#define GLSL_a_color0 "VD"
#define GLSL_a_color0_raw VD
#define GLSL_a_color1 "WD"
#define GLSL_a_color1_raw WD
#define GLSL_a_contourIDWithFlags "KE"
#define GLSL_a_contourIDWithFlags_raw KE
#define GLSL_a_imageDrawBlendMode "AC"
#define GLSL_a_imageDrawBlendMode_raw AC
#define GLSL_a_imageDrawClipID "ZB"
#define GLSL_a_imageDrawClipID_raw ZB
#define GLSL_a_imageDrawClipRectInverseMatrix "RB"
#define GLSL_a_imageDrawClipRectInverseMatrix_raw RB
#define GLSL_a_imageDrawModulatedColor "YB"
#define GLSL_a_imageDrawModulatedColor_raw YB
#define GLSL_a_imageDrawTranslates "NB"
#define GLSL_a_imageDrawTranslates_raw NB
#define GLSL_a_imageDrawViewMatrix "XB"
#define GLSL_a_imageDrawViewMatrix_raw XB
#define GLSL_a_imageDrawZIndex "LC"
#define GLSL_a_imageDrawZIndex_raw LC
#define GLSL_a_imageRectGradientMatrix "PD"
#define GLSL_a_imageRectGradientMatrix_raw PD
#define GLSL_a_imageRectImageAndGradientTranslates "AD"
#define GLSL_a_imageRectImageAndGradientTranslates_raw AD
#define GLSL_a_imageRectImageMatrix "OD"
#define GLSL_a_imageRectImageMatrix_raw OD
#define GLSL_a_imageRectPackedGradientData "NC"
#define GLSL_a_imageRectPackedGradientData_raw NC
#define GLSL_a_imageRectVertex "FC"
#define GLSL_a_imageRectVertex_raw FC
#define GLSL_a_joinTan_and_ys "UC"
#define GLSL_a_joinTan_and_ys_raw UC
#define GLSL_a_mirroredVertexData "WB"
#define GLSL_a_mirroredVertexData_raw WB
#define GLSL_a_p0p1_ "LD"
#define GLSL_a_p0p1__raw LD
#define GLSL_a_p2p3_ "MD"
#define GLSL_a_p2p3__raw MD
#define GLSL_a_patchVertexData "VB"
#define GLSL_a_patchVertexData_raw VB
#define GLSL_a_position "OC"
#define GLSL_a_position_raw OC
#define GLSL_a_reflectionX0X1 "IE"
#define GLSL_a_reflectionX0X1_raw IE
#define GLSL_a_segmentCounts "JE"
#define GLSL_a_segmentCounts_raw JE
#define GLSL_a_span "IC"
#define GLSL_a_span_raw IC
#define GLSL_a_spanX "TD"
#define GLSL_a_spanX_raw TD
#define GLSL_a_texCoord "PC"
#define GLSL_a_texCoord_raw PC
#define GLSL_a_triangleVertex "JB"
#define GLSL_a_triangleVertex_raw JB
#define GLSL_a_x0x1 "HE"
#define GLSL_a_x0x1_raw HE
#define GLSL_a_yWithFlags "UD"
#define GLSL_a_yWithFlags_raw UD
#define GLSL_atlasFillFragmentMain "AF"
#define GLSL_atlasFillFragmentMain_raw AF
#define GLSL_atlasRenderTexture "CF"
#define GLSL_atlasRenderTexture_raw CF
#define GLSL_atlasResolveVertexMain "YF"
#define GLSL_atlasResolveVertexMain_raw YF
#define GLSL_atlasStrokeFragmentMain "BF"
#define GLSL_atlasStrokeFragmentMain_raw BF
#define GLSL_atlasVertexMain "XF"
#define GLSL_atlasVertexMain_raw XF
#define GLSL_blitFragmentMain "QE"
#define GLSL_blitFragmentMain_raw QE
#define GLSL_blitVertexMain "KF"
#define GLSL_blitVertexMain_raw KF
#define GLSL_clearColor "XE"
#define GLSL_clearColor_raw XE
#define GLSL_colorRampFragmentMain "MF"
#define GLSL_colorRampFragmentMain_raw MF
#define GLSL_colorRampVertexMain "LF"
#define GLSL_colorRampVertexMain_raw LF
#define GLSL_contourBuffer "HD"
#define GLSL_contourBuffer_raw HD
#define GLSL_drawFragmentMain "HB"
#define GLSL_drawFragmentMain_raw HB
#define GLSL_drawVertexMain "EC"
#define GLSL_drawVertexMain_raw EC
#define GLSL_dstColorTexture "XD"
#define GLSL_dstColorTexture_raw XD
#define GLSL_featherAtlasTexture "ED"
#define GLSL_featherAtlasTexture_raw ED
#define GLSL_gaussianIntegralTexture "XC"
#define GLSL_gaussianIntegralTexture_raw XC
#define GLSL_gradTexture "DD"
#define GLSL_gradTexture_raw DD
#define GLSL_imageTexture "GC"
#define GLSL_imageTexture_raw GC
#define GLSL_paintAuxBuffer "PB"
#define GLSL_paintAuxBuffer_raw PB
#define GLSL_paintBuffer "CD"
#define GLSL_paintBuffer_raw CD
#define GLSL_pathBuffer "OB"
#define GLSL_pathBuffer_raw OB
#define GLSL_sourceTexture "HC"
#define GLSL_sourceTexture_raw HC
#define GLSL_stencilVertexMain "DG"
#define GLSL_stencilVertexMain_raw DG
#define GLSL_tessVertexTexture "JC"
#define GLSL_tessVertexTexture_raw JC
#define GLSL_tessellateFragmentMain "FG"
#define GLSL_tessellateFragmentMain_raw FG
#define GLSL_tessellateVertexMain "EG"
#define GLSL_tessellateVertexMain_raw EG
