#ifndef NUX_CAPI_GENERATED_H
#define NUX_CAPI_GENERATED_H

/* Generated by cbindgen. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Increment only for a breaking change to the exported C contract.
 */
#define NUX_CAPI_ABI_VERSION 3

































#define NUX_PLAYER_STEP_MAX_INPUTS (4 * 1024)

#define NUX_PLAYER_STEP_MAX_INPUT_NAME_BYTES (4 * 1024)

#define NUX_PLAYER_STEP_MAX_POINTERS (4 * 1024)

enum NuxStatus
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_STATUS_OK = 0,
  NUX_STATUS_NULL_ARGUMENT = 1,
  NUX_STATUS_IMPORT_ERROR = 2,
  NUX_STATUS_NOT_FOUND = 3,
  NUX_STATUS_RUNTIME_ERROR = 4,
  NUX_STATUS_INVALID_ARGUMENT = 5,
  NUX_STATUS_ABI_MISMATCH = 6,
  NUX_STATUS_WRONG_THREAD = 7,
  NUX_STATUS_INVALID_STRUCT_SIZE = 8,
  NUX_STATUS_HANDLE_MISMATCH = 9,
  NUX_STATUS_REENTRANT_CALL = 10,
  NUX_STATUS_LIMIT_EXCEEDED = 11,
};
#ifndef __cplusplus
typedef uint32_t NuxStatus;
#endif // __cplusplus

/**
 * Owned linear-animation occurrence selected from an artboard.
 */
enum NuxPlayerKind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_PLAYER_KIND_STATIC_ARTBOARD = 0,
  NUX_PLAYER_KIND_STATE_MACHINE = 1,
  NUX_PLAYER_KIND_LINEAR_ANIMATION = 2,
};
#ifndef __cplusplus
typedef uint32_t NuxPlayerKind;
#endif // __cplusplus

/**
 * One fixed-stride state-machine input mutation in a player step. The
 * selected value field is determined by `kind`; Trigger ignores both values.
 */
enum NuxPlayerInputKind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_PLAYER_INPUT_KIND_BOOL = 0,
  NUX_PLAYER_INPUT_KIND_NUMBER = 1,
  NUX_PLAYER_INPUT_KIND_TRIGGER = 2,
};
#ifndef __cplusplus
typedef uint32_t NuxPlayerInputKind;
#endif // __cplusplus

/**
 * Pinned C++ Scene pointer operation. Application-level cancellation policy
 * is intentionally absent: C++ exposes Down, Move, Up, and Exit.
 */
enum NuxPlayerPointerKind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_PLAYER_POINTER_KIND_DOWN = 0,
  NUX_PLAYER_POINTER_KIND_MOVE = 1,
  NUX_PLAYER_POINTER_KIND_UP = 2,
  NUX_PLAYER_POINTER_KIND_EXIT = 3,
};
#ifndef __cplusplus
typedef uint32_t NuxPlayerPointerKind;
#endif // __cplusplus

/**
 * Exact C++ HitResult strength in pointer submission order.
 */
enum NuxPlayerPointerHit
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_PLAYER_POINTER_HIT_NONE = 0,
  NUX_PLAYER_POINTER_HIT_HIT = 1,
  NUX_PLAYER_POINTER_HIT_HIT_OPAQUE = 2,
};
#ifndef __cplusplus
typedef uint32_t NuxPlayerPointerHit;
#endif // __cplusplus

enum NuxPlayerEventPropertyKind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_PLAYER_EVENT_PROPERTY_KIND_NUMBER = 0,
  NUX_PLAYER_EVENT_PROPERTY_KIND_BOOL = 1,
  NUX_PLAYER_EVENT_PROPERTY_KIND_STRING = 2,
  NUX_PLAYER_EVENT_PROPERTY_KIND_COLOR = 3,
  NUX_PLAYER_EVENT_PROPERTY_KIND_ENUM = 4,
  NUX_PLAYER_EVENT_PROPERTY_KIND_TRIGGER = 5,
};
#ifndef __cplusplus
typedef uint32_t NuxPlayerEventPropertyKind;
#endif // __cplusplus

/**
 * Owned artboard occurrence. It retains the imported [`File`] through native
 * shared ownership and therefore remains valid after its [`NuxFile`] handle
 * is released.
 */
typedef struct NuxArtboardInstance NuxArtboardInstance;

/**
 * Bounded, library-owned diagnostic/result storage.
 */
typedef struct NuxCapiResult NuxCapiResult;

typedef struct NuxFile NuxFile;

/**
 * Product-neutral selected player. This surface establishes selection,
 * ownership, and metadata; playback operations are exposed separately.
 */
typedef struct NuxPlayer NuxPlayer;

/**
 * Bounded library-owned result of one player step.
 */
typedef struct NuxPlayerStepResult NuxPlayerStepResult;

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Product-neutral native renderer. The handle owns one wgpu/Metal domain and
 * is affine to its creator thread like the other portable C handles.
 */
typedef struct NuxRenderer NuxRenderer;
#endif

/**
 * Owned state machine instance. Advance it through the
 * [`NuxArtboardInstance`] it was created from.
 */
typedef struct NuxStateMachineInstance NuxStateMachineInstance;

/**
 * Owned view-model context for driving an artboard's data binds.
 *
 * Unlike [`NuxArtboardInstance`], this handle owns a private copy of the
 * view model's values and does **not** borrow the [`NuxFile`] it came from,
 * so it participates in no liveness ordering: it may be freed before or after
 * its originating file and artboard instance. It is only meaningful when bound
 * back (via `nux_artboard_instance_bind_view_model`) to the artboard instance
 * it was created from, which must still be alive at bind time.
 */
typedef struct NuxViewModelInstance NuxViewModelInstance;

/**
 * Borrowed view of a [`RawPath`]: `verbs` holds `NuxPathVerb` values and
 * `points` holds `point_count` interleaved x,y pairs. Only valid for the
 * duration of the callback it is passed to.
 */
typedef struct NuxRawPathView {
  const uint8_t *verbs;
  size_t verb_count;
  const float *points;
  size_t point_count;
} NuxRawPathView;

/**
 * C mirror of [`ImageSampler`] using the `NuxImageWrap`/`NuxImageFilter`
 * enum values.
 */
typedef struct NuxImageSampler {
  uint8_t wrap_x;
  uint8_t wrap_y;
  uint8_t filter;
} NuxImageSampler;

/**
 * Caller-provided render vtable mirroring the nuxie-render-api traits.
 *
 * Handles are opaque `uint64_t` values chosen by the caller; `0` is passed
 * for "no object" (for example a cleared shader). Transform arguments point
 * at six floats in `[xx, yx, xy, yy, tx, ty]` order. All callbacks may be
 * NULL.
 */
typedef struct NuxRenderCallbacks {
  /**
   * Must be initialized to `sizeof(NuxRenderCallbacks)` by the caller.
   */
  uint32_t struct_size;
  void *user_data;
  uint64_t (*make_render_path)(void*, const struct NuxRawPathView*, uint8_t);
  uint64_t (*make_empty_render_path)(void*);
  uint64_t (*make_render_paint)(void*);
  uint64_t (*make_linear_gradient)(void*,
                                   float,
                                   float,
                                   float,
                                   float,
                                   const uint32_t*,
                                   const float*,
                                   size_t);
  uint64_t (*make_radial_gradient)(void*, float, float, float, const uint32_t*, const float*, size_t);
  uint64_t (*make_render_buffer)(void*, uint8_t, uint8_t, size_t);
  uint64_t (*decode_image)(void*, const uint8_t*, size_t, uint32_t*, uint32_t*);
  void (*release_render_path)(void*, uint64_t);
  void (*release_render_paint)(void*, uint64_t);
  void (*release_render_shader)(void*, uint64_t);
  void (*release_render_buffer)(void*, uint64_t);
  void (*release_render_image)(void*, uint64_t);
  void (*render_path_rewind)(void*, uint64_t);
  void (*render_path_fill_rule)(void*, uint64_t, uint8_t);
  void (*render_path_move_to)(void*, uint64_t, float, float);
  void (*render_path_line_to)(void*, uint64_t, float, float);
  void (*render_path_cubic_to)(void*, uint64_t, float, float, float, float, float, float);
  void (*render_path_close)(void*, uint64_t);
  void (*render_path_add_raw_path)(void*, uint64_t, const struct NuxRawPathView*);
  void (*render_path_add_render_path)(void*, uint64_t, uint64_t, const float*);
  void (*render_path_add_render_path_backwards)(void*, uint64_t, uint64_t, const float*);
  void (*render_paint_style)(void*, uint64_t, uint8_t);
  void (*render_paint_color)(void*, uint64_t, uint32_t);
  void (*render_paint_thickness)(void*, uint64_t, float);
  void (*render_paint_join)(void*, uint64_t, uint32_t);
  void (*render_paint_cap)(void*, uint64_t, uint32_t);
  void (*render_paint_feather)(void*, uint64_t, float);
  void (*render_paint_blend_mode)(void*, uint64_t, uint8_t);
  void (*render_paint_shader)(void*, uint64_t, uint64_t);
  void (*render_paint_invalidate_stroke)(void*, uint64_t);
  void (*render_buffer_unmap)(void*, uint64_t, const uint8_t*, size_t);
  void (*save)(void*);
  void (*restore)(void*);
  void (*transform)(void*, const float*);
  void (*draw_path)(void*, uint64_t, uint64_t);
  void (*clip_path)(void*, uint64_t);
  void (*draw_image)(void*, uint64_t, struct NuxImageSampler, uint8_t, float);
  void (*draw_image_mesh)(void*,
                          uint64_t,
                          struct NuxImageSampler,
                          uint64_t,
                          uint64_t,
                          uint64_t,
                          uint32_t,
                          uint32_t,
                          uint8_t,
                          float);
  void (*modulate_opacity)(void*, float);
} NuxRenderCallbacks;

typedef struct NuxStringView {
  const char *data;
  size_t len;
} NuxStringView;

/**
 * Caller-sized view into one owned C-ABI result. `code` and `message` remain
 * valid until the owning `NuxCapiResult` is released.
 */
typedef struct NuxCapiDiagnosticView {
  uint32_t struct_size;
  NuxStatus status;
  struct NuxStringView code;
  struct NuxStringView message;
} NuxCapiDiagnosticView;

/**
 * Immutable identity embedded into the shipped runtime binary.
 *
 * Both strings have process-static lifetime and are not NUL-terminated; C
 * callers must respect their explicit lengths.
 */
typedef struct NuxRuntimeInfo {
  /**
   * Must be initialized to `sizeof(NuxRuntimeInfo)` by the caller.
   */
  uint32_t struct_size;
  uint32_t abi_version;
  struct NuxStringView runtime_version;
  struct NuxStringView source_revision;
} NuxRuntimeInfo;

/**
 * Versioned metadata for a selected runtime-native player.
 */
typedef struct NuxPlayerInfo {
  /**
   * Must be initialized to `sizeof(NuxPlayerInfo)` by the caller.
   */
  uint32_t struct_size;
  NuxPlayerKind kind;
  /**
   * Authored index within the selected kind, or `SIZE_MAX` for static.
   */
  size_t index;
  /**
   * Copied UTF-8 metadata owned by `NuxPlayer`; valid until player free.
   */
  struct NuxStringView name;
} NuxPlayerInfo;

typedef struct NuxPlayerInputChange {
  /**
   * One of the `NuxPlayerInputKind` constants. Stored as an integer so an
   * invalid C bit pattern is rejected rather than becoming a Rust enum.
   */
  uint32_t kind;
  struct NuxStringView name;
  /**
   * Canonical C boolean encoding: exactly 0 or 1. Other values reject the
   * whole batch before mutation.
   */
  uint32_t bool_value;
  float number_value;
} NuxPlayerInputChange;

typedef struct NuxPlayerPointerEvent {
  /**
   * One of the `NuxPlayerPointerKind` constants. Invalid values are
   * rejected during whole-batch validation.
   */
  uint32_t kind;
  float x;
  float y;
  int32_t pointer_id;
  float timestamp_seconds;
} NuxPlayerPointerEvent;

/**
 * One atomic, product-neutral player operation. Input and pointer arrays use
 * ABI-v3 fixed element strides; future element layouts require a new entry
 * point rather than appending fields and silently changing array stride.
 */
typedef struct NuxPlayerStep {
  uint32_t struct_size;
  const struct NuxPlayerInputChange *inputs;
  size_t input_count;
  const struct NuxPlayerPointerEvent *pointers;
  size_t pointer_count;
  float elapsed_seconds;
} NuxPlayerStep;

/**
 * Owned reported-event projection. All string views borrow the owning step
 * result and remain valid until its successful free.
 */
typedef struct NuxPlayerEventView {
  uint32_t struct_size;
  size_t event_local_index;
  uint32_t event_core_type;
  struct NuxStringView name;
  struct NuxStringView url;
  struct NuxStringView target;
  float seconds_delay;
  size_t property_count;
} NuxPlayerEventView;

/**
 * Borrowed arbitrary bytes. Unlike `NuxStringView`, this view makes no UTF-8
 * promise. Its owner and lifetime are documented by the containing API.
 */
typedef struct NuxByteView {
  const uint8_t *data;
  size_t len;
} NuxByteView;

/**
 * Fixed projection of one typed custom Event property. Only the value field
 * selected by `kind` is meaningful.
 */
typedef struct NuxPlayerEventPropertyView {
  uint32_t struct_size;
  /**
   * One of the `NUX_PLAYER_EVENT_PROPERTY_KIND_*` constants.
   */
  uint32_t kind;
  struct NuxStringView name;
  float number_value;
  bool bool_value;
  /**
   * Exact authored/script bytes for a String property; not necessarily UTF-8.
   */
  struct NuxByteView string_value;
  uint32_t color_value;
  uint64_t integer_value;
} NuxPlayerEventPropertyView;

/**
 * Summary of one owned step result. `keep_going` is the runtime's
 * advanceAndApply continuation result; it is not a host render/scheduling
 * request.
 */
typedef struct NuxPlayerStepInfo {
  uint32_t struct_size;
  bool keep_going;
  size_t pointer_result_count;
  size_t state_change_count;
  size_t event_count;
} NuxPlayerStepInfo;

/**
 * C++ `stateChangedByIndex` projection in compressed authored-layer order.
 */
typedef struct NuxPlayerStateChangeView {
  uint32_t struct_size;
  size_t layer_index;
  /**
   * Pinned Core schema type key (`Core::typeKey`).
   */
  uint32_t state_core_type;
  /**
   * Authored Core id, or `UINT32_MAX` when absent.
   */
  uint32_t state_global_id;
} NuxPlayerStateChangeView;

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef uint32_t NuxRendererDisposition;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef uint32_t NuxRendererHealth;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef struct NuxRendererOutcome {
  /**
   * Must be initialized to `sizeof(NuxRendererOutcome)`.
   */
  uint32_t struct_size;
  NuxRendererDisposition disposition;
  NuxRendererHealth health;
  uint32_t pixel_width;
  uint32_t pixel_height;
  uint64_t draw_calls;
  uint64_t logical_flushes;
  uint64_t atomic_strategy_partitions;
} NuxRendererOutcome;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef struct NuxRendererInfo {
  /**
   * Must be initialized to `sizeof(NuxRendererInfo)`.
   */
  uint32_t struct_size;
  uint32_t pixel_width;
  uint32_t pixel_height;
  bool attached;
  NuxRendererHealth health;
  /**
   * Changes whenever reattach replaces native renderer resources.
   */
  uint64_t generation;
} NuxRendererInfo;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef uint32_t NuxMetalDrawableState;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef struct NuxMetalRenderOperation {
  /**
   * Must be initialized to `sizeof(NuxMetalRenderOperation)`.
   */
  uint32_t struct_size;
  /**
   * Swift-reported drawable availability; Rust never queries UI state.
   */
  NuxMetalDrawableState drawable_state;
  /**
   * Synchronously borrowed live `id<CAMetalDrawable>` when AVAILABLE.
   */
  void *drawable;
  /**
   * Premultiplied ARGB clear color.
   */
  uint32_t clear_color;
  /**
   * Caller-owned context consumed by `completion_callback`.
   */
  void *completion_context;
  /**
   * Both completion fields must be null or non-null together.
   */
  void (*completion_callback)(void *context);
} NuxMetalRenderOperation;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_METAL_DRAWABLE_STATE_AVAILABLE 0
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_METAL_DRAWABLE_STATE_OCCLUDED 2
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_METAL_DRAWABLE_STATE_TIMEOUT 1
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_DEVICE_LOST 7
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_NONE 0
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_OUT_OF_MEMORY 8
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_PRESENTED 1
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_RECONFIGURED 5
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_RECREATED 6
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_SKIPPED_OCCLUDED 4
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_SKIPPED_TIMEOUT 3
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_SKIPPED_ZERO_SIZE 2
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_HEALTH_DEVICE_LOST 1
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_HEALTH_FAILED 3
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_HEALTH_HEALTHY 0
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_HEALTH_OUT_OF_MEMORY 2
#endif

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Advance the artboard timeline without a state machine. `out_changed` is
 * optional and reports whether anything changed.
 */
NuxStatus nux_artboard_instance_advance(struct NuxArtboardInstance *instance,
                                        float elapsed_seconds,
                                        bool *out_changed);

/**
 * Bind `view_model` to `instance`'s own data binds and nested-artboard
 * contexts (mirrors `artboard->bindViewModelInstance(...)`). The context is
 * copied in, so call this again after mutating `view_model` to propagate the
 * change on the next advance. `view_model` must have been created from
 * `instance`.
 */
NuxStatus nux_artboard_instance_bind_view_model(struct NuxArtboardInstance *instance,
                                                const struct NuxViewModelInstance *view_model);

/**
 * Draw the artboard through the caller-provided render vtable. See
 * `NuxRenderCallbacks` for the ownership and handle contract. The first
 * draw's renderer domain is retained by the Artboard occurrence, even if that
 * draw returns an error. A different descriptor/domain returns
 * `NUX_STATUS_HANDLE_MISMATCH`; a future explicit reset can make switching
 * domains safe. Callback functions and `user_data` must remain valid until
 * the last artboard/player retaining the occurrence is freed.
 */
NuxStatus nux_artboard_instance_draw(struct NuxArtboardInstance *instance,
                                     const struct NuxRenderCallbacks *callbacks);

NuxStatus nux_artboard_instance_free(struct NuxArtboardInstance *instance);

/**
 * Instantiate the artboard at `artboard_index`. The returned occurrence
 * retains the imported file and may outlive the `NuxFile` handle.
 */
NuxStatus nux_artboard_instance_new(const struct NuxFile *file,
                                    size_t artboard_index,
                                    struct NuxArtboardInstance **out_instance);

/**
 * Instantiate the first artboard whose authored name exactly matches the
 * length-delimited UTF-8 `name`. Matching is case-sensitive and has no
 * fallback; an empty name is a valid selector.
 */
NuxStatus nux_artboard_instance_new_named(const struct NuxFile *file,
                                          struct NuxStringView name,
                                          struct NuxArtboardInstance **out_instance);

/**
 * Result-bearing exact artboard selection for consumers that need an owned
 * diagnostic on every outcome.
 */
NuxStatus nux_artboard_instance_new_named_with_result(const struct NuxFile *file,
                                                      struct NuxStringView name,
                                                      struct NuxArtboardInstance **out_instance,
                                                      struct NuxCapiResult **out_result);

uint32_t nux_capi_abi_version(void);

NuxStatus nux_capi_require_abi(uint32_t required_version);

NuxStatus nux_capi_result_diagnostic(const struct NuxCapiResult *result,
                                     struct NuxCapiDiagnosticView *out_diagnostic);

NuxStatus nux_capi_result_free(struct NuxCapiResult *result);

NuxStatus nux_capi_result_status(const struct NuxCapiResult *result, NuxStatus *out_status);

NuxStatus nux_capi_runtime_info(struct NuxRuntimeInfo *out_info);

NuxStatus nux_file_artboard_animation_count(const struct NuxFile *file,
                                            size_t index,
                                            size_t *out_count);

/**
 * Name of one of an artboard's linear animations. The returned
 * length-delimited UTF-8 view borrows `file` and expires when the file handle
 * is freed.
 */
NuxStatus nux_file_artboard_animation_name(const struct NuxFile *file,
                                           size_t artboard_index,
                                           size_t animation_index,
                                           struct NuxStringView *out_name);

NuxStatus nux_file_artboard_count(const struct NuxFile *file, size_t *out_count);

NuxStatus nux_file_artboard_name(const struct NuxFile *file,
                                 size_t index,
                                 struct NuxStringView *out_name);

NuxStatus nux_file_artboard_state_machine_count(const struct NuxFile *file,
                                                size_t index,
                                                size_t *out_count);

/**
 * Name of one of an artboard's state machines. The returned view borrows the
 * file and is valid until the file is freed.
 */
NuxStatus nux_file_artboard_state_machine_name(const struct NuxFile *file,
                                               size_t artboard_index,
                                               size_t state_machine_index,
                                               struct NuxStringView *out_name);

NuxStatus nux_file_free(struct NuxFile *file);

NuxStatus nux_file_import(const uint8_t *bytes, size_t len, struct NuxFile **out_file);

/**
 * Diagnostic import path for production consumers. `out_file` is published
 * only on success. `out_result` is always published and owns a bounded status
 * code/message until released with `nux_capi_result_free`.
 */
NuxStatus nux_file_import_with_result(const uint8_t *bytes,
                                      size_t len,
                                      struct NuxFile **out_file,
                                      struct NuxCapiResult **out_result);

NuxStatus nux_player_free(struct NuxPlayer *player);

/**
 * Read selected-player metadata into a versioned caller-owned struct.
 */
NuxStatus nux_player_info(const struct NuxPlayer *player, struct NuxPlayerInfo *out_info);

/**
 * Select the artboard's default scene using the pinned C++ order: authored
 * valid default state machine, state machine zero, animation zero, then a
 * static artboard when it has no playable animation.
 */
NuxStatus nux_player_new_default(struct NuxArtboardInstance *instance,
                                 struct NuxPlayer **out_player);

/**
 * Result-bearing default-scene selection.
 */
NuxStatus nux_player_new_default_with_result(struct NuxArtboardInstance *instance,
                                             struct NuxPlayer **out_player,
                                             struct NuxCapiResult **out_result);

/**
 * Select a linear animation by exact, case-sensitive, length-delimited UTF-8
 * name. No state-machine or index fallback is performed.
 */
NuxStatus nux_player_new_linear_animation_named(struct NuxArtboardInstance *instance,
                                                struct NuxStringView name,
                                                struct NuxPlayer **out_player);

/**
 * Result-bearing exact linear-animation selection.
 */
NuxStatus nux_player_new_linear_animation_named_with_result(struct NuxArtboardInstance *instance,
                                                            struct NuxStringView name,
                                                            struct NuxPlayer **out_player,
                                                            struct NuxCapiResult **out_result);

/**
 * Select a state machine by exact, case-sensitive, length-delimited UTF-8
 * name. No default, index-zero, or animation fallback is performed.
 */
NuxStatus nux_player_new_state_machine_named(struct NuxArtboardInstance *instance,
                                             struct NuxStringView name,
                                             struct NuxPlayer **out_player);

/**
 * Result-bearing exact state-machine selection.
 */
NuxStatus nux_player_new_state_machine_named_with_result(struct NuxArtboardInstance *instance,
                                                         struct NuxStringView name,
                                                         struct NuxPlayer **out_player,
                                                         struct NuxCapiResult **out_result);

/**
 * Explicitly select a static artboard even when it also contains authored
 * state machines or linear animations.
 */
NuxStatus nux_player_new_static(struct NuxArtboardInstance *instance,
                                struct NuxPlayer **out_player);

/**
 * Result-bearing explicit static-artboard selection.
 */
NuxStatus nux_player_new_static_with_result(struct NuxArtboardInstance *instance,
                                            struct NuxPlayer **out_player,
                                            struct NuxCapiResult **out_result);

/**
 * Apply all input changes and pointer events, then advance exactly once. The
 * operation validates the complete batch before mutation. Any unexpected
 * post-mutation failure rolls back pending script-host effects and terminally
 * poisons the shared occurrence, so no artboard/player operation can observe
 * partially committed runtime state.
 */
NuxStatus nux_player_step(struct NuxPlayer *player,
                          const struct NuxPlayerStep *step,
                          struct NuxPlayerStepResult **out_result);

NuxStatus nux_player_step_result_diagnostic(const struct NuxPlayerStepResult *result,
                                            struct NuxCapiDiagnosticView *out_diagnostic);

NuxStatus nux_player_step_result_event(const struct NuxPlayerStepResult *result,
                                       size_t index,
                                       struct NuxPlayerEventView *out_event);

NuxStatus nux_player_step_result_event_property(const struct NuxPlayerStepResult *result,
                                                size_t event_index,
                                                size_t property_index,
                                                struct NuxPlayerEventPropertyView *out_property);

NuxStatus nux_player_step_result_free(struct NuxPlayerStepResult *result);

NuxStatus nux_player_step_result_info(const struct NuxPlayerStepResult *result,
                                      struct NuxPlayerStepInfo *out_info);

NuxStatus nux_player_step_result_pointer(const struct NuxPlayerStepResult *result,
                                         size_t index,
                                         uint32_t *out_hit);

NuxStatus nux_player_step_result_state_change(const struct NuxPlayerStepResult *result,
                                              size_t index,
                                              struct NuxPlayerStateChangeView *out_change);

NuxStatus nux_player_step_result_status(const struct NuxPlayerStepResult *result,
                                        NuxStatus *out_status);

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Copies the renderer's MTLDevice with Objective-C +1 ownership.
 */
NuxStatus nux_renderer_copy_metal_device(const struct NuxRenderer *renderer,
                                         void **out_device,
                                         struct NuxCapiResult **out_result);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
NuxStatus nux_renderer_detach(struct NuxRenderer *renderer,
                              struct NuxRendererOutcome *out_outcome,
                              struct NuxCapiResult **out_result);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
NuxStatus nux_renderer_free(struct NuxRenderer *renderer);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
NuxStatus nux_renderer_info(const struct NuxRenderer *renderer,
                            struct NuxRendererInfo *out_info,
                            struct NuxCapiResult **out_result);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Creates a Metal renderer without touching UIKit, AppKit, or CAMetalLayer.
 */
NuxStatus nux_renderer_new_metal(uint32_t pixel_width,
                                 uint32_t pixel_height,
                                 struct NuxRenderer **out_renderer,
                                 struct NuxCapiResult **out_result);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Reattaches with a fresh native device domain. Players bound to an older
 * generation return HANDLE_MISMATCH until reset explicitly.
 */
NuxStatus nux_renderer_reattach(struct NuxRenderer *renderer,
                                uint32_t pixel_width,
                                uint32_t pixel_height,
                                struct NuxRendererOutcome *out_outcome,
                                struct NuxCapiResult **out_result);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Renders the player's retained artboard into a caller-acquired
 * CAMetalDrawable and schedules presentation. The drawable is borrowed only
 * until this synchronous function returns.
 */
NuxStatus nux_renderer_render_player(struct NuxRenderer *renderer,
                                     struct NuxPlayer *player,
                                     const struct NuxMetalRenderOperation *operation,
                                     struct NuxRendererOutcome *out_outcome,
                                     struct NuxCapiResult **out_result);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Drops renderer-owned resources from the player's retained artboard and
 * binds it to this renderer's current generation.
 */
NuxStatus nux_renderer_reset_player_domain(const struct NuxRenderer *renderer,
                                           struct NuxPlayer *player,
                                           struct NuxCapiResult **out_result);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
NuxStatus nux_renderer_resize(struct NuxRenderer *renderer,
                              uint32_t pixel_width,
                              uint32_t pixel_height,
                              struct NuxRendererOutcome *out_outcome,
                              struct NuxCapiResult **out_result);
#endif

/**
 * Advance the artboard while driving `state_machine`. The state machine must
 * have been created from the same artboard instance. `out_changed` is
 * optional and reports whether anything changed.
 */
NuxStatus nux_state_machine_instance_advance(struct NuxArtboardInstance *instance,
                                             struct NuxStateMachineInstance *state_machine,
                                             float elapsed_seconds,
                                             bool *out_changed);

/**
 * Fire a trigger input by name (NUL-terminated UTF-8). Returns
 * `NUX_STATUS_NOT_FOUND` when no input has that name and
 * `NUX_STATUS_INVALID_ARGUMENT` when the input is not a trigger.
 */
NuxStatus nux_state_machine_instance_fire_trigger(struct NuxStateMachineInstance *state_machine,
                                                  const char *name);

NuxStatus nux_state_machine_instance_free(struct NuxStateMachineInstance *state_machine);

/**
 * Instantiate the state machine at `state_machine_index` on the instance's
 * artboard. Free with `nux_state_machine_instance_free`.
 */
NuxStatus nux_state_machine_instance_new(struct NuxArtboardInstance *instance,
                                         size_t state_machine_index,
                                         struct NuxStateMachineInstance **out_state_machine);

/**
 * Instantiate only the artboard's authored, valid default state machine.
 * Returns `NUX_STATUS_NOT_FOUND` when no valid default was authored; this
 * function does not fall back to state-machine zero.
 */
NuxStatus nux_state_machine_instance_new_default(struct NuxArtboardInstance *instance,
                                                 struct NuxStateMachineInstance **out_state_machine);

/**
 * Instantiate the first state machine with an exact, case-sensitive authored
 * name. There is no default or cross-kind fallback.
 */
NuxStatus nux_state_machine_instance_new_named(struct NuxArtboardInstance *instance,
                                               struct NuxStringView name,
                                               struct NuxStateMachineInstance **out_state_machine);

/**
 * Deliver a pointer-down at artboard coordinates `(x, y)` to `state_machine`,
 * which must have been created from `instance`. `out_hit` is optional and
 * reports whether the event landed on a listener.
 */
NuxStatus nux_state_machine_instance_pointer_down(struct NuxArtboardInstance *instance,
                                                  struct NuxStateMachineInstance *state_machine,
                                                  float x,
                                                  float y,
                                                  bool *out_hit);

/**
 * Deliver a pointer-move at artboard coordinates `(x, y)` to `state_machine`,
 * which must have been created from `instance`. `out_hit` is optional and
 * reports whether the event landed on a listener.
 */
NuxStatus nux_state_machine_instance_pointer_move(struct NuxArtboardInstance *instance,
                                                  struct NuxStateMachineInstance *state_machine,
                                                  float x,
                                                  float y,
                                                  bool *out_hit);

/**
 * Deliver a pointer-up at artboard coordinates `(x, y)` to `state_machine`,
 * which must have been created from `instance`. `out_hit` is optional and
 * reports whether the event landed on a listener.
 */
NuxStatus nux_state_machine_instance_pointer_up(struct NuxArtboardInstance *instance,
                                                struct NuxStateMachineInstance *state_machine,
                                                float x,
                                                float y,
                                                bool *out_hit);

/**
 * Set a bool input by name (NUL-terminated UTF-8). Returns
 * `NUX_STATUS_NOT_FOUND` when no input has that name and
 * `NUX_STATUS_INVALID_ARGUMENT` when the input is not a bool.
 */
NuxStatus nux_state_machine_instance_set_bool(struct NuxStateMachineInstance *state_machine,
                                              const char *name,
                                              bool value);

/**
 * Set a number input by name (NUL-terminated UTF-8). Returns
 * `NUX_STATUS_NOT_FOUND` when no input has that name and
 * `NUX_STATUS_INVALID_ARGUMENT` when the input is not a number.
 */
NuxStatus nux_state_machine_instance_set_number(struct NuxStateMachineInstance *state_machine,
                                                const char *name,
                                                float value);

NuxStatus nux_view_model_instance_free(struct NuxViewModelInstance *view_model);

/**
 * Instantiate the artboard's view model with generated defaults (mirrors
 * `createDefaultViewModelInstance`). Returns `NUX_STATUS_NOT_FOUND` when the
 * artboard declares no view model. Free with `nux_view_model_instance_free`.
 */
NuxStatus nux_view_model_instance_new_default(const struct NuxArtboardInstance *instance,
                                              struct NuxViewModelInstance **out_view_model);

/**
 * Instantiate the artboard's view model from the source instance at
 * `instance_index` (the order the instances appear in the file). Returns
 * `NUX_STATUS_NOT_FOUND` when the artboard declares no view model or the
 * index is out of range. Free with `nux_view_model_instance_free`.
 */
NuxStatus nux_view_model_instance_new_instance(const struct NuxArtboardInstance *instance,
                                               size_t instance_index,
                                               struct NuxViewModelInstance **out_view_model);

/**
 * Set a boolean property by NUL-terminated UTF-8 name path (`/`-separated for
 * nested view models). Returns `NUX_STATUS_NOT_FOUND` when no settable
 * boolean property matches the path.
 */
NuxStatus nux_view_model_instance_set_bool(struct NuxViewModelInstance *view_model,
                                           const char *name_path,
                                           bool value);

/**
 * Set a number property by NUL-terminated UTF-8 name path (`/`-separated for
 * nested view models). Returns `NUX_STATUS_NOT_FOUND` when no settable number
 * property matches the path.
 *
 * Note: for the mutation to reach the artboard, call
 * `nux_artboard_instance_bind_view_model` after setting and before advancing.
 */
NuxStatus nux_view_model_instance_set_number(struct NuxViewModelInstance *view_model,
                                             const char *name_path,
                                             float value);

/**
 * Set a string property by NUL-terminated UTF-8 name path (`/`-separated for
 * nested view models). `value` is a NUL-terminated UTF-8 string. Returns
 * `NUX_STATUS_NOT_FOUND` when no settable string property matches the path.
 */
NuxStatus nux_view_model_instance_set_string(struct NuxViewModelInstance *view_model,
                                             const char *name_path,
                                             const char *value);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NUX_CAPI_GENERATED_H */
