#ifndef NUX_CAPI_GENERATED_H
#define NUX_CAPI_GENERATED_H

/* Generated by cbindgen. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_ASSET_ID_NONE UINT32_MAX
#endif

/**
 * Increment only for a breaking change to the exported C contract.
 */
#define NUX_CAPI_ABI_VERSION 3

#define NUX_FILE_ASSET_CATALOG_HARD_MAX 4096













#define NUX_FILE_ASSET_PROVIDER_EXTERNAL_BYTES (1 << 0)

#define NUX_FILE_ASSET_PROVIDER_IMAGE_DECODE (1 << 1)

#define NUX_HOST_COMMANDS_PER_STEP_HARD_MAX 4096

#define NUX_HOST_COMMAND_BYTES_PER_STEP_HARD_MAX ((32 * 1024) * 1024)

#define NUX_HOST_IDENTIFIER_BYTES_HARD_MAX 4096

#define NUX_HOST_MODULE_NAME_HARD_MAX 4096

#define NUX_HOST_STRING_BYTES_HARD_MAX ((4 * 1024) * 1024)

#define NUX_HOST_VALUE_BYTES_HARD_MAX ((16 * 1024) * 1024)

#define NUX_HOST_VALUE_DEPTH_HARD_MAX 64













#define NUX_HOST_VALUE_NODES_HARD_MAX 65536

































#define NUX_PLAYER_STEP_MAX_INPUTS (4 * 1024)

#define NUX_PLAYER_STEP_MAX_INPUT_NAME_BYTES (4 * 1024)

#define NUX_PLAYER_STEP_MAX_POINTERS (4 * 1024)

#define NUX_SCRIPT_INTERRUPTS_PER_CALLBACK_HARD_MAX 10000000

#define NUX_SCRIPT_VM_MEMORY_BYTES_HARD_MAX ((1024 * 1024) * 1024)































































enum NuxStatus
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_STATUS_OK = 0,
  NUX_STATUS_NULL_ARGUMENT = 1,
  NUX_STATUS_IMPORT_ERROR = 2,
  NUX_STATUS_NOT_FOUND = 3,
  NUX_STATUS_RUNTIME_ERROR = 4,
  NUX_STATUS_INVALID_ARGUMENT = 5,
  NUX_STATUS_ABI_MISMATCH = 6,
  NUX_STATUS_WRONG_THREAD = 7,
  NUX_STATUS_INVALID_STRUCT_SIZE = 8,
  NUX_STATUS_HANDLE_MISMATCH = 9,
  NUX_STATUS_REENTRANT_CALL = 10,
  NUX_STATUS_LIMIT_EXCEEDED = 11,
};
#ifndef __cplusplus
typedef uint32_t NuxStatus;
#endif // __cplusplus

/**
 * Owned linear-animation occurrence selected from an artboard.
 */
enum NuxPlayerKind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_PLAYER_KIND_STATIC_ARTBOARD = 0,
  NUX_PLAYER_KIND_STATE_MACHINE = 1,
  NUX_PLAYER_KIND_LINEAR_ANIMATION = 2,
};
#ifndef __cplusplus
typedef uint32_t NuxPlayerKind;
#endif // __cplusplus

/**
 * Explicit domain for an optional absolute monotonic deadline. Epochs are
 * intentionally not interchangeable across domains or processes.
 */
enum NuxMonotonicClockDomain
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_MONOTONIC_CLOCK_DOMAIN_UNSPECIFIED = 0,
  NUX_MONOTONIC_CLOCK_DOMAIN_POSIX_MONOTONIC = 1,
  NUX_MONOTONIC_CLOCK_DOMAIN_APPLE_CONTINUOUS = 2,
  NUX_MONOTONIC_CLOCK_DOMAIN_WINDOWS_PERFORMANCE_COUNTER = 3,
};
#ifndef __cplusplus
typedef uint32_t NuxMonotonicClockDomain;
#endif // __cplusplus

/**
 * One fixed-stride state-machine input mutation in a player step. The
 * selected value field is determined by `kind`; Trigger ignores both values.
 */
enum NuxPlayerInputKind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_PLAYER_INPUT_KIND_BOOL = 0,
  NUX_PLAYER_INPUT_KIND_NUMBER = 1,
  NUX_PLAYER_INPUT_KIND_TRIGGER = 2,
};
#ifndef __cplusplus
typedef uint32_t NuxPlayerInputKind;
#endif // __cplusplus

/**
 * Pinned C++ Scene pointer operation. Application-level cancellation policy
 * is intentionally absent: C++ exposes Down, Move, Up, and Exit.
 */
enum NuxPlayerPointerKind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_PLAYER_POINTER_KIND_DOWN = 0,
  NUX_PLAYER_POINTER_KIND_MOVE = 1,
  NUX_PLAYER_POINTER_KIND_UP = 2,
  NUX_PLAYER_POINTER_KIND_EXIT = 3,
};
#ifndef __cplusplus
typedef uint32_t NuxPlayerPointerKind;
#endif // __cplusplus

/**
 * Exact C++ HitResult strength in pointer submission order.
 */
enum NuxPlayerPointerHit
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_PLAYER_POINTER_HIT_NONE = 0,
  NUX_PLAYER_POINTER_HIT_HIT = 1,
  NUX_PLAYER_POINTER_HIT_HIT_OPAQUE = 2,
};
#ifndef __cplusplus
typedef uint32_t NuxPlayerPointerHit;
#endif // __cplusplus

enum NuxHostValueKind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_HOST_VALUE_KIND_NULL = 0,
  NUX_HOST_VALUE_KIND_BOOL = 1,
  NUX_HOST_VALUE_KIND_NUMBER = 2,
  NUX_HOST_VALUE_KIND_STRING = 3,
  NUX_HOST_VALUE_KIND_LIST = 4,
  NUX_HOST_VALUE_KIND_OBJECT = 5,
};
#ifndef __cplusplus
typedef uint32_t NuxHostValueKind;
#endif // __cplusplus

enum NuxPlayerEventPropertyKind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_PLAYER_EVENT_PROPERTY_KIND_NUMBER = 0,
  NUX_PLAYER_EVENT_PROPERTY_KIND_BOOL = 1,
  NUX_PLAYER_EVENT_PROPERTY_KIND_STRING = 2,
  NUX_PLAYER_EVENT_PROPERTY_KIND_COLOR = 3,
  NUX_PLAYER_EVENT_PROPERTY_KIND_ENUM = 4,
  NUX_PLAYER_EVENT_PROPERTY_KIND_TRIGGER = 5,
};
#ifndef __cplusplus
typedef uint32_t NuxPlayerEventPropertyKind;
#endif // __cplusplus

enum NuxFileAssetKind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_FILE_ASSET_KIND_IMAGE = 0,
  NUX_FILE_ASSET_KIND_FONT = 1,
  NUX_FILE_ASSET_KIND_AUDIO = 2,
  NUX_FILE_ASSET_KIND_BLOB = 3,
  NUX_FILE_ASSET_KIND_SCRIPT = 4,
  NUX_FILE_ASSET_KIND_SHADER = 5,
};
#ifndef __cplusplus
typedef uint32_t NuxFileAssetKind;
#endif // __cplusplus

enum NuxViewModelValueKind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_VIEW_MODEL_VALUE_KIND_UNSUPPORTED = 0,
  NUX_VIEW_MODEL_VALUE_KIND_STRING = 1,
  NUX_VIEW_MODEL_VALUE_KIND_NUMBER = 2,
  NUX_VIEW_MODEL_VALUE_KIND_BOOL = 3,
  NUX_VIEW_MODEL_VALUE_KIND_COLOR = 4,
  NUX_VIEW_MODEL_VALUE_KIND_ENUM = 5,
  NUX_VIEW_MODEL_VALUE_KIND_TRIGGER = 6,
  NUX_VIEW_MODEL_VALUE_KIND_LIST_INDEX = 7,
  NUX_VIEW_MODEL_VALUE_KIND_LIST = 8,
  NUX_VIEW_MODEL_VALUE_KIND_VIEW_MODEL = 9,
  NUX_VIEW_MODEL_VALUE_KIND_IMAGE = 10,
  NUX_VIEW_MODEL_VALUE_KIND_FONT = 11,
  NUX_VIEW_MODEL_VALUE_KIND_BLOB = 12,
  NUX_VIEW_MODEL_VALUE_KIND_ARTBOARD = 13,
};
#ifndef __cplusplus
typedef uint32_t NuxViewModelValueKind;
#endif // __cplusplus

enum NuxViewModelMutationKind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_VIEW_MODEL_MUTATION_KIND_SET_STRING = 0,
  NUX_VIEW_MODEL_MUTATION_KIND_SET_NUMBER = 1,
  NUX_VIEW_MODEL_MUTATION_KIND_SET_BOOL = 2,
  NUX_VIEW_MODEL_MUTATION_KIND_SET_COLOR = 3,
  NUX_VIEW_MODEL_MUTATION_KIND_SET_ENUM = 4,
  NUX_VIEW_MODEL_MUTATION_KIND_FIRE_TRIGGER = 5,
  NUX_VIEW_MODEL_MUTATION_KIND_SET_LIST_INDEX = 6,
  NUX_VIEW_MODEL_MUTATION_KIND_SET_IMAGE = 7,
  NUX_VIEW_MODEL_MUTATION_KIND_SET_VIEW_MODEL = 8,
  NUX_VIEW_MODEL_MUTATION_KIND_LIST_INSERT = 9,
  NUX_VIEW_MODEL_MUTATION_KIND_LIST_REMOVE = 10,
  NUX_VIEW_MODEL_MUTATION_KIND_LIST_SWAP = 11,
  NUX_VIEW_MODEL_MUTATION_KIND_LIST_MOVE = 12,
  NUX_VIEW_MODEL_MUTATION_KIND_LIST_SET = 13,
  NUX_VIEW_MODEL_MUTATION_KIND_LIST_CLEAR = 14,
};
#ifndef __cplusplus
typedef uint32_t NuxViewModelMutationKind;
#endif // __cplusplus

enum NuxViewModelChangeOrigin
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NUX_VIEW_MODEL_CHANGE_ORIGIN_CALLER = 0,
  NUX_VIEW_MODEL_CHANGE_ORIGIN_RUNTIME = 1,
};
#ifndef __cplusplus
typedef uint32_t NuxViewModelChangeOrigin;
#endif // __cplusplus

#if defined(NUX_CAPI_ANDROID_VULKAN)
/**
 * Owned frame pixels returned by the Android Vulkan renderer.
 *
 * `data` exposes tightly packed, top-row-first RGBA8 UNORM bytes with
 * premultiplied alpha. Its borrowed pointer remains valid until `_free`.
 */
typedef struct NuxAndroidVulkanFrame NuxAndroidVulkanFrame;
#endif

#if defined(NUX_CAPI_ANDROID_VULKAN)
/**
 * Product-neutral headless Vulkan renderer. The handle and every frame it
 * returns are affine to the thread that created them.
 */
typedef struct NuxAndroidVulkanRenderer NuxAndroidVulkanRenderer;
#endif

/**
 * Owned artboard occurrence. It retains the imported [`File`] through native
 * shared ownership and therefore remains valid after its [`NuxFile`] handle
 * is released.
 */
typedef struct NuxArtboardInstance NuxArtboardInstance;

/**
 * Bounded, library-owned diagnostic/result storage.
 */
typedef struct NuxCapiResult NuxCapiResult;

typedef struct NuxFile NuxFile;

/**
 * Product-neutral selected player. This surface establishes selection,
 * ownership, and metadata; playback operations are exposed separately.
 */
typedef struct NuxPlayer NuxPlayer;

/**
 * Bounded library-owned result of one player step.
 */
typedef struct NuxPlayerStepResult NuxPlayerStepResult;

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Product-neutral native renderer. The handle owns one exact Metal domain and
 * is affine to its creator thread like the other portable C handles.
 */
typedef struct NuxRenderer NuxRenderer;
#endif

/**
 * Owned state machine instance. Advance it through the
 * [`NuxArtboardInstance`] it was created from.
 */
typedef struct NuxStateMachineInstance NuxStateMachineInstance;

/**
 * Immutable owned projection of every data-binding schema in one file.
 */
typedef struct NuxViewModelCatalog NuxViewModelCatalog;

/**
 * Owned view-model context for driving an artboard's data binds.
 *
 * This handle retains its imported file and one shared runtime graph. Handles
 * returned by `nux_view_model_instance_share` preserve graph identity and
 * observe the same mutations. Generic file-level instances may bind to a
 * compatible artboard occurrence from the same file; legacy instances created
 * from an artboard retain the exact originating-occurrence restriction.
 */
typedef struct NuxViewModelInstance NuxViewModelInstance;

typedef struct NuxViewModelMutationResult NuxViewModelMutationResult;

typedef struct NuxViewModelSnapshot NuxViewModelSnapshot;

#if defined(NUX_CAPI_ANDROID_VULKAN)
typedef uint32_t NuxAndroidVulkanPixelFormat;
#endif

/**
 * Borrowed view of a [`RawPath`]: `verbs` holds `NuxPathVerb` values and
 * `points` holds `point_count` interleaved x,y pairs. Only valid for the
 * duration of the callback it is passed to.
 */
typedef struct NuxRawPathView {
  const uint8_t *verbs;
  size_t verb_count;
  const float *points;
  size_t point_count;
} NuxRawPathView;

/**
 * C mirror of [`ImageSampler`] using the `NuxImageWrap`/`NuxImageFilter`
 * enum values.
 */
typedef struct NuxImageSampler {
  uint8_t wrap_x;
  uint8_t wrap_y;
  uint8_t filter;
} NuxImageSampler;

/**
 * Caller-provided render vtable mirroring the nuxie-render-api traits.
 *
 * Handles are opaque `uint64_t` values chosen by the caller; `0` is passed
 * for "no object" (for example a cleared shader). Transform arguments point
 * at six floats in `[xx, yx, xy, yy, tx, ty]` order. All callbacks may be
 * NULL.
 */
typedef struct NuxRenderCallbacks {
  /**
   * Must be initialized to `sizeof(NuxRenderCallbacks)` by the caller.
   */
  uint32_t struct_size;
  void *user_data;
  uint64_t (*make_render_path)(void*, const struct NuxRawPathView*, uint8_t);
  uint64_t (*make_empty_render_path)(void*);
  uint64_t (*make_render_paint)(void*);
  uint64_t (*make_linear_gradient)(void*,
                                   float,
                                   float,
                                   float,
                                   float,
                                   const uint32_t*,
                                   const float*,
                                   size_t);
  uint64_t (*make_radial_gradient)(void*, float, float, float, const uint32_t*, const float*, size_t);
  uint64_t (*make_render_buffer)(void*, uint8_t, uint8_t, size_t);
  uint64_t (*decode_image)(void*, const uint8_t*, size_t, uint32_t*, uint32_t*);
  void (*release_render_path)(void*, uint64_t);
  void (*release_render_paint)(void*, uint64_t);
  void (*release_render_shader)(void*, uint64_t);
  void (*release_render_buffer)(void*, uint64_t);
  void (*release_render_image)(void*, uint64_t);
  void (*render_path_rewind)(void*, uint64_t);
  void (*render_path_fill_rule)(void*, uint64_t, uint8_t);
  void (*render_path_move_to)(void*, uint64_t, float, float);
  void (*render_path_line_to)(void*, uint64_t, float, float);
  void (*render_path_cubic_to)(void*, uint64_t, float, float, float, float, float, float);
  void (*render_path_close)(void*, uint64_t);
  void (*render_path_add_raw_path)(void*, uint64_t, const struct NuxRawPathView*);
  void (*render_path_add_render_path)(void*, uint64_t, uint64_t, const float*);
  void (*render_path_add_render_path_backwards)(void*, uint64_t, uint64_t, const float*);
  void (*render_paint_style)(void*, uint64_t, uint8_t);
  void (*render_paint_color)(void*, uint64_t, uint32_t);
  void (*render_paint_thickness)(void*, uint64_t, float);
  void (*render_paint_join)(void*, uint64_t, uint32_t);
  void (*render_paint_cap)(void*, uint64_t, uint32_t);
  void (*render_paint_feather)(void*, uint64_t, float);
  void (*render_paint_blend_mode)(void*, uint64_t, uint8_t);
  void (*render_paint_shader)(void*, uint64_t, uint64_t);
  void (*render_paint_invalidate_stroke)(void*, uint64_t);
  void (*render_buffer_unmap)(void*, uint64_t, const uint8_t*, size_t);
  void (*save)(void*);
  void (*restore)(void*);
  void (*transform)(void*, const float*);
  void (*draw_path)(void*, uint64_t, uint64_t);
  void (*clip_path)(void*, uint64_t);
  void (*draw_image)(void*, uint64_t, struct NuxImageSampler, uint8_t, float);
  void (*draw_image_mesh)(void*,
                          uint64_t,
                          struct NuxImageSampler,
                          uint64_t,
                          uint64_t,
                          uint64_t,
                          uint32_t,
                          uint32_t,
                          uint8_t,
                          float);
  void (*modulate_opacity)(void*, float);
} NuxRenderCallbacks;

typedef struct NuxStringView {
  const char *data;
  size_t len;
} NuxStringView;

/**
 * Borrowed arbitrary bytes. Unlike `NuxStringView`, this view makes no UTF-8
 * promise. Its owner and lifetime are documented by the containing API.
 */
typedef struct NuxByteView {
  const uint8_t *data;
  size_t len;
} NuxByteView;

typedef struct NuxTextRunMutation {
  /**
   * Exact, case-sensitive authored root `TextValueRun` name.
   */
  struct NuxStringView name;
  /**
   * Replacement text bytes, borrowed only for the synchronous call.
   */
  struct NuxByteView text;
} NuxTextRunMutation;

typedef struct NuxTextRunMutationBatch {
  uint32_t struct_size;
  const struct NuxTextRunMutation *mutations;
  size_t mutation_count;
} NuxTextRunMutationBatch;

/**
 * Caller-sized view into one owned C-ABI result. `code` and `message` remain
 * valid until the owning `NuxCapiResult` is released.
 */
typedef struct NuxCapiDiagnosticView {
  uint32_t struct_size;
  NuxStatus status;
  struct NuxStringView code;
  struct NuxStringView message;
} NuxCapiDiagnosticView;

/**
 * Immutable identity embedded into the shipped runtime binary.
 *
 * Both strings have process-static lifetime and are not NUL-terminated; C
 * callers must respect their explicit lengths.
 */
typedef struct NuxRuntimeInfo {
  /**
   * Must be initialized to `sizeof(NuxRuntimeInfo)` by the caller.
   */
  uint32_t struct_size;
  uint32_t abi_version;
  struct NuxStringView runtime_version;
  struct NuxStringView source_revision;
} NuxRuntimeInfo;

typedef struct NuxFileAssetDescriptorView {
  uint32_t struct_size;
  size_t ordinal;
  uint32_t kind;
  uint32_t has_authored_id;
  uint32_t authored_id;
  struct NuxStringView name;
  struct NuxStringView file_extension;
  uint32_t is_embedded;
  uint32_t has_contents_record;
  uint32_t required_provider_flags;
} NuxFileAssetDescriptorView;

/**
 * Explicit trust and resource policy for a generic script-host command
 * import. `module_name` is copied during the call and is never interpreted by
 * the runtime. Every numeric limit must be non-zero and no greater than the
 * corresponding `NUX_HOST_*_HARD_MAX` constant.
 */
typedef struct NuxHostCommandImportConfig {
  uint32_t struct_size;
  struct NuxStringView module_name;
  size_t max_script_memory_bytes;
  uint32_t max_script_interrupts_per_callback;
  size_t max_commands_per_step;
  size_t max_value_depth;
  size_t max_value_nodes;
  size_t max_identifier_bytes;
  size_t max_string_bytes;
  size_t max_value_bytes;
  size_t max_command_bytes_per_step;
} NuxHostCommandImportConfig;

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef uint32_t NuxAssetCallbackStatus;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef uint32_t NuxAssetKind;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef struct NuxExternalAssetRequest {
  uint32_t struct_size;
  NuxAssetKind kind;
  size_t asset_index;
  uint32_t asset_id;
  struct NuxStringView name;
  struct NuxStringView file_extension;
} NuxExternalAssetRequest;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Callback-produced bytes with an explicit borrowed-owner retain cycle.
 *
 * When `struct_size` covers the callback fields and both callbacks are
 * present, Rust invokes `retain(owner)` exactly once before inspecting `data`,
 * and `release(owner)` exactly once after copying or rejecting it. A short
 * prefix or a missing half of the pair transfers no ownership and is rejected
 * without invoking either callback.
 */
typedef struct NuxRetainedBytes {
  uint32_t struct_size;
  const uint8_t *data;
  size_t len;
  void *owner;
  void (*retain)(void *owner);
  void (*release)(void *owner);
} NuxRetainedBytes;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef struct NuxImageDecodeRequest {
  uint32_t struct_size;
  /**
   * Encoded bytes borrowed only for the synchronous callback invocation.
   */
  struct NuxByteView encoded;
  uint32_t maximum_dimension;
  size_t maximum_decoded_bytes;
} NuxImageDecodeRequest;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef uint32_t NuxPixelFormat;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Host-decoded image pixels. The only accepted format is RGBA8,
 * premultiplied-alpha, sRGB; Rust validates and tightly repacks each row before
 * any renderer upload.
 */
typedef struct NuxDecodedImage {
  uint32_t struct_size;
  uint32_t width;
  uint32_t height;
  uint32_t row_bytes;
  NuxPixelFormat pixel_format;
  struct NuxRetainedBytes pixels;
} NuxDecodedImage;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * One synchronous, versioned Apple asset import surface. The table and all
 * request views are borrowed only until `nux_file_import_with_apple_assets`
 * returns; callback-owned outputs use `NuxRetainedBytes` instead.
 */
typedef struct NuxAppleAssetHooks {
  uint32_t struct_size;
  void *context;
  NuxAssetCallbackStatus (*lookup_external_asset)(void *context,
                                                  const struct NuxExternalAssetRequest *request,
                                                  struct NuxRetainedBytes *out_bytes);
  NuxAssetCallbackStatus (*decode_image)(void *context,
                                         const struct NuxImageDecodeRequest *request,
                                         struct NuxDecodedImage *out_image);
  size_t maximum_external_asset_bytes;
  size_t maximum_total_external_asset_bytes;
  uint32_t maximum_image_dimension;
  size_t maximum_decoded_image_bytes;
  size_t maximum_total_decoded_image_bytes;
} NuxAppleAssetHooks;
#endif

/**
 * Exact descriptor expected by a configured import. This is a fixed-stride
 * array element: `struct_size` must equal `sizeof(NuxExpectedFileAssetDescriptor)`.
 */
typedef struct NuxExpectedFileAssetDescriptor {
  uint32_t struct_size;
  size_t ordinal;
  uint32_t kind;
  uint32_t has_authored_id;
  uint32_t authored_id;
  struct NuxStringView name;
  struct NuxStringView file_extension;
  uint32_t is_embedded;
  uint32_t has_contents_record;
  uint32_t required_provider_flags;
} NuxExpectedFileAssetDescriptor;

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * One deep import surface. Each optional child is copied and validated in
 * full before file parsing or any platform callback. A null child pointer
 * leaves that capability inert.
 */
typedef struct NuxFileImportConfig {
  uint32_t struct_size;
  const struct NuxHostCommandImportConfig *host_commands;
  const struct NuxAppleAssetHooks *apple_assets;
  const struct NuxExpectedFileAssetDescriptor *expected_assets;
  size_t expected_asset_count;
} NuxFileImportConfig;
#endif

/**
 * Versioned metadata for a selected runtime-native player.
 */
typedef struct NuxPlayerInfo {
  /**
   * Must be initialized to `sizeof(NuxPlayerInfo)` by the caller.
   */
  uint32_t struct_size;
  NuxPlayerKind kind;
  /**
   * Authored index within the selected kind, or `SIZE_MAX` for static.
   */
  size_t index;
  /**
   * Copied UTF-8 metadata owned by `NuxPlayer`; valid until player free.
   */
  struct NuxStringView name;
} NuxPlayerInfo;

typedef struct NuxPlayerInputChange {
  /**
   * One of the `NuxPlayerInputKind` constants. Stored as an integer so an
   * invalid C bit pattern is rejected rather than becoming a Rust enum.
   */
  uint32_t kind;
  struct NuxStringView name;
  /**
   * Canonical C boolean encoding: exactly 0 or 1. Other values reject the
   * whole batch before mutation.
   */
  uint32_t bool_value;
  float number_value;
} NuxPlayerInputChange;

typedef struct NuxPlayerPointerEvent {
  /**
   * One of the `NuxPlayerPointerKind` constants. Invalid values are
   * rejected during whole-batch validation.
   */
  uint32_t kind;
  float x;
  float y;
  int32_t pointer_id;
  float timestamp_seconds;
} NuxPlayerPointerEvent;

/**
 * One atomic, product-neutral player operation. Input and pointer arrays use
 * ABI-v3 fixed element strides; future element layouts require a new entry
 * point rather than appending fields and silently changing array stride.
 */
typedef struct NuxPlayerStep {
  uint32_t struct_size;
  const struct NuxPlayerInputChange *inputs;
  size_t input_count;
  const struct NuxPlayerPointerEvent *pointers;
  size_t pointer_count;
  float elapsed_seconds;
  /**
   * Opaque caller identity copied into runtime-authored change entries.
   */
  uint64_t correlation_id;
} NuxPlayerStep;

/**
 * Owned reported-event projection. All string views borrow the owning step
 * result and remain valid until its successful free.
 */
typedef struct NuxPlayerEventView {
  uint32_t struct_size;
  size_t event_local_index;
  uint32_t event_core_type;
  struct NuxStringView name;
  struct NuxStringView url;
  struct NuxStringView target;
  float seconds_delay;
  size_t property_count;
} NuxPlayerEventView;

/**
 * Fixed projection of one typed custom Event property. Only the value field
 * selected by `kind` is meaningful.
 */
typedef struct NuxPlayerEventPropertyView {
  uint32_t struct_size;
  /**
   * One of the `NUX_PLAYER_EVENT_PROPERTY_KIND_*` constants.
   */
  uint32_t kind;
  struct NuxStringView name;
  float number_value;
  bool bool_value;
  /**
   * Exact authored/script bytes for a String property; not necessarily UTF-8.
   */
  struct NuxByteView string_value;
  uint32_t color_value;
  uint64_t integer_value;
} NuxPlayerEventPropertyView;

/**
 * One command in transaction FIFO order. `root_value_index` addresses the
 * owning step result's flattened value graph.
 */
typedef struct NuxHostCommandView {
  uint32_t struct_size;
  struct NuxStringView name;
  size_t root_value_index;
} NuxHostCommandView;

/**
 * One flattened host value. Scalars use their matching value field. Lists
 * and objects expose `child_count` edges through
 * `nux_player_step_result_host_value_child`.
 */
typedef struct NuxHostValueView {
  uint32_t struct_size;
  uint32_t kind;
  bool bool_value;
  double number_value;
  struct NuxStringView string_value;
  size_t child_count;
} NuxHostValueView;

/**
 * One edge in a list or object. Object edges have a present UTF-8 `key`;
 * list edges use NULL+0. `value_index` addresses the same owned result.
 */
typedef struct NuxHostValueChildView {
  uint32_t struct_size;
  struct NuxStringView key;
  size_t value_index;
} NuxHostValueChildView;

/**
 * Summary of one owned step result. `keep_going` is the runtime's
 * advanceAndApply continuation result; it is not a host render/scheduling
 * request.
 */
typedef struct NuxPlayerStepInfo {
  uint32_t struct_size;
  bool keep_going;
  size_t pointer_result_count;
  size_t state_change_count;
  size_t event_count;
  /**
   * Commands are exposed only after the transaction commits. Hosts copy
   * authored events first, then commands in FIFO order.
   */
  size_t host_command_count;
  size_t view_model_change_count;
} NuxPlayerStepInfo;

/**
 * Product-neutral scheduling facts captured by one successful atomic player
 * step. They are deliberately independent from `keep_going`, whose meaning
 * remains the exact pinned C++ `advanceAndApply` return value.
 */
typedef struct NuxPlayerSchedulingInfo {
  uint32_t struct_size;
  /**
   * This committed operation changed observable runtime state.
   */
  bool dirty;
  /**
   * No selected root or nested runtime occurrence needs continuation.
   */
  bool settled;
  /**
   * The current occurrence revision has not yet been presented.
   */
  bool render_required;
  /**
   * Whether `wake_deadline_monotonic_ns` contains a deadline.
   */
  bool has_wake_deadline;
  /**
   * Clock whose epoch defines `wake_deadline_monotonic_ns`.
   */
  NuxMonotonicClockDomain wake_deadline_clock;
  /**
   * Exact occurrence-local revision associated with `render_required`.
   */
  uint64_t render_revision;
  /**
   * Absolute nanoseconds in `wake_deadline_clock`'s named domain.
   * The current runtime has no time-based deferred work and reports this
   * field absent rather than manufacturing a host-policy deadline.
   */
  uint64_t wake_deadline_monotonic_ns;
} NuxPlayerSchedulingInfo;

/**
 * C++ `stateChangedByIndex` projection in compressed authored-layer order.
 */
typedef struct NuxPlayerStateChangeView {
  uint32_t struct_size;
  size_t layer_index;
  /**
   * Pinned Core schema type key (`Core::typeKey`).
   */
  uint32_t state_core_type;
  /**
   * Authored Core id, or `UINT32_MAX` when absent.
   */
  uint32_t state_global_id;
} NuxPlayerStateChangeView;

/**
 * One ordered after-value from an owned mutation or player-step result.
 * Every borrowed field expires when that containing result is freed.
 */
typedef struct NuxViewModelChangeView {
  uint32_t struct_size;
  uint32_t origin;
  uint64_t correlation_id;
  uint64_t owner_instance_id;
  size_t property_index;
  uint32_t kind;
  /**
   * String after-value bytes borrowed from the containing result.
   * Absent for other value kinds.
   */
  struct NuxByteView bytes_value;
  float number_value;
  uint64_t integer_value;
  uint32_t bool_value;
  uint64_t referenced_instance_id;
  size_t list_item_count;
} NuxViewModelChangeView;

#if defined(NUX_CAPI_ANDROID_VULKAN)
typedef uint32_t NuxAndroidVulkanRendererFit;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef uint32_t NuxRendererDisposition;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef uint32_t NuxRendererHealth;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef struct NuxRendererOutcome {
  /**
   * Must be initialized to `sizeof(NuxRendererOutcome)`.
   */
  uint32_t struct_size;
  NuxRendererDisposition disposition;
  NuxRendererHealth health;
  uint32_t pixel_width;
  uint32_t pixel_height;
  uint64_t draw_calls;
  uint64_t logical_flushes;
  uint64_t atomic_strategy_partitions;
} NuxRendererOutcome;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef struct NuxRendererInfo {
  /**
   * Must be initialized to `sizeof(NuxRendererInfo)`.
   */
  uint32_t struct_size;
  uint32_t pixel_width;
  uint32_t pixel_height;
  bool attached;
  NuxRendererHealth health;
  /**
   * Changes whenever reattach replaces native renderer resources.
   */
  uint64_t generation;
} NuxRendererInfo;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef uint32_t NuxMetalDrawableState;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef uint32_t NuxRendererFit;
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
typedef struct NuxMetalRenderOperation {
  /**
   * Must be initialized to `sizeof(NuxMetalRenderOperation)`.
   */
  uint32_t struct_size;
  /**
   * Swift-reported drawable availability; Rust never queries UI state.
   */
  NuxMetalDrawableState drawable_state;
  /**
   * Synchronously borrowed live `id<CAMetalDrawable>` when AVAILABLE.
   */
  void *drawable;
  /**
   * Premultiplied ARGB clear color.
   */
  uint32_t clear_color;
  /**
   * Caller-owned context consumed by `completion_callback`.
   */
  void *completion_context;
  /**
   * Both completion fields must be null or non-null together.
   */
  void (*completion_callback)(void *context);
  /**
   * Optional viewport-fit policy. Older struct prefixes default to NONE.
   */
  NuxRendererFit fit;
} NuxMetalRenderOperation;
#endif

typedef struct NuxViewModelAuthoredInstanceView {
  uint32_t struct_size;
  size_t schema_index;
  size_t instance_index;
  /**
   * NULL+0 means the authored instance has no name.
   */
  struct NuxStringView name;
} NuxViewModelAuthoredInstanceView;

typedef struct NuxViewModelCatalogInfo {
  uint32_t struct_size;
  size_t schema_count;
  size_t property_count;
  size_t authored_instance_count;
  size_t enum_label_count;
} NuxViewModelCatalogInfo;

typedef struct NuxViewModelPropertyView {
  uint32_t struct_size;
  size_t schema_index;
  size_t property_index;
  struct NuxStringView name;
  uint32_t kind;
  /**
   * `SIZE_MAX` when this is not a nested view-model property.
   */
  size_t referenced_schema_index;
  size_t first_enum_label;
  size_t enum_label_count;
} NuxViewModelPropertyView;

typedef struct NuxViewModelSchemaView {
  uint32_t struct_size;
  size_t schema_index;
  struct NuxStringView name;
  size_t first_property;
  size_t property_count;
  size_t first_authored_instance;
  size_t authored_instance_count;
  /**
   * Catalog-authored-instance index, or `SIZE_MAX` when generated defaults apply.
   */
  size_t default_authored_instance;
  uint32_t is_global;
} NuxViewModelSchemaView;

typedef struct NuxViewModelMutation {
  uint32_t kind;
  struct NuxViewModelInstance *instance;
  struct NuxStringView path;
  struct NuxViewModelInstance *related_instance;
  struct NuxByteView bytes_value;
  float number_value;
  uint64_t integer_value;
  /**
   * Canonical C boolean: exactly 0 or 1.
   */
  uint32_t bool_value;
  size_t index;
  size_t second_index;
} NuxViewModelMutation;

typedef struct NuxViewModelMutationBatch {
  uint32_t struct_size;
  const struct NuxViewModelMutation *mutations;
  size_t mutation_count;
  /**
   * Opaque caller identity copied into every successful change entry.
   */
  uint64_t correlation_id;
} NuxViewModelMutationBatch;

typedef struct NuxViewModelMutationResultInfo {
  uint32_t struct_size;
  NuxStatus status;
  size_t applied_count;
  /**
   * Bounded diagnostic code bytes borrowed from the result until it is freed.
   */
  struct NuxStringView code;
  /**
   * Bounded diagnostic message bytes borrowed from the result until it is freed.
   */
  struct NuxStringView message;
  uint64_t correlation_id;
  size_t change_count;
} NuxViewModelMutationResultInfo;

typedef struct NuxViewModelSnapshotInfo {
  uint32_t struct_size;
  uint64_t root_instance_id;
  size_t instance_count;
  size_t value_count;
  size_t list_item_count;
} NuxViewModelSnapshotInfo;

typedef struct NuxViewModelSnapshotInstanceView {
  uint32_t struct_size;
  uint64_t instance_id;
  size_t schema_index;
  size_t first_value;
  size_t value_count;
} NuxViewModelSnapshotInstanceView;

typedef struct NuxViewModelSnapshotValueView {
  uint32_t struct_size;
  uint64_t owner_instance_id;
  size_t property_index;
  struct NuxStringView name;
  uint32_t kind;
  float number_value;
  uint64_t integer_value;
  uint32_t bool_value;
  struct NuxByteView bytes_value;
  uint64_t referenced_instance_id;
  size_t first_list_item;
  size_t list_item_count;
} NuxViewModelSnapshotValueView;

#if defined(NUX_CAPI_ANDROID_VULKAN)
/**
 * Tightly packed, top-row-first RGBA8 UNORM with premultiplied alpha.
 */
#define NUX_ANDROID_VULKAN_PIXEL_FORMAT_RGBA8_PREMULTIPLIED 1
#endif

#if defined(NUX_CAPI_ANDROID_VULKAN)
/**
 * Uniformly scale and center the authored artboard inside the output frame.
 */
#define NUX_ANDROID_VULKAN_RENDERER_FIT_CONTAIN_CENTER 1
#endif

#if defined(NUX_CAPI_ANDROID_VULKAN)
/**
 * Preserve authored artboard coordinates without applying a viewport fit.
 */
#define NUX_ANDROID_VULKAN_RENDERER_FIT_NONE 0
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_ASSET_CALLBACK_STATUS_FAILED 2
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_ASSET_CALLBACK_STATUS_NOT_FOUND 1
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_ASSET_CALLBACK_STATUS_OK 0
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_ASSET_KIND_AUDIO 3
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_ASSET_KIND_FONT 2
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_ASSET_KIND_IMAGE 1
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_METAL_DRAWABLE_STATE_AVAILABLE 0
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_METAL_DRAWABLE_STATE_OCCLUDED 2
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_METAL_DRAWABLE_STATE_TIMEOUT 1
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_PIXEL_FORMAT_RGBA8_PREMULTIPLIED_SRGB 1
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_DEVICE_LOST 7
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_NONE 0
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_OUT_OF_MEMORY 8
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_PRESENTED 1
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_RECONFIGURED 5
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_RECREATED 6
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_SKIPPED_OCCLUDED 4
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_SKIPPED_TIMEOUT 3
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_DISPOSITION_SKIPPED_ZERO_SIZE 2
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Uniformly scale and center the authored artboard inside the renderer surface.
 */
#define NUX_RENDERER_FIT_CONTAIN_CENTER 1
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Preserve authored artboard coordinates without applying a viewport fit.
 */
#define NUX_RENDERER_FIT_NONE 0
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_HEALTH_DEVICE_LOST 1
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_HEALTH_FAILED 3
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_HEALTH_HEALTHY 0
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
#define NUX_RENDERER_HEALTH_OUT_OF_MEMORY 2
#endif

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#if defined(NUX_CAPI_ANDROID_VULKAN)
/**
 * Returns a borrowed pointer to the frame's tightly packed RGBA8 bytes.
 */
const uint8_t *nux_android_vulkan_frame_data(const struct NuxAndroidVulkanFrame *frame);
#endif

#if defined(NUX_CAPI_ANDROID_VULKAN)
NuxStatus nux_android_vulkan_frame_free(struct NuxAndroidVulkanFrame *frame);
#endif

#if defined(NUX_CAPI_ANDROID_VULKAN)
uint32_t nux_android_vulkan_frame_height(const struct NuxAndroidVulkanFrame *frame);
#endif

#if defined(NUX_CAPI_ANDROID_VULKAN)
size_t nux_android_vulkan_frame_len(const struct NuxAndroidVulkanFrame *frame);
#endif

#if defined(NUX_CAPI_ANDROID_VULKAN)
NuxAndroidVulkanPixelFormat nux_android_vulkan_frame_pixel_format(const struct NuxAndroidVulkanFrame *frame);
#endif

#if defined(NUX_CAPI_ANDROID_VULKAN)
uint32_t nux_android_vulkan_frame_row_stride_bytes(const struct NuxAndroidVulkanFrame *frame);
#endif

#if defined(NUX_CAPI_ANDROID_VULKAN)
uint32_t nux_android_vulkan_frame_width(const struct NuxAndroidVulkanFrame *frame);
#endif

/**
 * Advance the artboard timeline without a state machine. `out_changed` is
 * optional and reports whether anything changed.
 */
NuxStatus nux_artboard_instance_advance(struct NuxArtboardInstance *instance,
                                        float elapsed_seconds,
                                        bool *out_changed);

/**
 * Bind `view_model` to `instance`'s own data binds and nested-artboard
 * contexts (mirrors `artboard->bindViewModelInstance(...)`). The context is
 * retained by the artboard, so later mutations remain shared. Generic file-level
 * instances must have a compatible schema and source file; legacy instances
 * created from an artboard must come from this exact occurrence.
 */
NuxStatus nux_artboard_instance_bind_view_model(struct NuxArtboardInstance *instance,
                                                const struct NuxViewModelInstance *view_model);

/**
 * Draw the artboard through the caller-provided render vtable. See
 * `NuxRenderCallbacks` for the ownership and handle contract. The first
 * draw's renderer domain is retained by the Artboard occurrence, even if that
 * draw returns an error. A different descriptor/domain returns
 * `NUX_STATUS_HANDLE_MISMATCH`; a future explicit reset can make switching
 * domains safe. Callback functions and `user_data` must remain valid until
 * the last artboard/player retaining the occurrence is freed.
 */
NuxStatus nux_artboard_instance_draw(struct NuxArtboardInstance *instance,
                                     const struct NuxRenderCallbacks *callbacks);

NuxStatus nux_artboard_instance_free(struct NuxArtboardInstance *instance);

/**
 * Instantiate the artboard at `artboard_index`. The returned occurrence
 * retains the imported file and may outlive the `NuxFile` handle.
 */
NuxStatus nux_artboard_instance_new(const struct NuxFile *file,
                                    size_t artboard_index,
                                    struct NuxArtboardInstance **out_instance);

/**
 * Instantiate the first artboard whose authored name exactly matches the
 * length-delimited UTF-8 `name`. Matching is case-sensitive and has no
 * fallback; an empty name is a valid selector.
 */
NuxStatus nux_artboard_instance_new_named(const struct NuxFile *file,
                                          struct NuxStringView name,
                                          struct NuxArtboardInstance **out_instance);

/**
 * Result-bearing exact artboard selection for consumers that need an owned
 * diagnostic on every outcome.
 */
NuxStatus nux_artboard_instance_new_named_with_result(const struct NuxFile *file,
                                                      struct NuxStringView name,
                                                      struct NuxArtboardInstance **out_instance,
                                                      struct NuxCapiResult **out_result);

/**
 * Atomically replace a bounded batch of exact-name root text runs.
 *
 * Every name and buffer is validated before the first write. `out_changed` is
 * optional and receives canonical 0/1. An unexpected commit divergence or
 * panic drops the runtime-owned transaction, restoring every staged write
 * and discarding every deferred invalidation before this call returns.
 */
NuxStatus nux_artboard_instance_set_text_runs(struct NuxArtboardInstance *instance,
                                              const struct NuxTextRunMutationBatch *batch,
                                              uint32_t *out_changed);

uint32_t nux_capi_abi_version(void);

NuxStatus nux_capi_require_abi(uint32_t required_version);

NuxStatus nux_capi_result_diagnostic(const struct NuxCapiResult *result,
                                     struct NuxCapiDiagnosticView *out_diagnostic);

NuxStatus nux_capi_result_free(struct NuxCapiResult *result);

NuxStatus nux_capi_result_status(const struct NuxCapiResult *result, NuxStatus *out_status);

NuxStatus nux_capi_runtime_info(struct NuxRuntimeInfo *out_info);

NuxStatus nux_file_artboard_animation_count(const struct NuxFile *file,
                                            size_t index,
                                            size_t *out_count);

/**
 * Name of one of an artboard's linear animations. The returned
 * length-delimited UTF-8 view borrows `file` and expires when the file handle
 * is freed.
 */
NuxStatus nux_file_artboard_animation_name(const struct NuxFile *file,
                                           size_t artboard_index,
                                           size_t animation_index,
                                           struct NuxStringView *out_name);

NuxStatus nux_file_artboard_count(const struct NuxFile *file, size_t *out_count);

NuxStatus nux_file_artboard_name(const struct NuxFile *file,
                                 size_t index,
                                 struct NuxStringView *out_name);

NuxStatus nux_file_artboard_state_machine_count(const struct NuxFile *file,
                                                size_t index,
                                                size_t *out_count);

/**
 * Name of one of an artboard's state machines. The returned view borrows the
 * file and is valid until the file is freed.
 */
NuxStatus nux_file_artboard_state_machine_name(const struct NuxFile *file,
                                               size_t artboard_index,
                                               size_t state_machine_index,
                                               struct NuxStringView *out_name);

NuxStatus nux_file_asset_count(const struct NuxFile *file, size_t *out_count);

/**
 * Returns metadata borrowed from `file`; string views remain valid until the
 * file handle is freed. Callers must copy them before another runtime call.
 */
NuxStatus nux_file_asset_descriptor(const struct NuxFile *file,
                                    size_t index,
                                    struct NuxFileAssetDescriptorView *out_descriptor);

NuxStatus nux_file_free(struct NuxFile *file);

NuxStatus nux_file_import(const uint8_t *bytes, size_t len, struct NuxFile **out_file);

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
NuxStatus nux_file_import_configured(const uint8_t *bytes,
                                     size_t len,
                                     const struct NuxFileImportConfig *config,
                                     struct NuxFile **out_file,
                                     struct NuxCapiResult **out_result);
#endif

/**
 * Import exact caller-authenticated bytes and install one generic script
 * module named by `config`. The module exposes only
 * `command(name, payload)`. This function performs no package/signature
 * authentication; choosing this explicit import path is the caller's trust
 * assertion. Ordinary `nux_file_import` remains script-inert.
 *
 * No foreign callback is installed. Commands are returned only through a
 * successful `NuxPlayerStepResult` after its runtime transaction commits.
 */
NuxStatus nux_file_import_trusted_with_host_commands(const uint8_t *bytes,
                                                     size_t len,
                                                     const struct NuxHostCommandImportConfig *config,
                                                     struct NuxFile **out_file,
                                                     struct NuxCapiResult **out_result);

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Compatibility wrapper for the Apple-only import added in ABI v3.
 */
NuxStatus nux_file_import_with_apple_assets(const uint8_t *bytes,
                                            size_t len,
                                            const struct NuxAppleAssetHooks *hooks,
                                            struct NuxFile **out_file,
                                            struct NuxCapiResult **out_result);
#endif

/**
 * Diagnostic import path for production consumers. `out_file` is published
 * only on success. `out_result` is always published and owns a bounded status
 * code/message until released with `nux_capi_result_free`.
 */
NuxStatus nux_file_import_with_result(const uint8_t *bytes,
                                      size_t len,
                                      struct NuxFile **out_file,
                                      struct NuxCapiResult **out_result);

NuxStatus nux_file_view_model_catalog(const struct NuxFile *file,
                                      struct NuxViewModelCatalog **out_catalog);

/**
 * Acknowledge that an exact occurrence revision was successfully presented.
 * Stale or future revisions return HANDLE_MISMATCH and cannot clear newer
 * render work.
 */
NuxStatus nux_player_acknowledge_presented(struct NuxPlayer *player, uint64_t render_revision);

NuxStatus nux_player_free(struct NuxPlayer *player);

/**
 * Read selected-player metadata into a versioned caller-owned struct.
 */
NuxStatus nux_player_info(const struct NuxPlayer *player, struct NuxPlayerInfo *out_info);

/**
 * Select the artboard's default scene using the pinned C++ order: authored
 * valid default state machine, state machine zero, animation zero, then a
 * static artboard when it has no playable animation.
 */
NuxStatus nux_player_new_default(struct NuxArtboardInstance *instance,
                                 struct NuxPlayer **out_player);

/**
 * Result-bearing default-scene selection.
 */
NuxStatus nux_player_new_default_with_result(struct NuxArtboardInstance *instance,
                                             struct NuxPlayer **out_player,
                                             struct NuxCapiResult **out_result);

/**
 * Select a linear animation by exact, case-sensitive, length-delimited UTF-8
 * name. No state-machine or index fallback is performed.
 */
NuxStatus nux_player_new_linear_animation_named(struct NuxArtboardInstance *instance,
                                                struct NuxStringView name,
                                                struct NuxPlayer **out_player);

/**
 * Result-bearing exact linear-animation selection.
 */
NuxStatus nux_player_new_linear_animation_named_with_result(struct NuxArtboardInstance *instance,
                                                            struct NuxStringView name,
                                                            struct NuxPlayer **out_player,
                                                            struct NuxCapiResult **out_result);

/**
 * Select a state machine by exact, case-sensitive, length-delimited UTF-8
 * name. No default, index-zero, or animation fallback is performed.
 */
NuxStatus nux_player_new_state_machine_named(struct NuxArtboardInstance *instance,
                                             struct NuxStringView name,
                                             struct NuxPlayer **out_player);

/**
 * Result-bearing exact state-machine selection.
 */
NuxStatus nux_player_new_state_machine_named_with_result(struct NuxArtboardInstance *instance,
                                                         struct NuxStringView name,
                                                         struct NuxPlayer **out_player,
                                                         struct NuxCapiResult **out_result);

/**
 * Explicitly select a static artboard even when it also contains authored
 * state machines or linear animations.
 */
NuxStatus nux_player_new_static(struct NuxArtboardInstance *instance,
                                struct NuxPlayer **out_player);

/**
 * Result-bearing explicit static-artboard selection.
 */
NuxStatus nux_player_new_static_with_result(struct NuxArtboardInstance *instance,
                                            struct NuxPlayer **out_player,
                                            struct NuxCapiResult **out_result);

/**
 * Apply all input changes and pointer events, then advance exactly once. The
 * operation validates the complete batch before mutation. Any unexpected
 * post-mutation failure rolls back pending script-host effects and terminally
 * poisons the shared occurrence, so no artboard/player operation can observe
 * partially committed runtime state.
 */
NuxStatus nux_player_step(struct NuxPlayer *player,
                          const struct NuxPlayerStep *step,
                          struct NuxPlayerStepResult **out_result);

NuxStatus nux_player_step_result_diagnostic(const struct NuxPlayerStepResult *result,
                                            struct NuxCapiDiagnosticView *out_diagnostic);

NuxStatus nux_player_step_result_event(const struct NuxPlayerStepResult *result,
                                       size_t index,
                                       struct NuxPlayerEventView *out_event);

NuxStatus nux_player_step_result_event_property(const struct NuxPlayerStepResult *result,
                                                size_t event_index,
                                                size_t property_index,
                                                struct NuxPlayerEventPropertyView *out_property);

NuxStatus nux_player_step_result_free(struct NuxPlayerStepResult *result);

NuxStatus nux_player_step_result_host_command(const struct NuxPlayerStepResult *result,
                                              size_t index,
                                              struct NuxHostCommandView *out_command);

NuxStatus nux_player_step_result_host_value(const struct NuxPlayerStepResult *result,
                                            size_t value_index,
                                            struct NuxHostValueView *out_value);

NuxStatus nux_player_step_result_host_value_child(const struct NuxPlayerStepResult *result,
                                                  size_t value_index,
                                                  size_t child_index,
                                                  struct NuxHostValueChildView *out_child);

NuxStatus nux_player_step_result_info(const struct NuxPlayerStepResult *result,
                                      struct NuxPlayerStepInfo *out_info);

NuxStatus nux_player_step_result_pointer(const struct NuxPlayerStepResult *result,
                                         size_t index,
                                         uint32_t *out_hit);

/**
 * Copy the product-neutral scheduling snapshot owned by one successful step.
 */
NuxStatus nux_player_step_result_scheduling(const struct NuxPlayerStepResult *result,
                                            struct NuxPlayerSchedulingInfo *out_scheduling);

NuxStatus nux_player_step_result_state_change(const struct NuxPlayerStepResult *result,
                                              size_t index,
                                              struct NuxPlayerStateChangeView *out_change);

NuxStatus nux_player_step_result_status(const struct NuxPlayerStepResult *result,
                                        NuxStatus *out_status);

NuxStatus nux_player_step_result_view_model_change(const struct NuxPlayerStepResult *result,
                                                   size_t index,
                                                   struct NuxViewModelChangeView *out_change);

NuxStatus nux_player_step_result_view_model_change_list_item(const struct NuxPlayerStepResult *result,
                                                             size_t change_index,
                                                             size_t item_index,
                                                             uint64_t *out_instance_id);

#if defined(NUX_CAPI_ANDROID_VULKAN)
NuxStatus nux_renderer_android_vulkan_free(struct NuxAndroidVulkanRenderer *renderer);
#endif

#if defined(NUX_CAPI_ANDROID_VULKAN)
/**
 * Renders a player into a newly owned CPU frame. `out_result` is optional and
 * failure-only: when supplied it stays NULL on success and owns a diagnostic
 * on failure.
 */
NuxStatus nux_renderer_android_vulkan_render_player(struct NuxAndroidVulkanRenderer *renderer,
                                                    struct NuxPlayer *player,
                                                    uint32_t clear_color,
                                                    NuxAndroidVulkanRendererFit fit,
                                                    struct NuxAndroidVulkanFrame **out_frame,
                                                    struct NuxCapiResult **out_result);
#endif

#if defined(NUX_CAPI_ANDROID_VULKAN)
/**
 * Drops renderer-owned resources from the player's retained artboard and
 * binds it to this renderer's current durable domain.
 */
NuxStatus nux_renderer_android_vulkan_reset_player_domain(const struct NuxAndroidVulkanRenderer *renderer,
                                                          struct NuxPlayer *player,
                                                          struct NuxCapiResult **out_result);
#endif

#if defined(NUX_CAPI_ANDROID_VULKAN)
/**
 * Recreates the headless target at a new non-zero extent. The durable domain
 * and generation are retained, so players already bound to this renderer
 * continue to render without an explicit reset.
 */
NuxStatus nux_renderer_android_vulkan_resize(struct NuxAndroidVulkanRenderer *renderer,
                                             uint32_t pixel_width,
                                             uint32_t pixel_height,
                                             struct NuxCapiResult **out_result);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Copies the renderer's MTLDevice with Objective-C +1 ownership.
 */
NuxStatus nux_renderer_copy_metal_device(const struct NuxRenderer *renderer,
                                         void **out_device,
                                         struct NuxCapiResult **out_result);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
NuxStatus nux_renderer_detach(struct NuxRenderer *renderer,
                              struct NuxRendererOutcome *out_outcome,
                              struct NuxCapiResult **out_result);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
NuxStatus nux_renderer_free(struct NuxRenderer *renderer);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
NuxStatus nux_renderer_info(const struct NuxRenderer *renderer,
                            struct NuxRendererInfo *out_info,
                            struct NuxCapiResult **out_result);
#endif

#if defined(NUX_CAPI_ANDROID_VULKAN)
/**
 * Creates a headless Vulkan renderer at the requested pixel extent.
 */
NuxStatus nux_renderer_new_android_vulkan(uint32_t pixel_width,
                                          uint32_t pixel_height,
                                          struct NuxAndroidVulkanRenderer **out_renderer,
                                          struct NuxCapiResult **out_result);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Creates a Metal renderer without touching UIKit, AppKit, or CAMetalLayer.
 */
NuxStatus nux_renderer_new_metal(uint32_t pixel_width,
                                 uint32_t pixel_height,
                                 struct NuxRenderer **out_renderer,
                                 struct NuxCapiResult **out_result);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Reattaches with a fresh native device domain. Players bound to an older
 * generation return HANDLE_MISMATCH until reset explicitly.
 */
NuxStatus nux_renderer_reattach(struct NuxRenderer *renderer,
                                uint32_t pixel_width,
                                uint32_t pixel_height,
                                struct NuxRendererOutcome *out_outcome,
                                struct NuxCapiResult **out_result);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Renders the player's retained artboard into a caller-acquired
 * CAMetalDrawable and schedules presentation. The drawable is borrowed only
 * until this synchronous function returns.
 */
NuxStatus nux_renderer_render_player(struct NuxRenderer *renderer,
                                     struct NuxPlayer *player,
                                     const struct NuxMetalRenderOperation *operation,
                                     struct NuxRendererOutcome *out_outcome,
                                     struct NuxCapiResult **out_result);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
/**
 * Drops renderer-owned resources from the player's retained artboard and
 * binds it to this renderer's current generation.
 */
NuxStatus nux_renderer_reset_player_domain(const struct NuxRenderer *renderer,
                                           struct NuxPlayer *player,
                                           struct NuxCapiResult **out_result);
#endif

#if (defined(NUX_CAPI_APPLE_METAL) && (defined(__APPLE__) || defined(__APPLE__)))
NuxStatus nux_renderer_resize(struct NuxRenderer *renderer,
                              uint32_t pixel_width,
                              uint32_t pixel_height,
                              struct NuxRendererOutcome *out_outcome,
                              struct NuxCapiResult **out_result);
#endif

/**
 * Advance the artboard while driving `state_machine`. The state machine must
 * have been created from the same artboard instance. `out_changed` is
 * optional and reports whether anything changed.
 */
NuxStatus nux_state_machine_instance_advance(struct NuxArtboardInstance *instance,
                                             struct NuxStateMachineInstance *state_machine,
                                             float elapsed_seconds,
                                             bool *out_changed);

/**
 * Fire a trigger input by name (NUL-terminated UTF-8). Returns
 * `NUX_STATUS_NOT_FOUND` when no input has that name and
 * `NUX_STATUS_INVALID_ARGUMENT` when the input is not a trigger.
 */
NuxStatus nux_state_machine_instance_fire_trigger(struct NuxStateMachineInstance *state_machine,
                                                  const char *name);

NuxStatus nux_state_machine_instance_free(struct NuxStateMachineInstance *state_machine);

/**
 * Instantiate the state machine at `state_machine_index` on the instance's
 * artboard. Free with `nux_state_machine_instance_free`.
 */
NuxStatus nux_state_machine_instance_new(struct NuxArtboardInstance *instance,
                                         size_t state_machine_index,
                                         struct NuxStateMachineInstance **out_state_machine);

/**
 * Instantiate only the artboard's authored, valid default state machine.
 * Returns `NUX_STATUS_NOT_FOUND` when no valid default was authored; this
 * function does not fall back to state-machine zero.
 */
NuxStatus nux_state_machine_instance_new_default(struct NuxArtboardInstance *instance,
                                                 struct NuxStateMachineInstance **out_state_machine);

/**
 * Instantiate the first state machine with an exact, case-sensitive authored
 * name. There is no default or cross-kind fallback.
 */
NuxStatus nux_state_machine_instance_new_named(struct NuxArtboardInstance *instance,
                                               struct NuxStringView name,
                                               struct NuxStateMachineInstance **out_state_machine);

/**
 * Deliver a pointer-down at artboard coordinates `(x, y)` to `state_machine`,
 * which must have been created from `instance`. `out_hit` is optional and
 * reports whether the event landed on a listener.
 */
NuxStatus nux_state_machine_instance_pointer_down(struct NuxArtboardInstance *instance,
                                                  struct NuxStateMachineInstance *state_machine,
                                                  float x,
                                                  float y,
                                                  bool *out_hit);

/**
 * Deliver a pointer-move at artboard coordinates `(x, y)` to `state_machine`,
 * which must have been created from `instance`. `out_hit` is optional and
 * reports whether the event landed on a listener.
 */
NuxStatus nux_state_machine_instance_pointer_move(struct NuxArtboardInstance *instance,
                                                  struct NuxStateMachineInstance *state_machine,
                                                  float x,
                                                  float y,
                                                  bool *out_hit);

/**
 * Deliver a pointer-up at artboard coordinates `(x, y)` to `state_machine`,
 * which must have been created from `instance`. `out_hit` is optional and
 * reports whether the event landed on a listener.
 */
NuxStatus nux_state_machine_instance_pointer_up(struct NuxArtboardInstance *instance,
                                                struct NuxStateMachineInstance *state_machine,
                                                float x,
                                                float y,
                                                bool *out_hit);

/**
 * Set a bool input by name (NUL-terminated UTF-8). Returns
 * `NUX_STATUS_NOT_FOUND` when no input has that name and
 * `NUX_STATUS_INVALID_ARGUMENT` when the input is not a bool.
 */
NuxStatus nux_state_machine_instance_set_bool(struct NuxStateMachineInstance *state_machine,
                                              const char *name,
                                              bool value);

/**
 * Set a number input by name (NUL-terminated UTF-8). Returns
 * `NUX_STATUS_NOT_FOUND` when no input has that name and
 * `NUX_STATUS_INVALID_ARGUMENT` when the input is not a number.
 */
NuxStatus nux_state_machine_instance_set_number(struct NuxStateMachineInstance *state_machine,
                                                const char *name,
                                                float value);

NuxStatus nux_view_model_catalog_authored_instance(const struct NuxViewModelCatalog *catalog,
                                                   size_t index,
                                                   struct NuxViewModelAuthoredInstanceView *out_instance);

NuxStatus nux_view_model_catalog_enum_label(const struct NuxViewModelCatalog *catalog,
                                            size_t index,
                                            struct NuxStringView *out_label);

NuxStatus nux_view_model_catalog_free(struct NuxViewModelCatalog *catalog);

NuxStatus nux_view_model_catalog_info(const struct NuxViewModelCatalog *catalog,
                                      struct NuxViewModelCatalogInfo *out_info);

NuxStatus nux_view_model_catalog_property(const struct NuxViewModelCatalog *catalog,
                                          size_t index,
                                          struct NuxViewModelPropertyView *out_property);

NuxStatus nux_view_model_catalog_schema(const struct NuxViewModelCatalog *catalog,
                                        size_t index,
                                        struct NuxViewModelSchemaView *out_schema);

NuxStatus nux_view_model_instance_free(struct NuxViewModelInstance *view_model);

NuxStatus nux_view_model_instance_identity(const struct NuxViewModelInstance *instance,
                                           uint64_t *out_identity);

NuxStatus nux_view_model_instance_new(const struct NuxFile *file,
                                      size_t schema_index,
                                      struct NuxViewModelInstance **out_instance);

NuxStatus nux_view_model_instance_new_authored(const struct NuxFile *file,
                                               size_t schema_index,
                                               size_t authored_instance_index,
                                               struct NuxViewModelInstance **out_instance);

/**
 * Instantiate the artboard's view model with generated defaults (mirrors
 * `createDefaultViewModelInstance`). Returns `NUX_STATUS_NOT_FOUND` when the
 * artboard declares no view model. Free with `nux_view_model_instance_free`.
 */
NuxStatus nux_view_model_instance_new_default(const struct NuxArtboardInstance *instance,
                                              struct NuxViewModelInstance **out_view_model);

/**
 * Instantiate the artboard's view model from the source instance at
 * `instance_index` (the order the instances appear in the file). Returns
 * `NUX_STATUS_NOT_FOUND` when the artboard declares no view model or the
 * index is out of range. Free with `nux_view_model_instance_free`.
 */
NuxStatus nux_view_model_instance_new_instance(const struct NuxArtboardInstance *instance,
                                               size_t instance_index,
                                               struct NuxViewModelInstance **out_view_model);

/**
 * Instantiate the schema's first authored instance, falling back to generated
 * property defaults when the schema has no authored instances.
 */
NuxStatus nux_view_model_instance_new_schema_default(const struct NuxFile *file,
                                                     size_t schema_index,
                                                     struct NuxViewModelInstance **out_instance);

/**
 * Set a boolean property by NUL-terminated UTF-8 name path (`/`-separated for
 * nested view models). Returns `NUX_STATUS_NOT_FOUND` when no settable
 * boolean property matches the path.
 */
NuxStatus nux_view_model_instance_set_bool(struct NuxViewModelInstance *view_model,
                                           const char *name_path,
                                           bool value);

/**
 * Set a number property by NUL-terminated UTF-8 name path (`/`-separated for
 * nested view models). Returns `NUX_STATUS_NOT_FOUND` when no settable number
 * property matches the path.
 *
 * Note: for the mutation to reach the artboard, call
 * `nux_artboard_instance_bind_view_model` after setting and before advancing.
 */
NuxStatus nux_view_model_instance_set_number(struct NuxViewModelInstance *view_model,
                                             const char *name_path,
                                             float value);

/**
 * Set a string property by NUL-terminated UTF-8 name path (`/`-separated for
 * nested view models). `value` is a NUL-terminated UTF-8 string. Returns
 * `NUX_STATUS_NOT_FOUND` when no settable string property matches the path.
 */
NuxStatus nux_view_model_instance_set_string(struct NuxViewModelInstance *view_model,
                                             const char *name_path,
                                             const char *value);

NuxStatus nux_view_model_instance_share(const struct NuxViewModelInstance *instance,
                                        struct NuxViewModelInstance **out_instance);

NuxStatus nux_view_model_instance_snapshot(const struct NuxViewModelInstance *instance,
                                           struct NuxViewModelSnapshot **out_snapshot);

NuxStatus nux_view_model_mutate(const struct NuxViewModelMutationBatch *batch,
                                struct NuxViewModelMutationResult **out_result);

NuxStatus nux_view_model_mutation_result_change(const struct NuxViewModelMutationResult *result,
                                                size_t index,
                                                struct NuxViewModelChangeView *out_change);

NuxStatus nux_view_model_mutation_result_change_list_item(const struct NuxViewModelMutationResult *result,
                                                          size_t change_index,
                                                          size_t item_index,
                                                          uint64_t *out_instance_id);

NuxStatus nux_view_model_mutation_result_free(struct NuxViewModelMutationResult *result);

NuxStatus nux_view_model_mutation_result_info(const struct NuxViewModelMutationResult *result,
                                              struct NuxViewModelMutationResultInfo *out_info);

NuxStatus nux_view_model_snapshot_free(struct NuxViewModelSnapshot *snapshot);

NuxStatus nux_view_model_snapshot_info(const struct NuxViewModelSnapshot *snapshot,
                                       struct NuxViewModelSnapshotInfo *out_info);

NuxStatus nux_view_model_snapshot_instance(const struct NuxViewModelSnapshot *snapshot,
                                           size_t index,
                                           struct NuxViewModelSnapshotInstanceView *out_instance);

NuxStatus nux_view_model_snapshot_list_item(const struct NuxViewModelSnapshot *snapshot,
                                            size_t index,
                                            uint64_t *out_instance_id);

NuxStatus nux_view_model_snapshot_value(const struct NuxViewModelSnapshot *snapshot,
                                        size_t index,
                                        struct NuxViewModelSnapshotValueView *out_value);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NUX_CAPI_GENERATED_H */
