#ifndef NUX_CAPI_GENERATED_H
#define NUX_CAPI_GENERATED_H

/* Generated by cbindgen. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Increment only for a breaking change to the exported C contract.
 */
#define NUX_CAPI_ABI_VERSION 1

typedef enum NuxStatus {
  NUX_STATUS_OK = 0,
  NUX_STATUS_NULL_ARGUMENT = 1,
  NUX_STATUS_IMPORT_ERROR = 2,
  NUX_STATUS_NOT_FOUND = 3,
  NUX_STATUS_RUNTIME_ERROR = 4,
  NUX_STATUS_INVALID_ARGUMENT = 5,
  NUX_STATUS_ABI_MISMATCH = 6,
} NuxStatus;

/**
 * Owned artboard instance. The [`NuxFile`] it was created from must stay
 * alive (not freed) for as long as this instance exists.
 */
typedef struct NuxArtboardInstance NuxArtboardInstance;

typedef struct NuxFile NuxFile;

/**
 * Render resources retained across draws of one artboard instance.
 */
typedef struct NuxRenderCache NuxRenderCache;

/**
 * Owned state machine instance. Advance it through the
 * [`NuxArtboardInstance`] it was created from.
 */
typedef struct NuxStateMachineInstance NuxStateMachineInstance;

/**
 * Owned view-model context for driving an artboard's data binds.
 *
 * Unlike [`NuxArtboardInstance`], this handle owns a private copy of the
 * view model's values and does **not** borrow the [`NuxFile`] it came from,
 * so it participates in no liveness ordering: it may be freed before or after
 * its originating file and artboard instance. It is only meaningful when bound
 * back (via `nux_artboard_instance_bind_view_model`) to the artboard instance
 * it was created from, which must still be alive at bind time.
 */
typedef struct NuxViewModelInstance NuxViewModelInstance;

/**
 * Borrowed view of a [`RawPath`]: `verbs` holds `NuxPathVerb` values and
 * `points` holds `point_count` interleaved x,y pairs. Only valid for the
 * duration of the callback it is passed to.
 */
typedef struct NuxRawPathView {
  const uint8_t *verbs;
  size_t verb_count;
  const float *points;
  size_t point_count;
} NuxRawPathView;

/**
 * C mirror of [`ImageSampler`] using the `NuxImageWrap`/`NuxImageFilter`
 * enum values.
 */
typedef struct NuxImageSampler {
  uint8_t wrap_x;
  uint8_t wrap_y;
  uint8_t filter;
} NuxImageSampler;

/**
 * Caller-provided render vtable mirroring the nuxie-render-api traits.
 *
 * Handles are opaque `uint64_t` values chosen by the caller; `0` is passed
 * for "no object" (for example a cleared shader). Transform arguments point
 * at six floats in `[xx, yx, xy, yy, tx, ty]` order. All callbacks may be
 * NULL.
 */
typedef struct NuxRenderCallbacks {
  void *user_data;
  uint64_t (*make_render_path)(void*, const struct NuxRawPathView*, uint8_t);
  uint64_t (*make_empty_render_path)(void*);
  uint64_t (*make_render_paint)(void*);
  uint64_t (*make_linear_gradient)(void*,
                                   float,
                                   float,
                                   float,
                                   float,
                                   const uint32_t*,
                                   const float*,
                                   size_t);
  uint64_t (*make_radial_gradient)(void*, float, float, float, const uint32_t*, const float*, size_t);
  uint64_t (*make_render_buffer)(void*, uint8_t, uint8_t, size_t);
  uint64_t (*decode_image)(void*, const uint8_t*, size_t, uint32_t*, uint32_t*);
  void (*release_render_path)(void*, uint64_t);
  void (*release_render_paint)(void*, uint64_t);
  void (*release_render_shader)(void*, uint64_t);
  void (*release_render_buffer)(void*, uint64_t);
  void (*release_render_image)(void*, uint64_t);
  void (*render_path_rewind)(void*, uint64_t);
  void (*render_path_fill_rule)(void*, uint64_t, uint8_t);
  void (*render_path_move_to)(void*, uint64_t, float, float);
  void (*render_path_line_to)(void*, uint64_t, float, float);
  void (*render_path_cubic_to)(void*, uint64_t, float, float, float, float, float, float);
  void (*render_path_close)(void*, uint64_t);
  void (*render_path_add_raw_path)(void*, uint64_t, const struct NuxRawPathView*);
  void (*render_path_add_render_path)(void*, uint64_t, uint64_t, const float*);
  void (*render_path_add_render_path_backwards)(void*, uint64_t, uint64_t, const float*);
  void (*render_paint_style)(void*, uint64_t, uint8_t);
  void (*render_paint_color)(void*, uint64_t, uint32_t);
  void (*render_paint_thickness)(void*, uint64_t, float);
  void (*render_paint_join)(void*, uint64_t, uint32_t);
  void (*render_paint_cap)(void*, uint64_t, uint32_t);
  void (*render_paint_feather)(void*, uint64_t, float);
  void (*render_paint_blend_mode)(void*, uint64_t, uint8_t);
  void (*render_paint_shader)(void*, uint64_t, uint64_t);
  void (*render_paint_invalidate_stroke)(void*, uint64_t);
  void (*render_buffer_unmap)(void*, uint64_t, const uint8_t*, size_t);
  void (*save)(void*);
  void (*restore)(void*);
  void (*transform)(void*, const float*);
  void (*draw_path)(void*, uint64_t, uint64_t);
  void (*clip_path)(void*, uint64_t);
  void (*draw_image)(void*, uint64_t, struct NuxImageSampler, uint8_t, float);
  void (*draw_image_mesh)(void*,
                          uint64_t,
                          struct NuxImageSampler,
                          uint64_t,
                          uint64_t,
                          uint64_t,
                          uint32_t,
                          uint32_t,
                          uint8_t,
                          float);
  void (*modulate_opacity)(void*, float);
} NuxRenderCallbacks;

typedef struct NuxStringView {
  const char *data;
  size_t len;
} NuxStringView;

/**
 * Immutable identity embedded into the shipped runtime binary.
 *
 * Both strings have process-static lifetime and are not NUL-terminated; C
 * callers must respect their explicit lengths.
 */
typedef struct NuxRuntimeInfo {
  uint32_t abi_version;
  struct NuxStringView runtime_version;
  struct NuxStringView source_revision;
} NuxRuntimeInfo;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Advance the artboard timeline without a state machine. `out_changed` is
 * optional and reports whether anything changed.
 */
enum NuxStatus nux_artboard_instance_advance(struct NuxArtboardInstance *instance,
                                             float elapsed_seconds,
                                             bool *out_changed);

/**
 * Bind `view_model` to `instance`'s own data binds and nested-artboard
 * contexts (mirrors `artboard->bindViewModelInstance(...)`). The context is
 * copied in, so call this again after mutating `view_model` to propagate the
 * change on the next advance. `view_model` must have been created from
 * `instance`.
 */
enum NuxStatus nux_artboard_instance_bind_view_model(struct NuxArtboardInstance *instance,
                                                     const struct NuxViewModelInstance *view_model);

/**
 * Draw the artboard through the caller-provided render vtable. See
 * `NuxRenderCallbacks` for the ownership and handle contract; the callbacks
 * only need to stay valid for the duration of this call.
 */
enum NuxStatus nux_artboard_instance_draw(struct NuxArtboardInstance *instance,
                                          const struct NuxRenderCallbacks *callbacks);

/**
 * Draw using render handles retained in `cache` from previous calls.
 */
enum NuxStatus nux_artboard_instance_draw_cached(struct NuxArtboardInstance *instance,
                                                 struct NuxRenderCache *cache);

void nux_artboard_instance_free(struct NuxArtboardInstance *instance);

/**
 * Instantiate the artboard at `artboard_index`. The file must outlive the
 * returned instance; free it with `nux_artboard_instance_free` before
 * freeing the file.
 */
enum NuxStatus nux_artboard_instance_new(const struct NuxFile *file,
                                         size_t artboard_index,
                                         struct NuxArtboardInstance **out_instance);

uint32_t nux_capi_abi_version(void);

enum NuxStatus nux_capi_require_abi(uint32_t required_version);

enum NuxStatus nux_capi_runtime_info(struct NuxRuntimeInfo *out_info);

enum NuxStatus nux_file_artboard_animation_count(const struct NuxFile *file,
                                                 size_t index,
                                                 size_t *out_count);

size_t nux_file_artboard_count(const struct NuxFile *file);

enum NuxStatus nux_file_artboard_name(const struct NuxFile *file,
                                      size_t index,
                                      struct NuxStringView *out_name);

enum NuxStatus nux_file_artboard_state_machine_count(const struct NuxFile *file,
                                                     size_t index,
                                                     size_t *out_count);

/**
 * Name of one of an artboard's state machines. The returned view borrows the
 * file and is valid until the file is freed.
 */
enum NuxStatus nux_file_artboard_state_machine_name(const struct NuxFile *file,
                                                    size_t artboard_index,
                                                    size_t state_machine_index,
                                                    struct NuxStringView *out_name);

void nux_file_free(struct NuxFile *file);

enum NuxStatus nux_file_import(const uint8_t *bytes, size_t len, struct NuxFile **out_file);

void nux_render_cache_free(struct NuxRenderCache *cache);

/**
 * Create a retained render cache for `instance` without invoking renderer callbacks.
 * Resource creation begins on the first cached draw, and a failed candidate is
 * discarded so the same cache can retry. The callback table and its `user_data`
 * must remain valid until `nux_render_cache_free` returns.
 */
enum NuxStatus nux_render_cache_new(const struct NuxArtboardInstance *instance,
                                    const struct NuxRenderCallbacks *callbacks,
                                    struct NuxRenderCache **out_cache);

/**
 * Advance the artboard while driving `state_machine`. The state machine must
 * have been created from the same artboard instance. `out_changed` is
 * optional and reports whether anything changed.
 */
enum NuxStatus nux_state_machine_instance_advance(struct NuxArtboardInstance *instance,
                                                  struct NuxStateMachineInstance *state_machine,
                                                  float elapsed_seconds,
                                                  bool *out_changed);

/**
 * Fire a trigger input by name (NUL-terminated UTF-8). Returns
 * `NUX_STATUS_NOT_FOUND` when no input has that name and
 * `NUX_STATUS_INVALID_ARGUMENT` when the input is not a trigger.
 */
enum NuxStatus nux_state_machine_instance_fire_trigger(struct NuxStateMachineInstance *state_machine,
                                                       const char *name);

void nux_state_machine_instance_free(struct NuxStateMachineInstance *state_machine);

/**
 * Instantiate the state machine at `state_machine_index` on the instance's
 * artboard. Free with `nux_state_machine_instance_free`.
 */
enum NuxStatus nux_state_machine_instance_new(const struct NuxArtboardInstance *instance,
                                              size_t state_machine_index,
                                              struct NuxStateMachineInstance **out_state_machine);

/**
 * Instantiate the artboard's default state machine: the one flagged in the
 * source file when present, otherwise the first state machine. Returns
 * `NUX_STATUS_NOT_FOUND` when the artboard has no state machines.
 */
enum NuxStatus nux_state_machine_instance_new_default(const struct NuxArtboardInstance *instance,
                                                      struct NuxStateMachineInstance **out_state_machine);

/**
 * Deliver a pointer-down at artboard coordinates `(x, y)` to `state_machine`,
 * which must have been created from `instance`. `out_hit` is optional and
 * reports whether the event landed on a listener.
 */
enum NuxStatus nux_state_machine_instance_pointer_down(const struct NuxArtboardInstance *instance,
                                                       struct NuxStateMachineInstance *state_machine,
                                                       float x,
                                                       float y,
                                                       bool *out_hit);

/**
 * Deliver a pointer-move at artboard coordinates `(x, y)` to `state_machine`,
 * which must have been created from `instance`. `out_hit` is optional and
 * reports whether the event landed on a listener.
 */
enum NuxStatus nux_state_machine_instance_pointer_move(const struct NuxArtboardInstance *instance,
                                                       struct NuxStateMachineInstance *state_machine,
                                                       float x,
                                                       float y,
                                                       bool *out_hit);

/**
 * Deliver a pointer-up at artboard coordinates `(x, y)` to `state_machine`,
 * which must have been created from `instance`. `out_hit` is optional and
 * reports whether the event landed on a listener.
 */
enum NuxStatus nux_state_machine_instance_pointer_up(const struct NuxArtboardInstance *instance,
                                                     struct NuxStateMachineInstance *state_machine,
                                                     float x,
                                                     float y,
                                                     bool *out_hit);

/**
 * Set a bool input by name (NUL-terminated UTF-8). Returns
 * `NUX_STATUS_NOT_FOUND` when no input has that name and
 * `NUX_STATUS_INVALID_ARGUMENT` when the input is not a bool.
 */
enum NuxStatus nux_state_machine_instance_set_bool(struct NuxStateMachineInstance *state_machine,
                                                   const char *name,
                                                   bool value);

/**
 * Set a number input by name (NUL-terminated UTF-8). Returns
 * `NUX_STATUS_NOT_FOUND` when no input has that name and
 * `NUX_STATUS_INVALID_ARGUMENT` when the input is not a number.
 */
enum NuxStatus nux_state_machine_instance_set_number(struct NuxStateMachineInstance *state_machine,
                                                     const char *name,
                                                     float value);

void nux_view_model_instance_free(struct NuxViewModelInstance *view_model);

/**
 * Instantiate the artboard's view model with generated defaults (mirrors
 * `createDefaultViewModelInstance`). Returns `NUX_STATUS_NOT_FOUND` when the
 * artboard declares no view model. Free with `nux_view_model_instance_free`.
 */
enum NuxStatus nux_view_model_instance_new_default(const struct NuxArtboardInstance *instance,
                                                   struct NuxViewModelInstance **out_view_model);

/**
 * Instantiate the artboard's view model from the source instance at
 * `instance_index` (the order the instances appear in the file). Returns
 * `NUX_STATUS_NOT_FOUND` when the artboard declares no view model or the
 * index is out of range. Free with `nux_view_model_instance_free`.
 */
enum NuxStatus nux_view_model_instance_new_instance(const struct NuxArtboardInstance *instance,
                                                    size_t instance_index,
                                                    struct NuxViewModelInstance **out_view_model);

/**
 * Set a boolean property by NUL-terminated UTF-8 name path (`/`-separated for
 * nested view models). Returns `NUX_STATUS_NOT_FOUND` when no settable
 * boolean property matches the path.
 */
enum NuxStatus nux_view_model_instance_set_bool(struct NuxViewModelInstance *view_model,
                                                const char *name_path,
                                                bool value);

/**
 * Set a number property by NUL-terminated UTF-8 name path (`/`-separated for
 * nested view models). Returns `NUX_STATUS_NOT_FOUND` when no settable number
 * property matches the path.
 *
 * Note: for the mutation to reach the artboard, call
 * `nux_artboard_instance_bind_view_model` after setting and before advancing.
 */
enum NuxStatus nux_view_model_instance_set_number(struct NuxViewModelInstance *view_model,
                                                  const char *name_path,
                                                  float value);

/**
 * Set a string property by NUL-terminated UTF-8 name path (`/`-separated for
 * nested view models). `value` is a NUL-terminated UTF-8 string. Returns
 * `NUX_STATUS_NOT_FOUND` when no settable string property matches the path.
 */
enum NuxStatus nux_view_model_instance_set_string(struct NuxViewModelInstance *view_model,
                                                  const char *name_path,
                                                  const char *value);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NUX_CAPI_GENERATED_H */
