use nuxie_schema::{
    Definition, FieldKind, Property, StoredFieldInitializer,
    core_registry_setter_field_kind_by_property_key, definition_by_name, generated::DEFINITIONS,
};
use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=../nuxie-schema/src/generated/schema.rs");
    println!("cargo:rerun-if-changed=../nuxie-schema/src/lib.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    fs::write(out_dir.join("runtime_objects.rs"), render_runtime_objects())
        .expect("write generated runtime object storage");
}

#[derive(Debug, Clone, Copy)]
struct FieldInfo {
    property: &'static Property,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum FieldStorageKind {
    Bool,
    Bytes,
    Color,
    Double,
    String,
    Uint,
}

impl FieldStorageKind {
    fn from_property(property: &Property) -> Option<Self> {
        match property.runtime_type {
            FieldKind::Bool => Some(Self::Bool),
            FieldKind::Bytes => Some(Self::Bytes),
            FieldKind::Callback => None,
            FieldKind::Color => Some(Self::Color),
            FieldKind::Double => Some(Self::Double),
            FieldKind::String => Some(Self::String),
            FieldKind::Uint => Some(Self::Uint),
        }
    }

    fn rust_type(self) -> &'static str {
        match self {
            Self::Bool => "bool",
            Self::Bytes => "Vec<u8>",
            Self::Color => "u32",
            Self::Double => "f32",
            Self::String => "super::InstanceString",
            Self::Uint => "u64",
        }
    }

    fn getter_name(self) -> &'static str {
        match self {
            Self::Bool => "bool_property",
            Self::Bytes => "bytes_property",
            Self::Color => "color_property",
            Self::Double => "double_property",
            Self::String => "string_property",
            Self::Uint => "uint_property",
        }
    }

    fn setter_name(self) -> Option<&'static str> {
        match self {
            Self::Bool => Some("set_bool_property"),
            Self::Bytes => None,
            Self::Color => Some("set_color_property"),
            Self::Double => Some("set_double_property"),
            Self::String => Some("set_string_property"),
            Self::Uint => Some("set_uint_property"),
        }
    }

    fn field_value_pattern(self) -> &'static str {
        match self {
            Self::Bool => "FieldValue::Bool(value)",
            Self::Bytes => "FieldValue::Bytes(value)",
            Self::Color => "FieldValue::Color(value)",
            Self::Double => "FieldValue::Double(value)",
            Self::String => "FieldValue::String(value)",
            Self::Uint => "FieldValue::Uint(value)",
        }
    }

    fn runtime_assignment(self, field_name: &str) -> String {
        match self {
            Self::Bool | Self::Color | Self::Double => {
                format!("self.{field_name} = Some(*value);")
            }
            Self::Bytes => format!("self.{field_name} = Some(value.raw.clone());"),
            Self::String => {
                format!(
                    "self.{field_name} = Some(super::InstanceString::from_string_value(value));"
                )
            }
            Self::Uint => format!("self.{field_name} = Some(*value);"),
        }
    }

    fn getter_expression(self, field_name: &str) -> String {
        match self {
            Self::Bool | Self::Color | Self::Double | Self::Uint => {
                format!("self.{field_name}")
            }
            Self::Bytes => format!("self.{field_name}.as_deref()"),
            Self::String => format!("self.{field_name}.as_ref().map(super::InstanceString::bytes)"),
        }
    }
}

fn render_runtime_objects() -> String {
    let definitions = DEFINITIONS
        .iter()
        .filter(|definition| definition.cloneable)
        .collect::<Vec<_>>();

    let mut out = String::new();
    out.push_str("// @generated by `nuxie-runtime` build script; do not edit by hand.\n");
    out.push_str("// Source: nuxie-schema generated Definition metadata.\n\n");
    out.push_str("use nuxie_binary::{FieldValue, RuntimeObject, RuntimeProperty};\n\n");

    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str("pub(crate) enum InstanceObjectStorage {\n");
    for definition in &definitions {
        out.push_str(&format!(
            "    {}({}Object),\n",
            definition.rust_variant, definition.rust_variant
        ));
    }
    out.push_str("}\n\n");

    out.push_str("impl InstanceObjectStorage {\n");
    out.push_str(
        "    pub(crate) fn from_runtime_object(object: &RuntimeObject) -> Option<Self> {\n",
    );
    out.push_str("        match object.type_key {\n");
    for definition in &definitions {
        out.push_str(&format!(
            "            {} => Some(Self::{}({}Object::from_runtime_object(object))),\n",
            definition.type_key.int, definition.rust_variant, definition.rust_variant
        ));
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    out.push_str("    pub(crate) fn type_key(&self) -> u16 {\n");
    out.push_str("        match self {\n");
    for definition in &definitions {
        out.push_str(&format!(
            "            Self::{}(_) => {},\n",
            definition.rust_variant, definition.type_key.int
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    render_enum_getter(
        &mut out,
        &definitions,
        FieldStorageKind::Double,
        "Option<f32>",
    );
    render_enum_getter(
        &mut out,
        &definitions,
        FieldStorageKind::Uint,
        "Option<u64>",
    );
    render_enum_getter(
        &mut out,
        &definitions,
        FieldStorageKind::Bool,
        "Option<bool>",
    );
    render_enum_getter(
        &mut out,
        &definitions,
        FieldStorageKind::Color,
        "Option<u32>",
    );
    render_enum_getter(
        &mut out,
        &definitions,
        FieldStorageKind::String,
        "Option<&[u8]>",
    );
    render_enum_getter(
        &mut out,
        &definitions,
        FieldStorageKind::Bytes,
        "Option<&[u8]>",
    );

    render_enum_setter(
        &mut out,
        &definitions,
        FieldStorageKind::Double,
        "value: f32",
        "value",
    );
    render_enum_setter(
        &mut out,
        &definitions,
        FieldStorageKind::Uint,
        "value: u64",
        "value",
    );
    render_enum_setter(
        &mut out,
        &definitions,
        FieldStorageKind::Bool,
        "value: bool",
        "value",
    );
    render_enum_setter(
        &mut out,
        &definitions,
        FieldStorageKind::Color,
        "value: u32",
        "value",
    );
    render_enum_setter(
        &mut out,
        &definitions,
        FieldStorageKind::String,
        "value: super::InstanceString",
        "value",
    );

    out.push_str("}\n\n");

    for definition in &definitions {
        render_object_struct(&mut out, definition);
    }

    out
}

fn render_enum_getter(
    out: &mut String,
    definitions: &[&'static Definition],
    kind: FieldStorageKind,
    return_type: &str,
) {
    out.push_str(&format!(
        "    pub(crate) fn {}(&self, property_key: u16) -> {} {{\n",
        kind.getter_name(),
        return_type
    ));
    out.push_str("        match self {\n");
    for definition in definitions {
        out.push_str(&format!(
            "            Self::{}(object) => object.{}(property_key),\n",
            definition.rust_variant,
            kind.getter_name()
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");
}

fn render_enum_setter(
    out: &mut String,
    definitions: &[&'static Definition],
    kind: FieldStorageKind,
    value_parameter: &str,
    value_argument: &str,
) {
    let Some(setter_name) = kind.setter_name() else {
        return;
    };
    out.push_str(&format!(
        "    pub(crate) fn {setter_name}(&mut self, property_key: u16, {value_parameter}) -> bool {{\n"
    ));
    out.push_str("        match self {\n");
    for definition in definitions {
        out.push_str(&format!(
            "            Self::{}(object) => object.{setter_name}(property_key, {value_argument}),\n",
            definition.rust_variant
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");
}

fn render_object_struct(out: &mut String, definition: &'static Definition) {
    let fields = fields_for_definition(definition);

    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str(&format!(
        "pub(crate) struct {}Object {{\n",
        definition.rust_variant
    ));
    for (key, field) in &fields {
        let kind = FieldStorageKind::from_property(field.property).expect("stored field kind");
        out.push_str(&format!("    field_{key}: Option<{}>,\n", kind.rust_type()));
    }
    out.push_str("}\n\n");

    out.push_str(&format!("impl {}Object {{\n", definition.rust_variant));
    out.push_str("    fn from_runtime_object(object: &RuntimeObject) -> Self {\n");
    out.push_str("        let mut this = Self::new();\n");
    out.push_str("        for property in &object.properties {\n");
    out.push_str("            this.apply_runtime_property(property);\n");
    out.push_str("        }\n");
    out.push_str("        this\n");
    out.push_str("    }\n\n");

    out.push_str("    fn new() -> Self {\n");
    out.push_str("        Self {\n");
    for (key, field) in &fields {
        out.push_str(&format!(
            "            field_{key}: {},\n",
            default_initializer(definition, field.property)
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    render_apply_runtime_property(out, definition, &fields);
    render_object_getters(out, definition, &fields);
    render_object_setters(out, definition, &fields);

    out.push_str("}\n\n");
}

fn render_apply_runtime_property(
    out: &mut String,
    definition: &'static Definition,
    fields: &BTreeMap<u16, FieldInfo>,
) {
    let key_to_field = key_to_field(definition, fields, |_| true);
    out.push_str("    fn apply_runtime_property(&mut self, property: &RuntimeProperty) {\n");
    out.push_str("        match property.key {\n");
    for (field_key, keys) in keys_by_field(&key_to_field) {
        let field = fields.get(&field_key).expect("field for key");
        let kind = FieldStorageKind::from_property(field.property).expect("stored field kind");
        out.push_str(&format!("            {} => {{\n", match_pattern(&keys)));
        out.push_str(&format!(
            "                if let {} = &property.value {{\n",
            kind.field_value_pattern()
        ));
        out.push_str(&format!(
            "                    {}\n",
            kind.runtime_assignment(&format!("field_{field_key}"))
        ));
        out.push_str("                }\n");
        out.push_str("            }\n");
    }
    out.push_str("            _ => {}\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");
}

fn render_object_getters(
    out: &mut String,
    definition: &'static Definition,
    fields: &BTreeMap<u16, FieldInfo>,
) {
    for (kind, return_type) in [
        (FieldStorageKind::Double, "Option<f32>"),
        (FieldStorageKind::Uint, "Option<u64>"),
        (FieldStorageKind::Bool, "Option<bool>"),
        (FieldStorageKind::Color, "Option<u32>"),
        (FieldStorageKind::String, "Option<&[u8]>"),
        (FieldStorageKind::Bytes, "Option<&[u8]>"),
    ] {
        let key_to_field = key_to_field(definition, fields, |field| {
            FieldStorageKind::from_property(field.property) == Some(kind)
        });
        out.push_str(&format!(
            "    fn {}(&self, property_key: u16) -> {} {{\n",
            kind.getter_name(),
            return_type
        ));
        out.push_str("        match property_key {\n");
        for (field_key, keys) in keys_by_field(&key_to_field) {
            out.push_str(&format!(
                "            {} => {},\n",
                match_pattern(&keys),
                kind.getter_expression(&format!("field_{field_key}"))
            ));
        }
        out.push_str("            _ => None,\n");
        out.push_str("        }\n");
        out.push_str("    }\n\n");
    }
}

fn render_object_setters(
    out: &mut String,
    definition: &'static Definition,
    fields: &BTreeMap<u16, FieldInfo>,
) {
    for (kind, value_type) in [
        (FieldStorageKind::Double, "f32"),
        (FieldStorageKind::Uint, "u64"),
        (FieldStorageKind::Bool, "bool"),
        (FieldStorageKind::Color, "u32"),
        (FieldStorageKind::String, "super::InstanceString"),
    ] {
        let Some(setter_name) = kind.setter_name() else {
            continue;
        };
        let key_to_field = key_to_field(definition, fields, |field| {
            FieldStorageKind::from_property(field.property) == Some(kind)
                && setter_kind_matches(field.property, kind)
        });
        let value_name = if key_to_field.is_empty() {
            "_value"
        } else {
            "value"
        };
        out.push_str(&format!(
            "    fn {setter_name}(&mut self, property_key: u16, {value_name}: {value_type}) -> bool {{\n"
        ));
        out.push_str("        match property_key {\n");
        for (field_key, keys) in keys_by_field(&key_to_field) {
            out.push_str(&format!(
                "            {} => super::set_optional_field(&mut self.field_{field_key}, {value_name}),\n",
                match_pattern(&keys)
            ));
        }
        out.push_str("            _ => false,\n");
        out.push_str("        }\n");
        out.push_str("    }\n\n");
    }
}

fn fields_for_definition(definition: &'static Definition) -> BTreeMap<u16, FieldInfo> {
    let mut fields = BTreeMap::new();
    for property in properties_in_resolution_order(definition) {
        if stores_runtime_field(property) {
            fields
                .entry(property.key.int)
                .or_insert(FieldInfo { property });
        }
    }
    fields
}

fn key_to_field(
    definition: &'static Definition,
    fields: &BTreeMap<u16, FieldInfo>,
    include: impl Fn(FieldInfo) -> bool,
) -> BTreeMap<u16, u16> {
    let mut key_to_field = BTreeMap::new();
    for property in properties_in_resolution_order(definition) {
        let Some(field) = fields.get(&property.key.int).copied() else {
            continue;
        };
        if !include(field) {
            continue;
        }
        key_to_field
            .entry(property.key.int)
            .or_insert(property.key.int);
        for alternate in property.alternates {
            key_to_field
                .entry(alternate.int)
                .or_insert(property.key.int);
        }
    }
    key_to_field
}

fn keys_by_field(key_to_field: &BTreeMap<u16, u16>) -> Vec<(u16, Vec<u16>)> {
    let mut grouped = BTreeMap::<u16, BTreeSet<u16>>::new();
    for (key, field_key) in key_to_field {
        grouped.entry(*field_key).or_default().insert(*key);
    }
    grouped
        .into_iter()
        .map(|(field_key, keys)| (field_key, keys.into_iter().collect()))
        .collect()
}

fn properties_in_resolution_order(definition: &'static Definition) -> Vec<&'static Property> {
    let mut properties = Vec::new();
    properties.extend(definition.properties.iter());
    for ancestor in definition.ancestors {
        let ancestor = definition_by_name(ancestor).expect("generated ancestor exists");
        properties.extend(ancestor.properties.iter());
    }
    properties
}

fn stores_runtime_field(property: &Property) -> bool {
    if property.bitmask_passthrough.is_some() {
        return false;
    }
    if FieldStorageKind::from_property(property).is_none() {
        return false;
    }
    property.stores_data || setter_kind(property).is_some()
}

fn setter_kind(property: &Property) -> Option<FieldKind> {
    core_registry_setter_field_kind_by_property_key(property.key.int).or_else(|| {
        property
            .alternates
            .iter()
            .find_map(|alternate| core_registry_setter_field_kind_by_property_key(alternate.int))
    })
}

fn setter_kind_matches(property: &Property, kind: FieldStorageKind) -> bool {
    matches!(
        (setter_kind(property), kind),
        (Some(FieldKind::Bool), FieldStorageKind::Bool)
            | (Some(FieldKind::Color), FieldStorageKind::Color)
            | (Some(FieldKind::Double), FieldStorageKind::Double)
            | (Some(FieldKind::String), FieldStorageKind::String)
            | (Some(FieldKind::Uint), FieldStorageKind::Uint)
    )
}

fn default_initializer(definition: &Definition, property: &Property) -> String {
    if definition.name == "Artboard" && property.name == "clip" {
        return "Some(true)".to_owned();
    }

    if !property.stores_field {
        return "None".to_owned();
    }

    match (*property).stored_field_initializer() {
        Some(StoredFieldInitializer::Bool(value)) => format!("Some({value})"),
        Some(StoredFieldInitializer::Color(value)) => format!("Some({value}u32)"),
        Some(StoredFieldInitializer::Double(value)) => format!("Some({value:?}f32)"),
        Some(StoredFieldInitializer::String(value)) => {
            format!(
                "Some(super::InstanceString::from_static({}))",
                rust_string(value)
            )
        }
        Some(StoredFieldInitializer::Uint(value)) => format!("Some({value}u64)"),
        None => "None".to_owned(),
    }
}

fn match_pattern(keys: &[u16]) -> String {
    keys.iter()
        .map(u16::to_string)
        .collect::<Vec<_>>()
        .join(" | ")
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}
