// Target-neutral JavaScript host for the pinned Dawn WebGPU C ABI used by the
// exact Rust translation. Descriptor offsets and enum values are generated by
// the same pinned Dawn headers as the translated Rust declarations.

let preparedAdapter;
let preparedDevice;
let preparedCanvas;
let preparedSurfaceTexture;
let preparedSurfaceWidth = 0;
let preparedSurfaceHeight = 0;
let preparedCaptureBuffer;
let preparedCaptureBuffers = [];
let preparedCaptureBytesPerRow = 0;
let destroyAfterSubmit = false;

export async function prepareWebGpu(canvas) {
  if (!navigator.gpu) {
    throw new Error("WebGPU is unavailable in this browser");
  }
  const adapter = await navigator.gpu.requestAdapter({
    powerPreference: "high-performance",
  });
  if (!adapter) {
    throw new Error("WebGPU did not return an adapter");
  }
  const requiredFeatures = adapter.features.has("clip-distances")
    ? ["clip-distances"]
    : [];
  preparedAdapter = adapter;
  preparedDevice = await adapter.requestDevice({ requiredFeatures });
  preparedCanvas = canvas;
  destroyAfterSubmit = false;
}

export async function waitForWebGpu() {
  if (!preparedDevice) return;
  await preparedDevice.queue.onSubmittedWorkDone();
}

export async function captureWebGpuPixels() {
  if (!preparedDevice || !preparedSurfaceTexture) {
    throw new Error("WebGPU replay did not produce a surface texture");
  }
  const buffer = preparedCaptureBuffer;
  const bytesPerRow = preparedCaptureBytesPerRow;
  if (!buffer) throw new Error("WebGPU replay did not submit a capturable frame");
  await buffer.mapAsync(GPUMapMode.READ);
  const mapped = new Uint8Array(buffer.getMappedRange());
  const pixels = new Uint8Array(preparedSurfaceWidth * preparedSurfaceHeight * 4);
  const packedBytesPerRow = preparedSurfaceWidth * 4;
  for (let row = 0; row < preparedSurfaceHeight; row += 1) {
    pixels.set(
      mapped.subarray(row * bytesPerRow, row * bytesPerRow + packedBytesPerRow),
      row * packedBytesPerRow,
    );
  }
  buffer.unmap();
  return {
    width: preparedSurfaceWidth,
    height: preparedSurfaceHeight,
    pixels,
  };
}

export function releaseWebGpu() {
  if (!preparedDevice) return;
  if (destroyAfterSubmit) {
    preparedDevice.destroy();
    preparedDevice = undefined;
    preparedSurfaceTexture = undefined;
    for (const buffer of preparedCaptureBuffers) buffer.destroy();
    preparedCaptureBuffer = undefined;
    preparedCaptureBuffers = [];
    destroyAfterSubmit = false;
  }
}

export function createWebGpuImports(getWasm) {
  const objects = new Map();
  const mappedRanges = new Map();
  let nextHandle = 4;
  let nextFuture = 1n;

  const wasm = () => getWasm();
  const memory = () => wasm().memory.buffer;
  const u8 = () => new Uint8Array(memory());
  const u16 = () => new Uint16Array(memory());
  const u32 = () => new Uint32Array(memory());
  const i32 = () => new Int32Array(memory());
  const f32 = () => new Float32Array(memory());
  const f64 = () => new Float64Array(memory());

  const addObject = (value, metadata = {}) => {
    const handle = nextHandle;
    nextHandle += 4;
    objects.set(handle, { value, references: 1, ...metadata });
    return handle;
  };
  const entry = (handle) => (handle ? objects.get(handle) : undefined);
  const object = (handle) => entry(handle)?.value;
  const addRef = (handle) => {
    const value = entry(handle);
    if (value) value.references += 1;
  };
  const release = (handle) => {
    const value = entry(handle);
    if (!value) return;
    value.references -= 1;
    if (value.references === 0) objects.delete(handle);
  };
  const readU64 = (pointer) =>
    u32()[pointer >>> 2] + i32()[(pointer + 4) >>> 2] * 4294967296;
  const writeU64 = (pointer, value) => {
    u32()[pointer >>> 2] = value;
    const lower = u32()[pointer >>> 2];
    u32()[(pointer + 4) >>> 2] = (value - lower) / 4294967296;
  };
  const readStringView = (pointer, optional = false) => {
    const data = u32()[pointer >>> 2];
    let length = u32()[(pointer + 4) >>> 2];
    if (!data) return optional ? undefined : "";
    if (length === 0xffffffff) {
      length = 0;
      while (u8()[data + length]) length += 1;
    }
    return new TextDecoder().decode(u8().subarray(data, data + length));
  };
  const writeStringView = (pointer, value) => {
    const bytes = new TextEncoder().encode(value);
    const data = wasm().__wbindgen_malloc(bytes.length, 1);
    u8().set(bytes, data);
    u32()[pointer >>> 2] = data;
    u32()[(pointer + 4) >>> 2] = bytes.length;
    return { data, length: bytes.length };
  };
  const emptyStringView = () => {
    const pointer = wasm().__wbindgen_malloc(8, 4);
    u32()[pointer >>> 2] = 0;
    u32()[(pointer + 4) >>> 2] = 0;
    return pointer;
  };
  const invokeCallback = (callbackInfo, ...arguments_) => {
    const callback = u32()[(callbackInfo + 8) >>> 2];
    const userdata1 = u32()[(callbackInfo + 12) >>> 2];
    const userdata2 = u32()[(callbackInfo + 16) >>> 2];
    const message = emptyStringView();
    try {
      wasm().__indirect_function_table
        .get(callback)(...arguments_, message, userdata1, userdata2);
    } finally {
      wasm().__wbindgen_free(message, 8, 4);
    }
  };

  const AddressMode = [, "clamp-to-edge", "repeat", "mirror-repeat"];
  const BlendFactor = [
    , "zero", "one", "src", "one-minus-src", "src-alpha",
    "one-minus-src-alpha", "dst", "one-minus-dst", "dst-alpha",
    "one-minus-dst-alpha", "src-alpha-saturated", "constant",
    "one-minus-constant", "src1", "one-minus-src1", "src1-alpha",
    "one-minus-src1-alpha",
  ];
  const BlendOperation = [, "add", "subtract", "reverse-subtract", "min", "max"];
  const BufferBindingType = [, , "uniform", "storage", "read-only-storage"];
  const CompareFunction = [
    , "never", "less", "equal", "less-equal", "greater", "not-equal",
    "greater-equal", "always",
  ];
  const CompositeAlphaMode = [, "opaque", "premultiplied", "unpremultiplied", "inherit"];
  const CullMode = [, "none", "front", "back"];
  const FeatureName = {
    1: "core-features-and-limits",
    2: "depth-clip-control",
    3: "depth32float-stencil8",
    4: "texture-compression-bc",
    5: "texture-compression-bc-sliced-3d",
    6: "texture-compression-etc2",
    7: "texture-compression-astc",
    8: "texture-compression-astc-sliced-3d",
    9: "timestamp-query",
    10: "indirect-first-instance",
    11: "shader-f16",
    12: "rg11b10ufloat-renderable",
    13: "bgra8unorm-storage",
    14: "float32-filterable",
    15: "float32-blendable",
    16: "clip-distances",
    17: "dual-source-blending",
    18: "subgroups",
    19: "texture-formats-tier1",
    20: "texture-formats-tier2",
    21: "primitive-index",
    22: "texture-component-swizzle",
  };
  const FilterMode = [, "nearest", "linear"];
  const FrontFace = [, "ccw", "cw"];
  const IndexFormat = [, "uint16", "uint32"];
  const LoadOp = [, "load", "clear"];
  const MipmapFilterMode = [, "nearest", "linear"];
  const PrimitiveTopology = [
    , "point-list", "line-list", "line-strip", "triangle-list", "triangle-strip",
  ];
  const SamplerBindingType = [, , "filtering", "non-filtering", "comparison"];
  const StencilOperation = [
    , "keep", "zero", "replace", "invert", "increment-clamp",
    "decrement-clamp", "increment-wrap", "decrement-wrap",
  ];
  const StorageTextureAccess = [, , "write-only", "read-only", "read-write"];
  const StoreOp = [, "store", "discard"];
  const TextureAspect = [, "all", "stencil-only", "depth-only"];
  const TextureDimension = [, "1d", "2d", "3d"];
  const TextureFormat = [
    , "r8unorm", "r8snorm", "r8uint", "r8sint", "r16unorm", "r16snorm",
    "r16uint", "r16sint", "r16float", "rg8unorm", "rg8snorm", "rg8uint",
    "rg8sint", "r32float", "r32uint", "r32sint", "rg16unorm", "rg16snorm",
    "rg16uint", "rg16sint", "rg16float", "rgba8unorm", "rgba8unorm-srgb",
    "rgba8snorm", "rgba8uint", "rgba8sint", "bgra8unorm", "bgra8unorm-srgb",
    "rgb10a2uint", "rgb10a2unorm", "rg11b10ufloat", "rgb9e5ufloat",
    "rg32float", "rg32uint", "rg32sint", "rgba16unorm", "rgba16snorm",
    "rgba16uint", "rgba16sint", "rgba16float", "rgba32float", "rgba32uint",
    "rgba32sint", "stencil8", "depth16unorm", "depth24plus",
    "depth24plus-stencil8", "depth32float", "depth32float-stencil8",
  ];
  const TextureSampleType = [, , "float", "unfilterable-float", "depth", "sint", "uint"];
  const TextureViewDimension = [, "1d", "2d", "2d-array", "cube", "cube-array", "3d"];
  const VertexFormat = [
    , "uint8", "uint8x2", "uint8x4", "sint8", "sint8x2", "sint8x4",
    "unorm8", "unorm8x2", "unorm8x4", "snorm8", "snorm8x2", "snorm8x4",
    "uint16", "uint16x2", "uint16x4", "sint16", "sint16x2", "sint16x4",
    "unorm16", "unorm16x2", "unorm16x4", "snorm16", "snorm16x2",
    "snorm16x4", "float16", "float16x2", "float16x4", "float32",
    "float32x2", "float32x3", "float32x4", "uint32", "uint32x2",
    "uint32x3", "uint32x4", "sint32", "sint32x2", "sint32x3", "sint32x4",
    "unorm10-10-10-2", "unorm8x4-bgra",
  ];
  const VertexStepMode = [, "vertex", "instance"];

  const extent3D = (pointer) => ({
    width: u32()[pointer >>> 2],
    height: u32()[(pointer + 4) >>> 2],
    depthOrArrayLayers: u32()[(pointer + 8) >>> 2],
  });
  const origin3D = (pointer) => ({
    x: u32()[pointer >>> 2],
    y: u32()[(pointer + 4) >>> 2],
    z: u32()[(pointer + 8) >>> 2],
  });
  const color = (pointer) => ({
    r: f64()[pointer >>> 3],
    g: f64()[(pointer + 8) >>> 3],
    b: f64()[(pointer + 16) >>> 3],
    a: f64()[(pointer + 24) >>> 3],
  });
  const texelCopyTexture = (pointer) => ({
    texture: object(u32()[pointer >>> 2]),
    mipLevel: u32()[(pointer + 4) >>> 2],
    origin: origin3D(pointer + 8),
    aspect: TextureAspect[i32()[(pointer + 20) >>> 2]],
  });
  const texelCopyLayout = (pointer) => {
    const bytesPerRow = u32()[(pointer + 8) >>> 2];
    const rowsPerImage = u32()[(pointer + 12) >>> 2];
    return {
      offset: readU64(pointer),
      bytesPerRow: bytesPerRow === 0xffffffff ? undefined : bytesPerRow,
      rowsPerImage: rowsPerImage === 0xffffffff ? undefined : rowsPerImage,
    };
  };
  const texelCopyBuffer = (pointer) => ({
    ...texelCopyLayout(pointer),
    buffer: object(u32()[(pointer + 16) >>> 2]),
  });
  const pipelineConstants = (count, pointer) => {
    if (!count) return undefined;
    const constants = {};
    for (let index = 0; index < count; index += 1) {
      const entryPointer = pointer + index * 24;
      constants[readStringView(entryPointer + 4)] = f64()[(entryPointer + 16) >>> 3];
    }
    return constants;
  };
  const pipelineLayout = (handle) => (handle ? object(handle) : "auto");

  const renderPipelineDescriptor = (pointer) => {
    const blendComponent = (componentPointer) => ({
      operation: BlendOperation[i32()[componentPointer >>> 2]],
      srcFactor: BlendFactor[i32()[(componentPointer + 4) >>> 2]],
      dstFactor: BlendFactor[i32()[(componentPointer + 8) >>> 2]],
    });
    const blendState = (statePointer) =>
      statePointer
        ? { color: blendComponent(statePointer), alpha: blendComponent(statePointer + 12) }
        : undefined;
    const vertexAttributes = (count, attributesPointer) => {
      const attributes = [];
      for (let index = 0; index < count; index += 1) {
        const attributePointer = attributesPointer + index * 24;
        attributes.push({
          format: VertexFormat[i32()[(attributePointer + 4) >>> 2]],
          offset: readU64(attributePointer + 8),
          shaderLocation: u32()[(attributePointer + 16) >>> 2],
        });
      }
      return attributes;
    };
    const vertexBuffers = (count, buffersPointer) => {
      if (!count) return undefined;
      const buffers = [];
      for (let index = 0; index < count; index += 1) {
        const bufferPointer = buffersPointer + index * 24;
        const stepMode = VertexStepMode[i32()[(bufferPointer + 4) >>> 2]];
        const attributeCount = u32()[(bufferPointer + 16) >>> 2];
        buffers.push(
          !stepMode && !attributeCount
            ? null
            : {
                arrayStride: readU64(bufferPointer + 8),
                stepMode,
                attributes: vertexAttributes(
                  attributeCount,
                  u32()[(bufferPointer + 20) >>> 2],
                ),
              },
        );
      }
      return buffers;
    };
    const vertexPointer = pointer + 16;
    const vertex = {
      module: object(u32()[(vertexPointer + 4) >>> 2]),
      entryPoint: readStringView(vertexPointer + 8, true),
      constants: pipelineConstants(
        u32()[(vertexPointer + 16) >>> 2],
        u32()[(vertexPointer + 20) >>> 2],
      ),
      buffers: vertexBuffers(
        u32()[(vertexPointer + 24) >>> 2],
        u32()[(vertexPointer + 28) >>> 2],
      ),
    };
    const primitivePointer = pointer + 48;
    const primitive = {
      topology: PrimitiveTopology[i32()[(primitivePointer + 4) >>> 2]],
      stripIndexFormat: IndexFormat[i32()[(primitivePointer + 8) >>> 2]],
      frontFace: FrontFace[i32()[(primitivePointer + 12) >>> 2]],
      cullMode: CullMode[i32()[(primitivePointer + 16) >>> 2]],
      unclippedDepth: Boolean(u32()[(primitivePointer + 20) >>> 2]),
    };
    const depthPointer = u32()[(pointer + 72) >>> 2];
    let depthStencil;
    if (depthPointer) {
      const stencilFace = (facePointer) => ({
        compare: CompareFunction[i32()[facePointer >>> 2]],
        failOp: StencilOperation[i32()[(facePointer + 4) >>> 2]],
        depthFailOp: StencilOperation[i32()[(facePointer + 8) >>> 2]],
        passOp: StencilOperation[i32()[(facePointer + 12) >>> 2]],
      });
      depthStencil = {
        format: TextureFormat[i32()[(depthPointer + 4) >>> 2]],
        depthWriteEnabled: Boolean(u32()[(depthPointer + 8) >>> 2]),
        depthCompare: CompareFunction[i32()[(depthPointer + 12) >>> 2]],
        stencilFront: stencilFace(depthPointer + 16),
        stencilBack: stencilFace(depthPointer + 32),
        stencilReadMask: u32()[(depthPointer + 48) >>> 2],
        stencilWriteMask: u32()[(depthPointer + 52) >>> 2],
        depthBias: i32()[(depthPointer + 56) >>> 2],
        depthBiasSlopeScale: f32()[(depthPointer + 60) >>> 2],
        depthBiasClamp: f32()[(depthPointer + 64) >>> 2],
      };
    }
    const multisamplePointer = pointer + 76;
    const multisample = {
      count: u32()[(multisamplePointer + 4) >>> 2],
      mask: u32()[(multisamplePointer + 8) >>> 2],
      alphaToCoverageEnabled: Boolean(u32()[(multisamplePointer + 12) >>> 2]),
    };
    const fragmentPointer = u32()[(pointer + 92) >>> 2];
    let fragment;
    if (fragmentPointer) {
      const targetCount = u32()[(fragmentPointer + 24) >>> 2];
      const targetsPointer = u32()[(fragmentPointer + 28) >>> 2];
      const targets = [];
      for (let index = 0; index < targetCount; index += 1) {
        const targetPointer = targetsPointer + index * 24;
        const format = TextureFormat[i32()[(targetPointer + 4) >>> 2]];
        targets.push(
          format
            ? {
                format,
                blend: blendState(u32()[(targetPointer + 8) >>> 2]),
                writeMask: u32()[(targetPointer + 16) >>> 2],
              }
            : undefined,
        );
      }
      fragment = {
        module: object(u32()[(fragmentPointer + 4) >>> 2]),
        entryPoint: readStringView(fragmentPointer + 8, true),
        constants: pipelineConstants(
          u32()[(fragmentPointer + 16) >>> 2],
          u32()[(fragmentPointer + 20) >>> 2],
        ),
        targets,
      };
    }
    return {
      label: readStringView(pointer + 4, true),
      layout: pipelineLayout(u32()[(pointer + 12) >>> 2]),
      vertex,
      primitive,
      depthStencil,
      multisample,
      fragment,
    };
  };

  const fillLimits = (limits, pointer) => {
    const u32Limits = {
      maxTextureDimension1D: 4,
      maxTextureDimension2D: 8,
      maxTextureDimension3D: 12,
      maxTextureArrayLayers: 16,
      maxBindGroups: 20,
      maxBindGroupsPlusVertexBuffers: 24,
      maxBindingsPerBindGroup: 28,
      maxDynamicUniformBuffersPerPipelineLayout: 32,
      maxDynamicStorageBuffersPerPipelineLayout: 36,
      maxSampledTexturesPerShaderStage: 40,
      maxSamplersPerShaderStage: 44,
      maxStorageBuffersPerShaderStage: 48,
      maxStorageTexturesPerShaderStage: 52,
      maxUniformBuffersPerShaderStage: 56,
      minUniformBufferOffsetAlignment: 80,
      minStorageBufferOffsetAlignment: 84,
      maxVertexBuffers: 88,
      maxVertexAttributes: 104,
      maxVertexBufferArrayStride: 108,
      maxInterStageShaderVariables: 112,
      maxColorAttachments: 116,
      maxColorAttachmentBytesPerSample: 120,
      maxComputeWorkgroupStorageSize: 124,
      maxComputeInvocationsPerWorkgroup: 128,
      maxComputeWorkgroupSizeX: 132,
      maxComputeWorkgroupSizeY: 136,
      maxComputeWorkgroupSizeZ: 140,
      maxComputeWorkgroupsPerDimension: 144,
      maxImmediateSize: 148,
    };
    for (const [name, offset] of Object.entries(u32Limits)) {
      u32()[(pointer + offset) >>> 2] = Number(limits[name] ?? 0);
    }
    for (const [name, offset] of [
      ["maxUniformBufferBindingSize", 64],
      ["maxStorageBufferBindingSize", 72],
      ["maxBufferSize", 96],
    ]) {
      writeU64(pointer + offset, Number(limits[name] ?? 0));
    }
  };

  const noOp = () => {};
  const imports = {
    wgpuCreateInstance: () => addObject({ kind: "instance" }),
    wgpuInstanceRequestAdapter: (_instance, _options, callbackInfo) => {
      const handle = addObject(preparedAdapter);
      invokeCallback(callbackInfo, 1, handle);
      return nextFuture++;
    },
    wgpuAdapterRequestDevice: (_adapter, _descriptor, callbackInfo) => {
      const deviceHandle = addObject(preparedDevice);
      const queueHandle = addObject(preparedDevice.queue);
      entry(deviceHandle).queueHandle = queueHandle;
      invokeCallback(callbackInfo, 1, deviceHandle);
      return nextFuture++;
    },
    wgpuAdapterGetInfo: (_adapter, infoPointer) => {
      const info = preparedAdapter?.info ?? {};
      const values = [
        info.vendor ?? "",
        info.architecture ?? "",
        info.device ?? "",
        info.description ?? "",
      ];
      values.forEach((value, index) =>
        writeStringView(infoPointer + 4 + index * 8, value),
      );
      i32()[(infoPointer + 36) >>> 2] = 2;
      i32()[(infoPointer + 40) >>> 2] = preparedAdapter?.isFallbackAdapter ? 3 : 4;
      return 1;
    },
    wgpuAdapterHasFeature: (_adapter, feature) =>
      preparedAdapter?.features.has(FeatureName[feature]) ? 1 : 0,
    wgpuDeviceHasFeature: (device, feature) =>
      object(device)?.features.has(FeatureName[feature]) ? 1 : 0,
    wgpuDeviceGetQueue: (device) => entry(device)?.queueHandle ?? 0,
    wgpuDeviceGetLimits: (device, limitsPointer) => {
      fillLimits(object(device).limits, limitsPointer);
      return 1;
    },
    wgpuInstanceCreateSurface: (_instance, descriptor) => {
      const chain = u32()[descriptor >>> 2];
      const selector = chain ? readStringView(chain + 8) : "#canvas";
      const canvas = document.querySelector(selector) ?? preparedCanvas;
      const context = canvas?.getContext("webgpu");
      return context ? addObject(context, { canvas }) : 0;
    },
    wgpuSurfaceGetCapabilities: (_surface, _adapter, capabilities) => {
      const formatPointer = wasm().__wbindgen_malloc(4, 4);
      i32()[formatPointer >>> 2] = 22;
      u32()[(capabilities + 8) >>> 2] = 0x1f;
      u32()[(capabilities + 16) >>> 2] = 1;
      u32()[(capabilities + 20) >>> 2] = formatPointer;
      u32()[(capabilities + 24) >>> 2] = 0;
      u32()[(capabilities + 28) >>> 2] = 0;
      u32()[(capabilities + 32) >>> 2] = 0;
      u32()[(capabilities + 36) >>> 2] = 0;
      return 1;
    },
    wgpuSurfaceConfigure: (surface, configuration) => {
      const value = entry(surface);
      const width = u32()[(configuration + 24) >>> 2];
      const height = u32()[(configuration + 28) >>> 2];
      if (width) value.canvas.width = width;
      if (height) value.canvas.height = height;
      value.value.configure({
        device: object(u32()[(configuration + 4) >>> 2]),
        format: TextureFormat[i32()[(configuration + 8) >>> 2]],
        usage: u32()[(configuration + 16) >>> 2],
        alphaMode: CompositeAlphaMode[i32()[(configuration + 40) >>> 2]],
      });
    },
    wgpuSurfaceGetCurrentTexture: (surface, output) => {
      const value = entry(surface);
      try {
        const texture = value.value.getCurrentTexture();
        preparedSurfaceTexture = texture;
        preparedSurfaceWidth = value.canvas.width;
        preparedSurfaceHeight = value.canvas.height;
        const handle = addObject(texture, {
          width: value.canvas.width,
          height: value.canvas.height,
          mipLevelCount: 1,
        });
        u32()[(output + 4) >>> 2] = handle;
        i32()[(output + 8) >>> 2] = 1;
      } catch (_error) {
        u32()[(output + 4) >>> 2] = 0;
        i32()[(output + 8) >>> 2] = 6;
      }
    },
    wgpuDeviceCreateBuffer: (device, descriptor) => {
      const mappedAtCreation = Boolean(u32()[(descriptor + 32) >>> 2]);
      const buffer = object(device).createBuffer({
        label: readStringView(descriptor + 4, true),
        usage: u32()[(descriptor + 16) >>> 2],
        size: readU64(descriptor + 24),
        mappedAtCreation,
      });
      const handle = addObject(buffer);
      if (mappedAtCreation) mappedRanges.set(handle, []);
      return handle;
    },
    wgpuBufferGetMappedRange: (buffer, offset, size) => {
      const mapped = object(buffer).getMappedRange(offset, size === -1 ? undefined : size);
      const pointer = wasm().__wbindgen_malloc(mapped.byteLength, 16);
      u8().fill(0, pointer, pointer + mapped.byteLength);
      mappedRanges.get(buffer)?.push(() => {
        new Uint8Array(mapped).set(u8().subarray(pointer, pointer + mapped.byteLength));
        wasm().__wbindgen_free(pointer, mapped.byteLength, 16);
      });
      return pointer;
    },
    wgpuBufferUnmap: (buffer) => {
      for (const flush of mappedRanges.get(buffer) ?? []) flush();
      mappedRanges.delete(buffer);
      object(buffer).unmap();
    },
    wgpuDeviceCreateTexture: (device, descriptor) => {
      const size = extent3D(descriptor + 28);
      const mipLevelCount = u32()[(descriptor + 44) >>> 2];
      const texture = object(device).createTexture({
        label: readStringView(descriptor + 4, true),
        usage: u32()[(descriptor + 16) >>> 2],
        dimension: TextureDimension[i32()[(descriptor + 24) >>> 2]],
        size,
        format: TextureFormat[i32()[(descriptor + 40) >>> 2]],
        mipLevelCount,
        sampleCount: u32()[(descriptor + 48) >>> 2],
      });
      return addObject(texture, { width: size.width, height: size.height, mipLevelCount });
    },
    wgpuTextureCreateView: (texture, descriptor) => {
      let value;
      if (descriptor) {
        const mipLevelCount = u32()[(descriptor + 24) >>> 2];
        const arrayLayerCount = u32()[(descriptor + 32) >>> 2];
        value = {
          label: readStringView(descriptor + 4, true),
          format: TextureFormat[i32()[(descriptor + 12) >>> 2]],
          dimension: TextureViewDimension[i32()[(descriptor + 16) >>> 2]],
          baseMipLevel: u32()[(descriptor + 20) >>> 2],
          mipLevelCount: mipLevelCount === 0xffffffff ? undefined : mipLevelCount,
          baseArrayLayer: u32()[(descriptor + 28) >>> 2],
          arrayLayerCount: arrayLayerCount === 0xffffffff ? undefined : arrayLayerCount,
          aspect: TextureAspect[i32()[(descriptor + 36) >>> 2]],
          usage: u32()[(descriptor + 40) >>> 2] || undefined,
        };
      }
      return addObject(object(texture).createView(value));
    },
    wgpuTextureGetWidth: (texture) => entry(texture)?.width ?? object(texture)?.width ?? 0,
    wgpuTextureGetHeight: (texture) => entry(texture)?.height ?? object(texture)?.height ?? 0,
    wgpuTextureGetMipLevelCount: (texture) =>
      entry(texture)?.mipLevelCount ?? object(texture)?.mipLevelCount ?? 1,
    wgpuDeviceCreateSampler: (device, descriptor) => {
      let value;
      if (descriptor) {
        value = {
          label: readStringView(descriptor + 4, true),
          addressModeU: AddressMode[i32()[(descriptor + 12) >>> 2]],
          addressModeV: AddressMode[i32()[(descriptor + 16) >>> 2]],
          addressModeW: AddressMode[i32()[(descriptor + 20) >>> 2]],
          magFilter: FilterMode[i32()[(descriptor + 24) >>> 2]],
          minFilter: FilterMode[i32()[(descriptor + 28) >>> 2]],
          mipmapFilter: MipmapFilterMode[i32()[(descriptor + 32) >>> 2]],
          lodMinClamp: f32()[(descriptor + 36) >>> 2],
          lodMaxClamp: f32()[(descriptor + 40) >>> 2],
          compare: CompareFunction[i32()[(descriptor + 44) >>> 2]],
          maxAnisotropy: u16()[(descriptor + 48) >>> 1],
        };
      }
      return addObject(object(device).createSampler(value));
    },
    wgpuDeviceCreateShaderModule: (device, descriptor) => {
      const chain = u32()[descriptor >>> 2];
      return addObject(
        object(device).createShaderModule({
          label: readStringView(descriptor + 4, true),
          code: chain ? readStringView(chain + 8) : "",
        }),
      );
    },
    wgpuDeviceCreateBindGroupLayout: (device, descriptor) => {
      const count = u32()[(descriptor + 12) >>> 2];
      const pointer = u32()[(descriptor + 16) >>> 2];
      const entries = [];
      for (let index = 0; index < count; index += 1) {
        const item = pointer + index * 88;
        const bufferType = u32()[(item + 28) >>> 2];
        const samplerType = u32()[(item + 52) >>> 2];
        const textureType = u32()[(item + 60) >>> 2];
        const storageType = u32()[(item + 76) >>> 2];
        entries.push({
          binding: u32()[(item + 4) >>> 2],
          visibility: u32()[(item + 8) >>> 2],
          buffer: bufferType
            ? {
                type: BufferBindingType[bufferType],
                hasDynamicOffset: Boolean(u32()[(item + 32) >>> 2]),
                minBindingSize: readU64(item + 40),
              }
            : undefined,
          sampler: samplerType ? { type: SamplerBindingType[samplerType] } : undefined,
          texture: textureType
            ? {
                sampleType: TextureSampleType[textureType],
                viewDimension: TextureViewDimension[i32()[(item + 64) >>> 2]],
                multisampled: Boolean(u32()[(item + 68) >>> 2]),
              }
            : undefined,
          storageTexture: storageType
            ? {
                access: StorageTextureAccess[storageType],
                format: TextureFormat[i32()[(item + 80) >>> 2]],
                viewDimension: TextureViewDimension[i32()[(item + 84) >>> 2]],
              }
            : undefined,
        });
      }
      return addObject(
        object(device).createBindGroupLayout({
          label: readStringView(descriptor + 4, true),
          entries,
        }),
      );
    },
    wgpuDeviceCreateBindGroup: (device, descriptor) => {
      const count = u32()[(descriptor + 16) >>> 2];
      const pointer = u32()[(descriptor + 20) >>> 2];
      const entries = [];
      for (let index = 0; index < count; index += 1) {
        const item = pointer + index * 40;
        const buffer = u32()[(item + 8) >>> 2];
        const sampler = u32()[(item + 32) >>> 2];
        const textureView = u32()[(item + 36) >>> 2];
        let resource;
        if (buffer) {
          const size = readU64(item + 24);
          resource = {
            buffer: object(buffer),
            offset: readU64(item + 16),
            size: size === -1 ? undefined : size,
          };
        } else {
          resource = object(sampler || textureView);
        }
        entries.push({ binding: u32()[(item + 4) >>> 2], resource });
      }
      return addObject(
        object(device).createBindGroup({
          label: readStringView(descriptor + 4, true),
          layout: object(u32()[(descriptor + 12) >>> 2]),
          entries,
        }),
      );
    },
    wgpuDeviceCreatePipelineLayout: (device, descriptor) => {
      const count = u32()[(descriptor + 12) >>> 2];
      const pointer = u32()[(descriptor + 16) >>> 2];
      const bindGroupLayouts = [];
      for (let index = 0; index < count; index += 1) {
        bindGroupLayouts.push(object(u32()[(pointer + index * 4) >>> 2]));
      }
      return addObject(
        object(device).createPipelineLayout({
          label: readStringView(descriptor + 4, true),
          bindGroupLayouts,
        }),
      );
    },
    wgpuDeviceCreateRenderPipeline: (device, descriptor) =>
      addObject(object(device).createRenderPipeline(renderPipelineDescriptor(descriptor))),
    wgpuDeviceCreateCommandEncoder: (device, descriptor) =>
      addObject(
        object(device).createCommandEncoder(
          descriptor ? { label: readStringView(descriptor + 4, true) } : undefined,
        ),
      ),
    wgpuCommandEncoderBeginRenderPass: (encoder, descriptor) => {
      const count = u32()[(descriptor + 12) >>> 2];
      const pointer = u32()[(descriptor + 16) >>> 2];
      const colorAttachments = [];
      for (let index = 0; index < count; index += 1) {
        const attachment = pointer + index * 56;
        const view = u32()[(attachment + 4) >>> 2];
        if (!view) {
          colorAttachments.push(undefined);
          continue;
        }
        const depthSlice = u32()[(attachment + 8) >>> 2];
        colorAttachments.push({
          view: object(view),
          depthSlice: depthSlice === 0xffffffff ? undefined : depthSlice,
          resolveTarget: object(u32()[(attachment + 12) >>> 2]),
          loadOp: LoadOp[i32()[(attachment + 16) >>> 2]],
          storeOp: StoreOp[i32()[(attachment + 20) >>> 2]],
          clearValue: color(attachment + 24),
        });
      }
      const depthPointer = u32()[(descriptor + 20) >>> 2];
      const depthStencilAttachment = depthPointer
        ? {
            view: object(u32()[(depthPointer + 4) >>> 2]),
            depthLoadOp: LoadOp[i32()[(depthPointer + 8) >>> 2]],
            depthStoreOp: StoreOp[i32()[(depthPointer + 12) >>> 2]],
            depthClearValue: f32()[(depthPointer + 16) >>> 2],
            depthReadOnly: Boolean(u32()[(depthPointer + 20) >>> 2]),
            stencilLoadOp: LoadOp[i32()[(depthPointer + 24) >>> 2]],
            stencilStoreOp: StoreOp[i32()[(depthPointer + 28) >>> 2]],
            stencilClearValue: u32()[(depthPointer + 32) >>> 2],
            stencilReadOnly: Boolean(u32()[(depthPointer + 36) >>> 2]),
          }
        : undefined;
      return addObject(
        object(encoder).beginRenderPass({
          label: readStringView(descriptor + 4, true),
          colorAttachments,
          depthStencilAttachment,
        }),
      );
    },
    wgpuCommandEncoderFinish: (encoder) => addObject(object(encoder).finish()),
    wgpuCommandEncoderCopyBufferToTexture: (encoder, source, destination, size) =>
      object(encoder).copyBufferToTexture(
        texelCopyBuffer(source),
        texelCopyTexture(destination),
        extent3D(size),
      ),
    wgpuCommandEncoderCopyTextureToTexture: (encoder, source, destination, size) =>
      object(encoder).copyTextureToTexture(
        texelCopyTexture(source),
        texelCopyTexture(destination),
        extent3D(size),
      ),
    wgpuQueueSubmit: (queue, count, commands) => {
      const values = [];
      for (let index = 0; index < count; index += 1) {
        values.push(object(u32()[(commands + index * 4) >>> 2]));
      }
      if (preparedSurfaceTexture) {
        preparedCaptureBytesPerRow = Math.ceil((preparedSurfaceWidth * 4) / 256) * 256;
        preparedCaptureBuffer = preparedDevice.createBuffer({
          size: preparedCaptureBytesPerRow * preparedSurfaceHeight,
          usage: GPUBufferUsage.COPY_DST | GPUBufferUsage.MAP_READ,
        });
        preparedCaptureBuffers.push(preparedCaptureBuffer);
        const captureEncoder = preparedDevice.createCommandEncoder();
        captureEncoder.copyTextureToBuffer(
          { texture: preparedSurfaceTexture },
          {
            buffer: preparedCaptureBuffer,
            bytesPerRow: preparedCaptureBytesPerRow,
            rowsPerImage: preparedSurfaceHeight,
          },
          {
            width: preparedSurfaceWidth,
            height: preparedSurfaceHeight,
            depthOrArrayLayers: 1,
          },
        );
        values.push(captureEncoder.finish());
      }
      object(queue).submit(values);
    },
    wgpuQueueWriteBuffer: (queue, buffer, offset, data, size) =>
      object(queue).writeBuffer(object(buffer), Number(offset), u8(), data, size),
    wgpuQueueWriteTexture: (queue, destination, data, dataSize, layout, size) =>
      object(queue).writeTexture(
        texelCopyTexture(destination),
        u8().subarray(data, data + dataSize),
        texelCopyLayout(layout),
        extent3D(size),
      ),
    wgpuRenderPassEncoderSetBindGroup: (pass, index, group, count, offsets) => {
      if (!count) object(pass).setBindGroup(index, object(group));
      else object(pass).setBindGroup(index, object(group), u32(), offsets >>> 2, count);
    },
    wgpuRenderPassEncoderSetPipeline: (pass, pipeline) =>
      object(pass).setPipeline(object(pipeline)),
    wgpuRenderPassEncoderSetStencilReference: (pass, reference) =>
      object(pass).setStencilReference(reference >>> 0),
    wgpuRenderPassEncoderSetVertexBuffer: (pass, slot, buffer, offset, size) =>
      object(pass).setVertexBuffer(
        slot,
        object(buffer),
        Number(offset),
        size === -1n ? undefined : Number(size),
      ),
    wgpuRenderPassEncoderSetIndexBuffer: (pass, buffer, format, offset, size) =>
      object(pass).setIndexBuffer(
        object(buffer),
        IndexFormat[format],
        Number(offset),
        size === -1n ? undefined : Number(size),
      ),
    wgpuRenderPassEncoderDraw: (pass, vertexCount, instanceCount, firstVertex, firstInstance) =>
      object(pass).draw(vertexCount, instanceCount, firstVertex >>> 0, firstInstance >>> 0),
    wgpuRenderPassEncoderDrawIndexed: (
      pass,
      indexCount,
      instanceCount,
      firstIndex,
      baseVertex,
      firstInstance,
    ) => object(pass).drawIndexed(
      indexCount,
      instanceCount,
      firstIndex >>> 0,
      baseVertex,
      firstInstance >>> 0,
    ),
    wgpuRenderPassEncoderSetViewport: (pass, x, y, width, height, minimum, maximum) =>
      object(pass).setViewport(x, y, width, height, minimum, maximum),
    wgpuRenderPassEncoderSetScissorRect: (pass, x, y, width, height) =>
      object(pass).setScissorRect(x, y, width, height),
    wgpuRenderPassEncoderEnd: (pass) => object(pass).end(),
    wgpuDeviceDestroy: (device) => {
      if (object(device) === preparedDevice) destroyAfterSubmit = true;
      else object(device)?.destroy();
    },
  };

  for (const name of [
    "wgpuQueue", "wgpuBuffer", "wgpuDevice", "wgpuAdapter", "wgpuTexture",
    "wgpuTextureView", "wgpuShaderModule", "wgpuCommandEncoder",
    "wgpuRenderPipeline", "wgpuBindGroupLayout", "wgpuRenderPassEncoder",
  ]) {
    imports[`${name}AddRef`] = addRef;
  }
  for (const name of [
    "wgpuQueue", "wgpuBuffer", "wgpuDevice", "wgpuAdapter", "wgpuSampler",
    "wgpuSurface", "wgpuTexture", "wgpuInstance", "wgpuTextureView",
    "wgpuShaderModule", "wgpuBindGroup", "wgpuCommandBuffer",
    "wgpuCommandEncoder", "wgpuPipelineLayout", "wgpuRenderPassEncoder",
    "wgpuRenderPipeline", "wgpuBindGroupLayout",
  ]) {
    imports[`${name}Release`] = release;
  }
  imports.wgpuAdapterInfoFreeMembers = (info) => {
    for (let index = 0; index < 4; index += 1) {
      const stringView = info + 4 + index * 8;
      const data = u32()[stringView >>> 2];
      const length = u32()[(stringView + 4) >>> 2];
      if (data) wasm().__wbindgen_free(data, length, 1);
    }
  };
  imports.wgpuSurfaceCapabilitiesFreeMembers = (capabilities) => {
    const formats = u32()[(capabilities + 20) >>> 2];
    if (formats) wasm().__wbindgen_free(formats, 4, 4);
  };
  return imports;
}
