#!/usr/bin/env python3
"""Generate compiled-module inventories for every mechanical Metal target."""

from __future__ import annotations

import argparse
import pathlib
import sys
import tomllib
from collections import defaultdict


def build(manifest_path: pathlib.Path) -> dict[pathlib.Path, str]:
    with manifest_path.open("rb") as source:
        manifest = tomllib.load(source)
    targets_by_crate: dict[str, set[str]] = defaultdict(set)
    for unit in manifest.get("translation_unit", []):
        for value in unit.get("rust_targets", []):
            target = str(value)
            parts = pathlib.PurePosixPath(target).parts
            if (
                len(parts) >= 7
                and parts[0] == "crates"
                and parts[2:5] == ("src", "mechanical_port", "source")
                and target.endswith(".rs")
            ):
                targets_by_crate[parts[1]].add(target)

    rendered: dict[pathlib.Path, str] = {}
    for crate, targets in sorted(targets_by_crate.items()):
        prefix = f"crates/{crate}/src/mechanical_port/"
        lines = [
            "//! @generated by the Metal campaign authority; do not edit by hand.",
            "#![allow(unused_imports)]",
            "",
        ]
        for target in sorted(targets):
            module_parts = pathlib.PurePosixPath(
                target.removeprefix(prefix)
            ).with_suffix("").parts
            lines.append(
                "use crate::mechanical_port::" + "::".join(module_parts) + " as _;"
            )
        lines.extend(
            [
                "",
                f"pub(crate) const MANIFEST_TARGET_COUNT: usize = {len(targets)};",
                "const _: [(); MANIFEST_TARGET_COUNT] = [(); MANIFEST_TARGET_COUNT];",
                "",
            ]
        )
        rendered[
            pathlib.Path("crates")
            / crate
            / "src"
            / "mechanical_port"
            / "target_inventory.rs"
        ] = "\n".join(lines)
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=pathlib.Path, required=True)
    parser.add_argument("--manifest", type=pathlib.Path, required=True)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    repo_root = args.repo_root.resolve()
    rendered = build(args.manifest.resolve())
    drifted: list[pathlib.Path] = []
    for relative, content in rendered.items():
        path = repo_root / relative
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        elif not path.is_file() or path.read_text(encoding="utf-8") != content:
            drifted.append(relative)
    if drifted:
        for path in drifted:
            print(f"compiled target inventory drifted: {path}", file=sys.stderr)
        return 1
    print(f"compiled target inventories: {len(rendered)} crates")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
