//! Literal fixture values from upstream virtual_layout_grid_test.cpp at dc75beed.
use super::{ColumnCase, RowCase, VirtualGridTrack, VirtualTrackSizing};
pub(super) const ROW_CASES: &[RowCase] = &[
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 40.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 80.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
        ],
        heights: &[150.0, 50.0, 50.0, 100.0, 150.0],
        gap: 0.0,
        row_space: 300.0,
        tops: &[0.0, 150.0, 200.0, 280.0, 380.0],
        height: -1.0,
    },
    RowCase {
        rows: &[],
        heights: &[150.0, 200.0, 80.0, 80.0, 100.0, 150.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 160.0, 370.0, 460.0, 550.0, 660.0],
        height: 810.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 10.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 10.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 80.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 80.0,
            },
        ],
        heights: &[50.0, 150.0, 80.0, 80.0, 80.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0, 90.0, 140.0, 230.0, 320.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::AutoSize,
            min_value: 0.0,
            max_sizing: VirtualTrackSizing::AutoSize,
            max_value: 0.0,
        }],
        heights: &[150.0, 80.0, 50.0, 80.0, 80.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0, 160.0, 250.0, 310.0, 400.0],
        height: -1.0,
    },
    RowCase {
        rows: &[],
        heights: &[100.0, 50.0, 50.0, 50.0, 150.0],
        gap: 0.0,
        row_space: -1.0,
        tops: &[0.0, 100.0, 150.0, 200.0, 250.0],
        height: 400.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 10.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
        ],
        heights: &[20.0],
        gap: 0.0,
        row_space: -1.0,
        tops: &[0.0],
        height: 20.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::Points,
            min_value: 0.0,
            max_sizing: VirtualTrackSizing::Points,
            max_value: 0.0,
        }],
        heights: &[200.0, 80.0, 80.0, 20.0, 200.0],
        gap: 0.0,
        row_space: 300.0,
        tops: &[0.0, 0.0, 80.0, 160.0, 180.0],
        height: -1.0,
    },
    RowCase {
        rows: &[],
        heights: &[100.0],
        gap: 0.0,
        row_space: 300.0,
        tops: &[0.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::Points,
            min_value: 40.0,
            max_sizing: VirtualTrackSizing::Points,
            max_value: 40.0,
        }],
        heights: &[20.0, 20.0],
        gap: 0.0,
        row_space: 400.0,
        tops: &[0.0, 40.0],
        height: -1.0,
    },
    RowCase {
        rows: &[],
        heights: &[80.0, 200.0, 80.0, 150.0],
        gap: 0.0,
        row_space: 300.0,
        tops: &[0.0, 80.0, 280.0, 360.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::AutoSize,
            min_value: 0.0,
            max_sizing: VirtualTrackSizing::AutoSize,
            max_value: 0.0,
        }],
        heights: &[100.0, 20.0, 50.0, 200.0, 80.0, 200.0],
        gap: 0.0,
        row_space: 400.0,
        tops: &[0.0, 100.0, 120.0, 170.0, 370.0, 450.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::Points,
            min_value: 0.0,
            max_sizing: VirtualTrackSizing::Percent,
            max_value: 10.0,
        }],
        heights: &[200.0, 50.0, 80.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0, 50.0, 110.0],
        height: -1.0,
    },
    RowCase {
        rows: &[],
        heights: &[50.0],
        gap: 0.0,
        row_space: 400.0,
        tops: &[0.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
        ],
        heights: &[20.0, 150.0, 200.0, 200.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0, 30.0, 190.0, 400.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
        ],
        heights: &[50.0, 50.0, 200.0, 100.0, 20.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 60.0, 120.0, 330.0, 440.0],
        height: 460.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 120.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 80.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 40.0,
            },
        ],
        heights: &[200.0, 100.0, 80.0, 20.0, 200.0, 200.0],
        gap: 0.0,
        row_space: 300.0,
        tops: &[0.0, 200.0, 320.0, 400.0, 420.0, 620.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::Percent,
            min_value: 25.0,
            max_sizing: VirtualTrackSizing::Percent,
            max_value: 25.0,
        }],
        heights: &[50.0, 20.0, 100.0, 80.0, 50.0],
        gap: 0.0,
        row_space: 400.0,
        tops: &[0.0, 100.0, 120.0, 220.0, 300.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::AutoSize,
            min_value: 0.0,
            max_sizing: VirtualTrackSizing::Points,
            max_value: 80.0,
        }],
        heights: &[150.0, 200.0, 100.0, 100.0, 100.0],
        gap: 0.0,
        row_space: -1.0,
        tops: &[0.0, 150.0, 350.0, 450.0, 550.0],
        height: 650.0,
    },
    RowCase {
        rows: &[],
        heights: &[150.0, 100.0, 50.0, 20.0, 80.0, 50.0],
        gap: 0.0,
        row_space: -1.0,
        tops: &[0.0, 150.0, 250.0, 300.0, 320.0, 400.0],
        height: 450.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 80.0,
            },
        ],
        heights: &[100.0, 100.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0, 300.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::Points,
            min_value: 80.0,
            max_sizing: VirtualTrackSizing::Fr,
            max_value: 2.0,
        }],
        heights: &[150.0, 100.0, 150.0, 50.0, 20.0],
        gap: 0.0,
        row_space: 400.0,
        tops: &[0.0, 80.0, 180.0, 330.0, 380.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 50.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 50.0,
            },
        ],
        heights: &[100.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0],
        height: 20.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 80.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 0.0,
            },
        ],
        heights: &[200.0, 200.0, 80.0, 150.0, 50.0, 150.0],
        gap: 0.0,
        row_space: 300.0,
        tops: &[0.0, 200.0, 400.0, 480.0, 630.0, 680.0],
        height: -1.0,
    },
    RowCase {
        rows: &[],
        heights: &[80.0, 100.0, 80.0, 80.0, 100.0, 200.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0, 90.0, 200.0, 290.0, 380.0, 490.0],
        height: -1.0,
    },
    RowCase {
        rows: &[],
        heights: &[80.0],
        gap: 0.0,
        row_space: 300.0,
        tops: &[0.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::Percent,
            min_value: 10.0,
            max_sizing: VirtualTrackSizing::Percent,
            max_value: 10.0,
        }],
        heights: &[20.0, 20.0],
        gap: 0.0,
        row_space: 300.0,
        tops: &[0.0, 30.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 25.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 50.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
        ],
        heights: &[200.0, 200.0, 150.0, 50.0, 100.0],
        gap: 0.0,
        row_space: 300.0,
        tops: &[0.0, 75.0, 75.0, 225.0, 275.0],
        height: -1.0,
    },
    RowCase {
        rows: &[],
        heights: &[200.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::Points,
            min_value: 120.0,
            max_sizing: VirtualTrackSizing::Points,
            max_value: 120.0,
        }],
        heights: &[20.0, 50.0, 20.0, 20.0, 50.0],
        gap: 0.0,
        row_space: -1.0,
        tops: &[0.0, 120.0, 170.0, 190.0, 210.0],
        height: 260.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::AutoSize,
            min_value: 0.0,
            max_sizing: VirtualTrackSizing::Points,
            max_value: 80.0,
        }],
        heights: &[100.0, 80.0, 100.0],
        gap: 0.0,
        row_space: -1.0,
        tops: &[0.0, 100.0, 180.0],
        height: 280.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 25.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 80.0,
            },
        ],
        heights: &[200.0, 20.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0, 300.0],
        height: -1.0,
    },
    RowCase {
        rows: &[],
        heights: &[50.0, 20.0, 200.0, 20.0, 200.0, 20.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 60.0, 90.0, 300.0, 330.0, 540.0],
        height: 560.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
        ],
        heights: &[150.0, 50.0, 200.0, 200.0, 80.0],
        gap: 0.0,
        row_space: -1.0,
        tops: &[0.0, 150.0, 200.0, 400.0, 600.0],
        height: 680.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 10.0,
            },
        ],
        heights: &[100.0, 200.0, 80.0, 200.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 110.0, 320.0, 410.0],
        height: 610.0,
    },
    RowCase {
        rows: &[],
        heights: &[100.0, 50.0],
        gap: 10.0,
        row_space: 300.0,
        tops: &[0.0, 110.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 10.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 10.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 25.0,
            },
        ],
        heights: &[20.0, 20.0, 80.0, 20.0, 200.0],
        gap: 0.0,
        row_space: -1.0,
        tops: &[0.0, 20.0, 54.0, 134.0, 154.0],
        height: 340.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 25.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
        ],
        heights: &[100.0, 50.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 10.0],
        height: 60.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 80.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 50.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 80.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 80.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
        ],
        heights: &[50.0, 20.0, 20.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 90.0, 180.0],
        height: 200.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 25.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 25.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 50.0,
            },
        ],
        heights: &[50.0, 200.0, 50.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0, 60.0, 170.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 10.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 25.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
        ],
        heights: &[80.0, 150.0, 20.0, 200.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 90.0, 250.0, 280.0],
        height: 480.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 25.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
        ],
        heights: &[100.0, 80.0, 50.0],
        gap: 10.0,
        row_space: 300.0,
        tops: &[0.0, 160.0, 250.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 40.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 40.0,
            },
        ],
        heights: &[150.0, 100.0, 20.0, 20.0, 100.0],
        gap: 10.0,
        row_space: 300.0,
        tops: &[0.0, 160.0, 210.0, 240.0, 270.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 80.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 50.0,
            },
        ],
        heights: &[100.0, 80.0, 50.0, 80.0],
        gap: 10.0,
        row_space: 300.0,
        tops: &[0.0, 110.0, 200.0, 260.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 80.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 80.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 40.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 40.0,
            },
        ],
        heights: &[100.0, 150.0, 20.0, 80.0, 50.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 110.0, 320.0, 370.0, 460.0],
        height: 510.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::AutoSize,
            min_value: 0.0,
            max_sizing: VirtualTrackSizing::Points,
            max_value: 0.0,
        }],
        heights: &[200.0, 200.0, 80.0, 100.0, 20.0, 150.0],
        gap: 0.0,
        row_space: -1.0,
        tops: &[0.0, 200.0, 400.0, 480.0, 580.0, 600.0],
        height: 750.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 50.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
        ],
        heights: &[20.0, 100.0, 50.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0, 210.0, 350.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 25.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 25.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 50.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 80.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
        ],
        heights: &[150.0, 150.0],
        gap: 10.0,
        row_space: 300.0,
        tops: &[0.0, 85.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 10.0,
            },
        ],
        heights: &[200.0, 80.0],
        gap: 0.0,
        row_space: -1.0,
        tops: &[0.0, 200.0],
        height: 280.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::AutoSize,
            min_value: 0.0,
            max_sizing: VirtualTrackSizing::Fr,
            max_value: 2.0,
        }],
        heights: &[100.0, 200.0, 100.0],
        gap: 0.0,
        row_space: 400.0,
        tops: &[0.0, 100.0, 300.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::Points,
            min_value: 40.0,
            max_sizing: VirtualTrackSizing::Points,
            max_value: 40.0,
        }],
        heights: &[20.0, 200.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0, 50.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 80.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 40.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 120.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 50.0,
            },
        ],
        heights: &[150.0, 100.0, 50.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 90.0, 140.0],
        height: 260.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 10.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
        ],
        heights: &[150.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::AutoSize,
            min_value: 0.0,
            max_sizing: VirtualTrackSizing::AutoSize,
            max_value: 0.0,
        }],
        heights: &[50.0, 80.0],
        gap: 0.0,
        row_space: 300.0,
        tops: &[0.0, 50.0],
        height: -1.0,
    },
    RowCase {
        rows: &[],
        heights: &[20.0, 80.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 30.0],
        height: 110.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::Percent,
            min_value: 25.0,
            max_sizing: VirtualTrackSizing::Percent,
            max_value: 50.0,
        }],
        heights: &[50.0, 80.0, 100.0, 80.0, 20.0, 20.0],
        gap: 10.0,
        row_space: 300.0,
        tops: &[0.0, 85.0, 175.0, 285.0, 375.0, 405.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::Percent,
            min_value: 10.0,
            max_sizing: VirtualTrackSizing::AutoSize,
            max_value: 0.0,
        }],
        heights: &[100.0, 100.0, 80.0, 150.0, 20.0, 50.0],
        gap: 0.0,
        row_space: 400.0,
        tops: &[0.0, 40.0, 140.0, 220.0, 370.0, 390.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::Points,
            min_value: 120.0,
            max_sizing: VirtualTrackSizing::Points,
            max_value: 120.0,
        }],
        heights: &[50.0, 100.0, 20.0, 150.0, 200.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0, 130.0, 240.0, 270.0, 430.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
        ],
        heights: &[200.0],
        gap: 0.0,
        row_space: 400.0,
        tops: &[0.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 120.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 25.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 25.0,
            },
        ],
        heights: &[150.0, 150.0, 200.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0, 160.0, 290.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 25.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 10.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
        ],
        heights: &[80.0, 100.0],
        gap: 10.0,
        row_space: 300.0,
        tops: &[0.0, 90.0],
        height: -1.0,
    },
    RowCase {
        rows: &[],
        heights: &[50.0, 80.0, 50.0, 200.0, 150.0],
        gap: 0.0,
        row_space: 400.0,
        tops: &[0.0, 50.0, 130.0, 180.0, 380.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
        ],
        heights: &[150.0, 20.0, 20.0, 50.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0, 160.0, 290.0, 320.0],
        height: -1.0,
    },
    RowCase {
        rows: &[],
        heights: &[200.0, 50.0, 50.0],
        gap: 10.0,
        row_space: 300.0,
        tops: &[0.0, 210.0, 270.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 120.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
        ],
        heights: &[100.0, 80.0, 50.0, 20.0, 50.0],
        gap: 10.0,
        row_space: 300.0,
        tops: &[0.0, 110.0, 200.0, 330.0, 360.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 80.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 10.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
        ],
        heights: &[80.0, 80.0, 20.0, 80.0, 100.0, 50.0],
        gap: 0.0,
        row_space: 400.0,
        tops: &[0.0, 80.0, 160.0, 180.0, 260.0, 360.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 10.0,
            },
        ],
        heights: &[200.0, 100.0],
        gap: 0.0,
        row_space: 400.0,
        tops: &[0.0, 200.0],
        height: -1.0,
    },
    RowCase {
        rows: &[],
        heights: &[80.0, 100.0, 20.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 90.0, 200.0],
        height: 220.0,
    },
    RowCase {
        rows: &[],
        heights: &[200.0],
        gap: 0.0,
        row_space: 400.0,
        tops: &[0.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 50.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 50.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
        ],
        heights: &[150.0, 50.0, 20.0, 150.0, 20.0, 150.0],
        gap: 0.0,
        row_space: 400.0,
        tops: &[0.0, 200.0, 250.0, 270.0, 420.0, 440.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 10.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 10.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 50.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 0.0,
            },
        ],
        heights: &[100.0, 200.0, 200.0, 150.0],
        gap: 10.0,
        row_space: 300.0,
        tops: &[0.0, 40.0, 200.0, 210.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 40.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 40.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 25.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 10.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
        ],
        heights: &[50.0, 80.0, 80.0, 20.0],
        gap: 0.0,
        row_space: 400.0,
        tops: &[0.0, 40.0, 140.0, 380.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::Percent,
            min_value: 10.0,
            max_sizing: VirtualTrackSizing::AutoSize,
            max_value: 0.0,
        }],
        heights: &[50.0, 20.0, 100.0, 50.0, 100.0, 150.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0, 50.0, 80.0, 190.0, 250.0, 360.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 10.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 10.0,
            },
        ],
        heights: &[200.0, 80.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 210.0],
        height: 300.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 50.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 50.0,
            },
        ],
        heights: &[200.0, 20.0, 50.0, 200.0, 150.0],
        gap: 0.0,
        row_space: -1.0,
        tops: &[0.0, 200.0, 220.0, 530.0, 730.0],
        height: 620.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 80.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
        ],
        heights: &[20.0, 200.0, 200.0],
        gap: 0.0,
        row_space: 300.0,
        tops: &[0.0, 20.0, 220.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 50.0,
            },
        ],
        heights: &[80.0, 150.0, 20.0],
        gap: 10.0,
        row_space: 300.0,
        tops: &[0.0, 90.0, 250.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::Points,
            min_value: 40.0,
            max_sizing: VirtualTrackSizing::Points,
            max_value: 40.0,
        }],
        heights: &[200.0],
        gap: 10.0,
        row_space: 400.0,
        tops: &[0.0],
        height: -1.0,
    },
    RowCase {
        rows: &[],
        heights: &[200.0, 80.0],
        gap: 0.0,
        row_space: 300.0,
        tops: &[0.0, 200.0],
        height: -1.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 50.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
        ],
        heights: &[50.0, 50.0, 150.0, 20.0, 20.0, 150.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 255.0, 315.0, 475.0, 505.0, 535.0],
        height: 490.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
        ],
        heights: &[50.0, 150.0, 50.0],
        gap: 10.0,
        row_space: 300.0,
        tops: &[0.0, 60.0, 250.0],
        height: -1.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::Points,
            min_value: 0.0,
            max_sizing: VirtualTrackSizing::Fr,
            max_value: 0.5,
        }],
        heights: &[80.0, 100.0, 200.0, 200.0],
        gap: 0.0,
        row_space: -1.0,
        tops: &[0.0, 40.0, 140.0, 340.0],
        height: 540.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
        ],
        heights: &[200.0, 50.0, 50.0, 80.0, 80.0, 20.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 210.0, 320.0, 380.0, 470.0, 560.0],
        height: 580.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 120.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
        ],
        heights: &[200.0, 50.0],
        gap: 0.0,
        row_space: -1.0,
        tops: &[0.0, 200.0],
        height: 250.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 120.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 80.0,
            },
        ],
        heights: &[50.0, 200.0, 100.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 250.0, 380.0],
        height: 480.0,
    },
    RowCase {
        rows: &[VirtualGridTrack {
            min_sizing: VirtualTrackSizing::Percent,
            min_value: 10.0,
            max_sizing: VirtualTrackSizing::AutoSize,
            max_value: 0.0,
        }],
        heights: &[150.0, 20.0],
        gap: 0.0,
        row_space: -1.0,
        tops: &[0.0, 150.0],
        height: 170.0,
    },
    RowCase {
        rows: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 10.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 10.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 50.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
        ],
        heights: &[200.0, 80.0, 80.0, 20.0, 100.0],
        gap: 10.0,
        row_space: -1.0,
        tops: &[0.0, 70.0, 160.0, 470.0, 500.0],
        height: 600.0,
    },
];
pub(super) const COLUMN_CASES: &[ColumnCase] = &[
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 10.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
        ],
        widths: &[20.0, 100.0, 150.0, 50.0],
        gap: 10.0,
        column_space: 300.0,
        resize: true,
        starts: &[0.0, 160.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 80.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
        ],
        widths: &[100.0, 50.0, 100.0, 50.0],
        gap: 10.0,
        column_space: 400.0,
        resize: true,
        starts: &[0.0, 205.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 40.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 40.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
        ],
        widths: &[20.0, 50.0, 20.0, 50.0],
        gap: 10.0,
        column_space: 400.0,
        resize: false,
        starts: &[0.0, 50.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 40.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
        ],
        widths: &[20.0, 80.0, 100.0, 100.0, 100.0, 100.0],
        gap: 10.0,
        column_space: 400.0,
        resize: true,
        starts: &[0.0, 162.0, 324.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 80.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 80.0,
            },
        ],
        widths: &[50.0, 100.0, 50.0, 100.0],
        gap: 0.0,
        column_space: 300.0,
        resize: false,
        starts: &[0.0, 80.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 120.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
        ],
        widths: &[80.0, 80.0, 20.0, 100.0, 150.0, 20.0],
        gap: 0.0,
        column_space: 400.0,
        resize: false,
        starts: &[0.0, 120.0, 280.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 80.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 40.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 50.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 25.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 25.0,
            },
        ],
        widths: &[20.0, 150.0, 100.0, 80.0, 100.0, 150.0],
        gap: 0.0,
        column_space: 300.0,
        resize: true,
        starts: &[0.0, 80.0, 225.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
        ],
        widths: &[50.0, 20.0, 50.0, 80.0, 50.0, 150.0],
        gap: 0.0,
        column_space: 300.0,
        resize: false,
        starts: &[0.0, 150.0, 150.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 40.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 80.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 40.0,
            },
        ],
        widths: &[50.0, 150.0, 80.0, 100.0, 80.0, 20.0],
        gap: 10.0,
        column_space: -1.0,
        resize: true,
        starts: &[0.0, 50.0, 210.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
        ],
        widths: &[50.0, 20.0, 80.0, 50.0],
        gap: 0.0,
        column_space: -1.0,
        resize: true,
        starts: &[0.0, 80.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 25.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
        ],
        widths: &[50.0, 20.0, 150.0, 80.0],
        gap: 0.0,
        column_space: 300.0,
        resize: true,
        starts: &[0.0, 100.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 50.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
        ],
        widths: &[50.0, 150.0, 50.0, 150.0],
        gap: 10.0,
        column_space: -1.0,
        resize: false,
        starts: &[0.0, 115.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
        ],
        widths: &[80.0, 100.0, 100.0, 50.0],
        gap: 0.0,
        column_space: 400.0,
        resize: true,
        starts: &[0.0, 100.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 10.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 10.0,
            },
        ],
        widths: &[50.0, 150.0, 20.0, 150.0],
        gap: 10.0,
        column_space: 400.0,
        resize: true,
        starts: &[0.0, 360.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 120.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
        ],
        widths: &[20.0, 80.0, 150.0, 80.0, 150.0, 80.0],
        gap: 0.0,
        column_space: 400.0,
        resize: true,
        starts: &[0.0, 120.0, 240.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Percent,
                min_value: 50.0,
                max_sizing: VirtualTrackSizing::Percent,
                max_value: 50.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
        ],
        widths: &[150.0, 100.0, 50.0, 20.0],
        gap: 0.0,
        column_space: -1.0,
        resize: false,
        starts: &[0.0, 125.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 2.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 1.0,
            },
        ],
        widths: &[20.0, 80.0, 20.0, 150.0, 50.0, 20.0],
        gap: 0.0,
        column_space: -1.0,
        resize: true,
        starts: &[0.0, 20.0, 100.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::AutoSize,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 80.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 120.0,
                max_sizing: VirtualTrackSizing::Points,
                max_value: 120.0,
            },
        ],
        widths: &[150.0, 50.0, 20.0, 20.0, 100.0, 150.0],
        gap: 10.0,
        column_space: -1.0,
        resize: true,
        starts: &[0.0, 160.0, 195.0],
    },
    ColumnCase {
        columns: &[
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 80.0,
                max_sizing: VirtualTrackSizing::AutoSize,
                max_value: 0.0,
            },
            VirtualGridTrack {
                min_sizing: VirtualTrackSizing::Points,
                min_value: 0.0,
                max_sizing: VirtualTrackSizing::Fr,
                max_value: 0.5,
            },
        ],
        widths: &[100.0, 150.0, 150.0, 50.0],
        gap: 0.0,
        column_space: -1.0,
        resize: true,
        starts: &[0.0, 150.0],
    },
];
