# Generated dependency metadata. Rust sources stay in their owning package.
[package]
name = "symphonia-utils-xiph"
version = "0.5.5"
edition = "2018"
autobins = false
autoexamples = false
autotests = false
autobenches = false
build = false

[lib]
path = "lib.rs"
name = "symphonia_utils_xiph"

[features]
"__bazel_dependency_default" = ["metadata"]
"metadata" = ["dep:symphonia-metadata"]
"default" = []

[dependencies]
"symphonia-core" = { "version" = "0.5.5" }
"symphonia-metadata" = { "version" = "0.5.5", "optional" = true }
