# Generated dependency metadata. Rust sources stay in their owning package.
[package]
name = "luaur-rt"
version = "0.1.8"
edition = "2021"
autobins = false
autoexamples = false
autotests = false
autobenches = false
build = "build.rs"

[lib]
path = "lib.rs"
name = "luaur_rt"

[features]
"async" = ["dep:futures-util"]
"compiler" = ["dep:luaur-ast", "dep:luaur-bytecode", "dep:luaur-compiler"]
"__bazel_dependency_default" = ["compiler"]
"macros" = ["dep:luaur-rt-derive"]
"send" = []
"serde" = ["dep:serde"]
"typecheck" = ["compiler", "dep:luaur-analysis", "dep:luaur-config"]
"default" = []

[dependencies]
"futures-util" = { "version" = "0.3", "optional" = true }
"luaur-analysis" = { "version" = "0.1.8", "optional" = true }
"luaur-ast" = { "version" = "0.1.8", "optional" = true, "path" = "../luaur-ast", "default-features" = false, "features" = ["__bazel_dependency_default"] }
"luaur-bytecode" = { "version" = "0.1.8", "optional" = true, "path" = "../luaur-bytecode", "default-features" = false, "features" = ["__bazel_dependency_default"] }
"luaur-common" = { "version" = "0.1.8", "path" = "../luaur-common", "default-features" = false, "features" = ["__bazel_dependency_default"] }
"luaur-compiler" = { "version" = "0.1.8", "optional" = true, "path" = "../luaur-compiler", "default-features" = false, "features" = ["__bazel_dependency_default"] }
"luaur-config" = { "version" = "0.1.8", "optional" = true }
"luaur-rt-derive" = { "version" = "0.1.8", "optional" = true }
"luaur-vm" = { "version" = "0.1.8", "path" = "../luaur-vm", "default-features" = false, "features" = ["__bazel_dependency_default"] }
"serde" = { "version" = "1.0", "optional" = true, "default-features" = false, "features" = ["std"] }

[build-dependencies]
"luaur-common" = { "version" = "0.1.8", "path" = "../luaur-common", "default-features" = false, "features" = ["__bazel_dependency_default"] }
"luaur-compiler" = { "version" = "0.1.8", "path" = "../luaur-compiler", "default-features" = false, "features" = ["__bazel_dependency_default"] }
